### ISSUE TITLE
Kippo attacks are not shown in the attacks page

### ISSUE THREAD

**Issue by aabed** [threatstream/mhn#105]
When there is an attack on a kippo sensor the number of attacks is increased in the sensors page
but when I click on it, nothing is displayed in the attack page

**Comment by jt6211** [comment]
I think this may be do to the attack coming from an rfc1918 address and mnenmosyne being configured to ignore them.

We increment the count based on the event's channel:  https://github.com/threatstream/mnemosyne/blob/master/persistance/mnemodb.py#L133-L137 before we know if the event will create a session metadata record: https://github.com/threatstream/mnemosyne/blob/master/normalizer/modules/kippo_events.py#L28

Can you follow this section and see if it fixes the issue?
https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide#i-have-an-internally-deployed-honeypot-and-even-when-i-scan-it-i-see-not-events-in-mhn

**Comment by aabed** [comment]
Thank you for your reply, I have changed it and now everything is working
