### ISSUE TITLE
honey map connection reset

### ISSUE THREAD

**Issue by silverfoxy** [threatstream/mhn#106]
I configured MHN Server with default settings, everything is working fine all the services are up and running under supervisorctl.
But when I try to view map, the corresponding iframe doesn't load up and when I go straight to port 3000, my connection is reset.
I tried connecting to port 3000 locally via nc on the mhn server and it succeeds. (with -vv switch)
but when I try to connect remotely it times out.
IPTables is disabled. 
honeymap and geoloc logs show nothing wrong, honeymap.err says it connected to hpfeeds on localhost:10000 and bound honeymap webserver to 0.0.0.0:3000 successfully.
What's the problem?
Edit:
seems like its working fine and the issue is with accessing it from the outside, it loads up locally,
how can I change its port? to run on a port other than 3000

**Comment by jt6211** [comment]
Edit `/opt/honeymap/server/config.json` and then restart honeymap.
