### ISSUE TITLE
No Destination on Honeymap

### ISSUE THREAD

**Issue by v1s0n** [threatstream/mhn#108]
Everything else appears to be working.  All firewall ports are open and data is getting from the sensors back to MHN (TCP-80, 3000 and 10000).  The correct external IP's are appearing under "Sensors".  The correct src IP's are showing up under "Attacks" with the correct sensor name that picked up the event.  For some reason the Honeymap will only show the red attacker location and not the yellow sensor location.  I have looked up the sensor IP's on MaxMind and they are located correctly there.

I have deployed sensors in both AWS and Azure...not sure if it's something odd there.  The sensors are behind NAT's but the external IP's are displayed in MHN.

I feel like I am missing something stupid here..

**Comment by aabed** [comment]
Have you attacked the sensors from the same machine,ip,subnet?

**Comment by jt6211** [comment]
Any chance your sensors are deployed in Singapore? If so, this bug may
affect you.  This is a known bug in a third party library used by Honeymap.

https://github.com/threatstream/mhn/issues/54

--Jason

**Comment by bdiggler** [comment]
Thanks for the quick replies..

aabed... No, I have not tried to trigger an alert from the same machine, ip or subnet.  I can try that but my theory is it would scan it from the internal network using the internal 10.10.0.0/16 IP range...which won't get plotted on the map for obvious reasons.  I could try to scan it's external IP from itself...but wouldn't that plot itself on the map as a red (attacker) dot?

jt6311... No..nothing in Singapore.  I have tried 4 different regions between AWS and Azure.  I listed them below.  None of them plotted the yellow sensor on the map.  I only get red (attacker) dots.

Azure - Central US
Azure - East US
Azure - Japan West
AWS - US West (Oregon)

**Comment by jt6211** [comment]
Which honeypots are you using? Not all of them report their source IP.

On Thursday, January 8, 2015, bdiggler <notifications@github.com> wrote:

> Thanks for the quick replies..
>
> aabed... No, I have not tried to trigger an alert from the same machine,
> ip or subnet. I can try that but my theory is it would scan it from the
> internal network using the internal 10.10.0.0/16 IP range...which won't
> get plotted on the map for obvious reasons. I could try to scan it's
> external IP from itself...but wouldn't that plot itself on the map as a red
> (attacker) dot?
>
> jt6311... No..nothing in Singapore. I have tried 4 different regions
> between AWS and Azure. I listed them below. None of them plotted the yellow
> sensor on the map. I only get red (attacker) dots.
>
> Azure - Central US
> Azure - East US
> Azure - Japan West
> AWS - US West (Oregon)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/108#issuecomment-69184470>.
>


-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
<http://www.threatstream.com/>
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by bdiggler** [comment]
Primarily just Dionaea.  I did try glastopf on a few (dionaea was installed on the same sensors)...oddly enough glastopf didn't get plotted at all on the map.

**Comment by bdiggler** [comment]
After looking at the TCPDUMP's, I noticed a lot of "null" in the "2" attributes...and there is a missing "dest" field that I noticed in the other post that I don't have.  Where/how is this information acquired and where would I look next?

geoloc.events{"city": "Redmond", "type": "dionaea.connections", "countrycode": "US", "country": "United States", "latitude2": null, "longitude2": null, "longitude": -122.12059783935547, "country2": null, "source": "::ffff:23.99.201.11", "time": "2015-01-08 22:25:14", "latitude": 47.68009948730469, "countrycode2": null, "city2": null, "sensor": "2406974e-9772-11e4-8e0d-000d3a903a5f"}
22:25:14.611480 IP (tos 0x0, ttl 64, id 6159, offset 0, flags [DF], proto TCP (6), length 52)

d..c.....'...B..3.P...\....~..a["{\"city\":\"Redmond\",\"city2\":null,\"countrycode\":\"US\",\"countrycode2\":null,\"latitude\":47.68009948730469,\"latitude2\":null,\"longitude\":-122.12059783935547,\"longitude2\":null,\"type\":\"dionaea.connections\"}"]

**Comment by jt6211** [comment]
https://github.com/threatstream/hpfeeds/blob/master/examples/geoloc/processors.py#L57
 AND
https://github.com/threatstream/hpfeeds/blob/master/examples/geoloc/processors.py#L130-L152

On Thu, Jan 8, 2015 at 2:42 PM, bdiggler <notifications@github.com> wrote:

> After looking at the TCPDUMP's, I noticed a lot of "null" in the "2"
> attributes...and there is a missing "dest" field that I noticed in the
> other post that I don't have. Where/how is this information acquired and
> where would I look next?
>
> geoloc.events{"city": "Redmond", "type": "dionaea.connections",
> "countrycode": "US", "country": "United States", "latitude2": null,
> "longitude2": null, "longitude": -122.12059783935547, "country2": null,
> "source": "::ffff:23.99.201.11", "time": "2015-01-08 22:25:14", "latitude":
> 47.68009948730469, "countrycode2": null, "city2": null, "sensor":
> "2406974e-9772-11e4-8e0d-000d3a903a5f"}
> 22:25:14.611480 IP (tos 0x0, ttl 64, id 6159, offset 0, flags [DF], proto
> TCP (6), length 52)
>
>
> d..c.....'...B..3.P.......~..a["{\"city\":\"Redmond\",\"city2\":null,\"countrycode\":\"US\",\"countrycode2\":null,\"latitude\":47.68009948730469,\"latitude2\":null,\"longitude\":-122.12059783935547,\"longitude2\":null,\"type\":\"dionaea.connections\"}"]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/108#issuecomment-69263762>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
<http://www.threatstream.com/>
Phone:  386.235.0078 | Twitter:  @jason_trost
