### ISSUE TITLE
Query data straight from Mongodb

### ISSUE THREAD

**Issue by andrew-morris** [threatstream/mhn#110]
How can I query attacks reported by HPFeeds in MongoDB, similar to how the "attacks > search > IP address" function works?

Thanks!

**Comment by andrew-morris** [comment]
After a little more research, it looks like the Mnemosyne WebAPI might be what I'm looking for. Is there a way to enable this? Right now I'm getting "connection reset" when I attempt to connect
```
# curl http://127.0.0.1:8181
curl: (56) Recv failure: Connection reset by peer
```

**Comment by jt6211** [comment]
At least 2 Ways:

1. The MHN API can be used like this:  https://YOUR_MHN_SERVER/api/session/?limit=20&destination_ip=4.4.4.4&destination_port=22&api_key=XXXXXXXXX
2. Query mongo directly.

```
mongo mnemosyne
> db.session.find({destination_port:22, destination_ip:"4.4.4.4"})
```

**Comment by andrew-morris** [comment]
Thanks Jason- one more quick question

Doing this doesn't seem to yield any results for attacks that I can confirm. Will this work for attacks reported by Kippo? How can I replicate the MHN "search by IP address" functionality in the attacks tab?

Thanks again!

**Comment by andrew-morris** [comment]
disregard- I got it. Thanks! Had to switch the parameter to "source_ip"

--Andrew
