### ISSUE TITLE
Amun fails on ulimit command

### ISSUE THREAD

**Issue by superponible** [threatstream/mhn#111]
Trying to deploy amun on Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-37-generic x86_64)

<pre>
Switched to a new branch 'development'
+ AMUN_HOME=/opt/amun
+ sed -i 's/ip: 127.0.0.1/ip: 0.0.0.0/g' conf/amun.conf
+ sed -i 's/    vuln-http,/#   vuln-http,/g' conf/amun.conf
+ sed -i 's/log_modules:/log_modules:\
    log-hpfeeds/g' conf/amun.conf
+ echo 104854
+ ulimit -Hn 104854
deploy.sh: line 39: ulimit: open files: cannot modify limit: Invalid argument
</pre>

If I just run ulimit manually:

<pre>
root@host:/opt# ulimit
unlimited
</pre>

**Comment by d1str0** [comment]
Should work with latest code base on 14.04 and 16.04
