### ISSUE TITLE
kippo graph into MHN

### ISSUE THREAD

**Issue by aabed** [threatstream/mhn#112]
Hello, I will be working on cloning kippo-graph graphs into MHN
Just wanted to raise a flag as well as getting opinions

**Comment by jt6211** [comment]
+1

**Comment by CovertServer** [comment]
Seeing all of my Kippo pots in one hippo-graph on MHN would be really nice.

**Comment by deanboole** [comment]
+1

**Comment by andrew-morris** [comment]
@CovertServer 
![image](https://cloud.githubusercontent.com/assets/3838808/6204090/b14a897e-b50b-11e4-909d-351fcae29946.png)

**Comment by mercolino** [comment]
I made an Add-on before realize that MHn added some charts, chek the installation guide for he add-on (here)[https://itandsecuritystuffs.wordpress.com/2015/03/01/kippo-statistics-graphs-in-modern-honey-network-mhn/]

**Comment by aabed** [comment]
Nice Work
