### ISSUE TITLE
supervisorctl stop kippo does not work

### ISSUE THREAD

**Issue by mercolino** [threatstream/mhn#115]
Supervisor uses /opt/kippo/start.sh that start another process with the command kippo .... then kippo spawn another process with python twistd. When the command "supervisorctl stop kippo" is issued, the only process killed is the first process (start.sh) but not the subprocesses.

I find a workaround for this, the file /etc/supervisor/conf.d/kippo.cfg should be:

[program:kippo]
command=su kippo -c "authbind --deep twistd -n -y /opt/kippo/kippo.tac -l /opt/kippo/log/kippo.log --pidfile /opt/kippo/kippo.pid"
directory=/opt/kippo
stdout_logfile=/opt/kippo/log/kippo.out
stderr_logfile=/opt/kippo/log/kippo.err
autostart=true
autorestart=true
redirect_stderr=true
stopasgroup=true

With this  configuration start.sh is not used and supervisor launch the process with kippo, then it spawns the child with twistd, at the moment to use stop supervisor, it recognise the child process and kills it too....

This was tested on ubuntu 14.04 LTS.

Regards
Miguel

**Comment by Waseem-farooqui** [comment]
@mercolino have to test this script ??? I don't think it works it will create some more problems.

**Comment by mercolino** [comment]
Did you test it? I have been using it since I post it and it is working....

**Comment by Waseem-farooqui** [comment]
Yes I have tested it, I was following this guide and it suggest the same thing basically this script some how replicates this section   
**Setup kippo to start at boot**
sed -i 's/twistd -y kippo.tac -l log\/kippo.log --pidfile kippo.pid/su kippo -c "authbind --deep twistd -n -y kippo.tac -l log\/kippo.log --pidfile kippo.pid"/g'  /opt/kippo/start.sh

https://itandsecuritystuffs.wordpress.com/2015/02/03/honeypot-networks/

**Comment by mercolino** [comment]
I do not understand what you mean or what you want, that line of configuration is a recommendation, with the currently configuration for the supervisor the stop command doesn’t work, for me in Ubuntu 14.04 it works perfectly with the command that I suggest. I am the author of the guide that you are following so it is the same recommendation. If you have an error, maybe a little more information is needed from you.

The problem with the script is that start.sh starts a twistd process and tiwstd starts another process to run the .tac, so when you issue the command supervisorctl stop kippo doesn’t kill all the processes opened by start.sh, with the command that i suggest it only opens two process, that are recognized by supervisor with the command stopasgroup=true.  

So as I said on my previous post, I am using it and it works, and it is a recommendation, if you have problems with the script do not use it and leave the configuration as is.

**Comment by Waseem-farooqui** [comment]
Sorry the problem from my side I copied your script and pasted while deploying the script and update it at that time instead of (" double quotes) I copied “.
This was not allowing kippo to run I revert the script still supervisor was loading the previous configurations.
here is the link that about that issue https://github.com/threatstream/mhn/issues/146 
But now I updated that again on your recommendation because your guide was really great and this is genuine issue of stopping kippo but still it not stoping.
I just change `/etc/supervisor/conf.d/kippo.conf` and add the script recommended by you but created a new sensor by that script.
What do you suggest I should do?

**Comment by Waseem-farooqui** [comment]
Yes it starts working :+1:  Its must be integrated its a great recommendation.

**Comment by mercolino** [comment]
Glad it worked!!
