### ISSUE TITLE
Problems with Shockpot deploy script

### ISSUE THREAD

**Issue by mercolino** [threatstream/mhn#116]
Hi, there is a problem with the deployment script of shockpot, once installed the command "sudo supervisorctl start shockpot" does not work.

There is a problem on the shockpot.conf that is used to determine the public address in shockpot.py, to resolve this issue you should add the section in the deployment script, at the end previous the "#Config for supervisor" line and previoues the line "EOF" add the following:

[fetch_public_ip]
enabled = false
urls = ["http://api.ipify.org","http://bot.whatismyipaddress.com/"]

With that you resolve the errors, obiously you could add your preferred ip address api url on the list.

Regards

**Comment by jt6211** [comment]
Thanks @mercolino.  I ended using the same config section from the default shockpot config (https://github.com/threatstream/shockpot/blob/master/shockpot.conf#L16-L18), but it should fix the issue.  Thanks for bringing this to our attention.
