### ISSUE TITLE
Kippo does not send Key Init Exchange when attacked with Hydra

### ISSUE THREAD

**Issue by mercolino** [threatstream/mhn#118]
When Kippo is attacked with Hydra, that uses libssh, kippo does not send the Key Init Exchange, hydra tear down the connection with an error: 
****[ERROR] could not connect to ssh:IP_ADDRESS:22
By a strange reason, twisted does not send automatically the Key Init Exchange, as does for OpenSSH and others... I found a workaround because I think that Hydra is one of the most popular tools for password attacks.

The workaround is:
You should modify /opt/kippo/kippo/core/honeypot.py and add the following after the line 533:

#Workaround libssh not working with Twisted Hydra not working
        isLibssh = False
        if data.find('libssh', data.find('SSH-')) != -1:
                isLibssh = True

and also modify the line 536 (before inserting the code above) with:
if (twisted.version.major < 11 or isLibssh) and \

Obviously this works with the forked version for MHN, for the master version desaster/kippo you should modify kippo/core/ssh.py the line number 533 should be 149 and 536 should be 152

Regards

**Comment by jt6211** [comment]
Does this look correct?  https://github.com/threatstream/kippo/pull/5

**Comment by jt6211** [comment]
thanks @mercolino
