### ISSUE TITLE
Manually adding a sensor (and locating hpfeeds secret key)

### ISSUE THREAD

**Issue by andrew-morris** [threatstream/mhn#120]
How do I locate/generate the secret key associated with a sensor I add manually through the "Sensors" tab?

Thanks!

**Comment by jt6211** [comment]
This script (https://github.com/threatstream/hpfeeds/blob/master/broker/add_user.py) that is deployed with hpfeeds in /opt/hpfeeds/broker/ can be used to add an hpfeeds user.  When we deploy sensors we generate a UUID for the user name and a random secret.  It can be whatever you want.  

If you want to figure out the hpfeeds user/secret you can pull this data from mongo db:

```
mongo hpfeeds
db.auth_key.find()
db.auth_key.find({identifier: "sensor_name"})  // if you know the identifier/username of the sensor
```

**Comment by andrew-morris** [comment]
Awesome, thanks so much Jason!

**Comment by Waseem-farooqui** [comment]
I am facing an issue when adding sensor manually.
I have study https://github.com/threatstream/mhn/wiki/Incorporate-an-already-deployed-Honeypot-into-MHN  and tried to perform these step but failed at step 2 :(
```I am running `Shiva an open relay honeypot` it has support of hpfeeds.``` 
**Following are list of my problem**

1.  When I add the sensor it gives me UUID fine but in my sensors ui it show me **IP 127.0.0.1** *How can I changed this IP? I don't even tried to change it*.
2.  In the **Shiva** configurations I have a section of hpfeeds that ask me to fill the following
     *  host (I gave mhn-server IP)
     *  port (10000)
     *  ident (I gave UUID generated at the time of adding sensor)
     *  secret (It has default)
  no section for **CHANNELS** is it required?
3.  If I come to the guide at step 2 
      *  I have added data in **auth_key** like this  `db.auth_key.insert({IDENT:"e4bb7bea-6804-11e5-8f7f-0800272c0865",SECRET:"8koAbA4P0PMhnW9Q",PUBLISH_CHANNELS:"shiva.events",SUBSCRIBE_CHANNELS:"" });`
      *   I did  `cd /opt/hpfeeds/broker` but at `source env/bin/activate` I got this `bash: env/bin/activate: No such file or directory`

**Comment by jt6211** [comment]
Shiva is not supported by MHN.  There is no mnemosyne module for it, no deploy script for it, no geoloc module to place it on a map, and no hpfeeds-logger module to normalize for splunk/arcsight/ELK.  Since none of these are implemented it probably isn't worth the time to try and integrate an already deployed Shiva sensor with MHN since even if you got the hpfeeds data flow working the data would not go anywhere .  

Re number 3, do this:

```
cd /opt/hpfeeds/broker
source /opt/hpfeeds/env/bin/activate
```

**Comment by Waseem-farooqui** [comment]
Which means we can only connect those honeypots that are supported or need to add them to support ?? by https://github.com/threatstream/mhn/wiki/Howto:-Add-Support-for-New-Sensors-to-the-MHN.

I think i don't need to do step3 than.

**Comment by jt6211** [comment]
Yes that is correct.

**Comment by Waseem-farooqui** [comment]
Thanks :+1:

**Comment by polancossj** [comment]
Can I add Snare as mhn sensor , it is possible?
