### ISSUE TITLE
Sensors and Attacks are not shown on Honeymap

### ISSUE THREAD

**Issue by secNinja** [threatstream/mhn#121]
I have two dionaea sensors on an Amazon EC2 instances. The MHN Server is getting attack info from the sensors with source IP of the attacker and showing it in the "Attack Stats" on the web interface. However, neither the sensors nor the attacks are shown on the honeymap. Could anyone tell what could be the problem?

**Comment by secNinja** [comment]
Sorry, it seems like honeymap only shows live attack and after some time the attack goes away. Possibly this is the reason why I didn't see any attack on honeymap. But, still I would like to know what I need to do to see the sensors on the map?

**Comment by ChrisFernandez** [comment]
Hello, I will like to be able to see the src and dst attacks as well like in the main honeymap map.
also is there any way to show the attacks to other honeypots from the network i do not own on my map?

**Comment by jt6211** [comment]
The sensor's should show up on the map as yellow IF maxmind can geolocate
them and IF they are not in singapore (
https://github.com/threatstream/mhn/issues/54#issuecomment-53164222).
Honeymap is realtime so it only shows events that have occurred since it
was openned.

**Comment by jt6211** [comment]
Christian,

I am not sure I understand.  How would you see the attacks from other
honeypots that you do not own?

--Jason

**Comment by ChrisFernandez** [comment]
Hello. I was under the impression that we could share with the main project stats both ways not just from us to the project..etc

**Comment by ChrisFernandez** [comment]
so is there a way to get/share with my own data, data from other pots?

**Comment by d1str0** [comment]
https://github.com/threatstream/mhn/wiki/Getting-Access-to-the-MHN-Community-Data
