### ISSUE TITLE
CRITICAL:root:Database connection closed (Connection closed. not data). Exiting.

### ISSUE THREAD

**Issue by andyrat33** [threatstream/mhn#126]
I have this error in my hpfeeds.err log file. I don't get any events in the mhn but the map is working, 
I have looked at the troubleshooting guide, but everything seems ok. Is there a google group for users??

**Comment by jt6211** [comment]
Here is the google group: https://groups.google.com/forum/#!forum/modern-honey-network and modern-honey-network@googlegroups.com

I updated the README to make this more clear.

Re your error.  Is mongodb running?  Can you check mongo's logs to see if it is in a weird state?  Does this command work without error?

```
mongo mnemosyne
> db.session.find()
```

**Comment by andyrat33** [comment]
Mongodb seems to be running:
root@ubuntu:~# mongo mnemosyne
MongoDB shell version: 2.6.8
connecting to: mnemosyne
> db.session.find()
> db.session.find()

This does not return anything at all.

I hope I can fix it it looks like a brilliant idea!



On 26 Feb 2015, at 17:36, Jason Trost <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the google group: https://groups.google.com/forum/#!forum/modern-honey-network and modern-honey-network@googlegroups.com<mailto:modern-honey-network@googlegroups.com>

I updated the README to make this more clear.

Re your error. Is mongodb running? Can you check mongo's logs to see if it is in a weird state? Does this command work without error?

mongo mnemosyne

**Comment by jt6211** [comment]
Can you provide the output of the following commands:

```
sudo netstat -luntp
sudo supervisorctl status
sudo iptables -L
cat /opt/mnemosyne/mnemosyne.cfg
tail /var/log/mnemosyne.err
tail /var/log/mnemosyne.out
```

**Comment by andyrat33** [comment]
root@ubuntu:~# sudo netstat -luntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      1222/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1181/nginx
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1041/sshd
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1156/mongod
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1192/redis-server
tcp6       0      0 :::22                   :::*                    LISTEN      1041/sshd
tcp6       0      0 :::3000                 :::*                    LISTEN      1233/server
root@ubuntu:~# sudo supervisorctl status
geoloc                           RUNNING    pid 1223, uptime 11:40:16
honeymap                         RUNNING    pid 1233, uptime 11:40:16
hpfeeds-broker                   RUNNING    pid 1222, uptime 11:40:17
mhn-celery-beat                  RUNNING    pid 1215, uptime 11:40:19
mhn-celery-worker                RUNNING    pid 1225, uptime 11:40:16
mhn-collector                    RUNNING    pid 1226, uptime 11:40:16
mhn-uwsgi                        RUNNING    pid 1224, uptime 11:40:16
root@ubuntu:~# sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
root@ubuntu:~# cat /opt/mnemosyne/mnemosyne.cfg
[webapi]
host = 0.0.0.0
port = 8181

[mongodb]
database = mnemosyne

[hpfriends]
host = localhost
port = 10000
ident = mnemosyne
secret = 86945f9f3d8f4ada805844a947f5d519
channels = amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events

[file_log]
enabled = True
file = mnemosyne.log

[loggly_log]
enabled = False
token =

[normalizer]
ignore_rfc1918 = True
root@ubuntu:~# tail /var/log/mnemosyne.err
tail: cannot open `/var/log/mnemosyne.err' for reading: No such file or directory
root@ubuntu:~# tail /var/log/mnemosyne.out
tail: cannot open `/var/log/mnemosyne.out' for reading: No such file or directory
root@ubuntu:~# tail /var/log/mnemosyne.out
tail: cannot open `/var/log/mnemosyne.out' for reading: No such file or directory
root@ubuntu:~#

Kind regards,
Andy

CISSP, GCIA, GCIH, GPEN, GWAPT, CSTA, CSTP, CWSA
Blog.InfoSecMatters.net <http://blog.infosecmatters.net/>

**Comment by jt6211** [comment]
It looks like you might have skipped the mnemosyne install since it is not in the supervisorctl listing as running or in error.  Thats why those logs don't exist.  mnemosyne reads off of the hpfeeds broker and writes data to mongo (which MHN uses to populate the various pages)

**Comment by andyrat33** [comment]
It does appear to be installed:
root@ubuntu:~# cd /opt/mnemosyne/
root@ubuntu:/opt/mnemosyne# ls
COPYING.txt  data  doc  env  feedpuller  mnemosyne.cfg  mnemosyne.cfg.dist  normalizer  persistance  README.md  requirements.txt  runner.py  scripts  test  webapi
root@ubuntu:/opt/mnemosyne#

Kind regards,
Andy

**Comment by jt6211** [comment]
Can you run this:

```
cat >> /etc/supervisor/conf.d/mnemosyne.conf <<EOF 
[program:mnemosyne]
command=/opt/mnemosyne/env/bin/python runner.py --config mnemosyne.cfg
directory=/opt/mnemosyne
stdout_logfile=/var/log/mnemosyne.log
stderr_logfile=/var/log/mnemosyne.err
autostart=true
autorestart=true
startsecs=10
EOF

supervisorctl update
```

Then try nmap'ing your honeypot.  You should see attacks in the MHN app after that.

**Comment by andyrat33** [comment]
Getting closer, I think. That seems to have got the mnemosyne running:
root@ubuntu:/opt# supervisorctl status
geoloc                           RUNNING    pid 1223, uptime 12:47:03
honeymap                         RUNNING    pid 1233, uptime 12:47:03
hpfeeds-broker                   RUNNING    pid 1222, uptime 12:47:04
mhn-celery-beat                  RUNNING    pid 1215, uptime 12:47:06
mhn-celery-worker                RUNNING    pid 1225, uptime 12:47:03
mhn-collector                    RUNNING    pid 1226, uptime 12:47:03
mhn-uwsgi                        RUNNING    pid 1224, uptime 12:47:03
mnemosyne                        RUNNING    pid 3261, uptime 0:00:36

I’m seeing the activity caused by nmap in the 'map' but still nothing in the web:


21:49:46
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:49:51
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:49:54
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:49:56
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:50:01
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:50:06
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:50:08
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:50:13
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)

21:50:14
<
dionaea.connections
>
New attack from
Shenyang, China
(41.79, 123.43) to
USA
(38.00, -97.00)

21:50:16
<
dionaea.connections
>
New attack from
United Kingdom
(51.50, -0.13)
Kind regards,
Andy

**Comment by andyrat33** [comment]
Is this useful?

> db.getCollectionNames()
[
	"counts",
	"daily_stats",
	"dork",
	"file",
	"hpfeed",
	"metadata",
	"session",
	"system.indexes",
	"url"
]
>


Kind regards,
Andy

**Comment by andyrat33** [comment]
2015-02-26 22:04:37,874 (root) Starting mnemosyne. (Git: 2c5e5b1832df660612e0e4661e8606dbc562b15f)
2015-02-26 22:04:40,603 (persistance.mnemodb) Connecting to mongodb, using "mnemosyne" as database.
Traceback (most recent call last):
  File "runner.py", line 116, in <module>
    db = mnemodb.MnemoDB(c['mongo_db'])
  File "/opt/mnemosyne/persistance/mnemodb.py", line 36, in __init__
    conn = MongoClient(auto_start_request=False)
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused

Kind regards,
Andy

**Comment by jt6211** [comment]
this indicates that mongo is having issues.  I would suggest looking in its logs (/var/log/mongodb/mongod.log).  Any chance you have a disk full or that mongo could have been shutdown uncleanly (poweroff, hard reboot, etc)?

Unrelated, what type of honeypots have u deployed?

**Comment by andyrat33** [comment]
I guess it’s possible that it may have been hard rebooted but I don’t recall anything of that sort. Disk space is OK.

root@ubuntu:/var/log# grep error /var/log/mongodb/mongod.log
2015-02-26T21:45:03.574+0000 [conn27] build index on: mnemosyne.hpfeed properties: { v: 1, key: { normalized: 1, last_error: 1 }, name: "normalized_1_last_error_1", ns: "mnemosyne.hpfeed", background: true }
2015-02-26T21:45:03.575+0000 [conn27] command mnemosyne.$cmd command: createIndexes { createIndexes: "hpfeed", indexes: [ { unique: false, background: true, name: "normalized_1_last_error_1", key: { normalized: 1, last_error: 1 } } ] } keyUpdates:0 numYields:0 locks(micros) r:12 w:1766181 reslen:113 1766ms

root@ubuntu:/var/log# supervisorctl status
geoloc                           RUNNING    pid 2494, uptime 0:24:56
honeymap                         RUNNING    pid 2520, uptime 0:24:54
hpfeeds-broker                   RUNNING    pid 2480, uptime 0:24:57
mhn-celery-beat                  RUNNING    pid 2479, uptime 0:24:57
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)
mhn-collector                    RUNNING    pid 2518, uptime 0:24:55
mhn-uwsgi                        RUNNING    pid 2499, uptime 0:24:55
mnemosyne                        RUNNING    pid 2487, uptime 0:24:56
root@ubuntu:/var/log#

Nothing stands out particularly in the log. Maybe I should try reinstall?
Kind regards,
Andy

**Comment by jt6211** [comment]
What OS for MHN server?
Are your hopeypots deployed on a public IP or privately?

I am kind of stumped.

**Comment by andyrat33** [comment]
The OS is Ubuntu 12.04. I'll rebuild it from scratch and see if it that fixes it. My honeypot is on public ip on a digital Ocean $5 droplet and is running Dionaea and Snort and seems ok.

Thanks for your help. Hopefully a rebuild will solve the issue.


Kind regards,
Andy

CISSP, GCIA, GCIH, GPEN, GWAPT, CSTA, CSTP
Blog.InfoSecMatters.net<http://blog.infosecmatters.net/>

Sent from an iDevice

On 27 Feb 2015, at 00:49, Jason Trost <notifications@github.com<mailto:notifications@github.com>> wrote:

What OS for MHN server?
Are your hopeypots deployed on a public IP or privately?

I am kind of stumped.

-

**Comment by andyrat33** [comment]
Freak issue. Cured by reinstall.
