### ISSUE TITLE
XSS within reset-password functionality

### ISSUE THREAD

**Issue by gfoss** [threatstream/mhn#130]
There is a low-severity reflected XSS vulnerability within the 'Change Password' feature of MHN. This vuln could not be used to attack other users. However, I haven't looked at the code yet (just happened across this during RMCCDC the other day) but I would guess there are more XSS bugs throughout the app due to the ease of execution related to this one. Some screenshots are below.

![image](https://cloud.githubusercontent.com/assets/727732/6431324/618dff86-bfe9-11e4-95e5-e580c34efe42.png)

![image](https://cloud.githubusercontent.com/assets/727732/6431325/6b01415e-bfe9-11e4-913b-df84ffbb382d.png)

Thanks,
Greg

**Comment by jt6211** [comment]
@gfoss thanks Greg. We will get this fixed.

**Comment by gfoss** [comment]
Excellent, thank you for the quick turnaround Jason! Also, do you have a more formal location to submit vulnerabilities to? This one was very low-risk so I didn't see much issue with posting it here, but for others I would not want to post them anywhere public.

Thanks again,
Greg

**Comment by jt6211** [comment]
@gfoss Thanks again for finding and reporting this.  We take security very seriously and want to address any potential issues as soon as possible.  Please send any sensitive vulns to me jason [.] trost [AT] threatstream [.] com AND/OR greg [AT] threatstream [.] com.  

Thanks,

--Jason

**Comment by gfoss** [comment]
Will do, thanks!

Greg
