### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/log/uwsgi/mhn.log

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/mhn#140]
I am stuck for a very long time I googled it but noting.
while installing **mhnserver** or when running `supervisor` it throws this error.
What's the reason is it some problem in my installations.
I was having this error too
     error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224

**Comment by jt6211** [comment]
What OS type and version?  Do you have a full log of the installation so I could review?

**Comment by Waseem-farooqui** [comment]
It was problem with my supervisor logs path.
Thanks Jason.
