### ISSUE TITLE
0 Attacks information.

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/mhn#141]
I have created 2 sensors 1 for `Dionaea` Honeypot and other is `kippo`.
I can ssh the sensor it and have scanned for dionaea but there are `0 attacks` at both `sensors` and `attacks` section.
I have also changed the **mnemosyne** configuration file for 
**ignore_rfc1918 =  False**
then restart it again but still no attacks detail.
How can I troubleshoot it ?

**Comment by jt6211** [comment]
I recommend starting here.  Most of the honeypots can be troubleshot in very similar ways from the network perspective.  Once it is determined that the network is not the issue, you can move to the specific host based logs.

https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide

**Comment by Waseem-farooqui** [comment]
I go through the whole guide but still having this issue.

**Comment by jt6211** [comment]
Can you collect output from these commands and send it to me:
1.
https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide#troubleshooting-the-honeypot-side
2.
https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide#dionaea-honeypot-troubleshooting-same-symptoms
3.
https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide#troubleshooting-from-the-mhn-server

**Comment by Waseem-farooqui** [comment]
I have tested all the aspects every thing is fine.
I have assigned it a private ip 172.20.16.36 and scan it by 172.20.16.35 
Still no attack.

**Comment by Waseem-farooqui** [comment]
Thankyou very much for your time.
I reconfigure the setup.
It was basically problem with my network interface my services were running on eth0 and my system has eth1.
I restart my system by not 
![geoloc](https://cloud.githubusercontent.com/assets/10846095/6683553/6b699854-cca9-11e4-848c-161ac9314a74.png)
I can see attacks in attacks sections but in sensors there is still 0 attack infomation that confuses most of the time.
![display](https://cloud.githubusercontent.com/assets/10846095/6683566/997cacf4-cca9-11e4-95fc-b79b8ec32bc8.png)
These are some logs or results 
**Dionaea conf for hpfeeds**
![dionaea conf](https://cloud.githubusercontent.com/assets/10846095/6683580/e37b611a-cca9-11e4-87b3-c2a2b07c7d2e.png)
**Dionaea netstat**
![dionaea lun ntp](https://cloud.githubusercontent.com/assets/10846095/6683621/935b6ecc-ccaa-11e4-8084-a5c771082c66.png)
**Hpfeeds**
![hpfeeds](https://cloud.githubusercontent.com/assets/10846095/6683636/aa9c13ac-ccaa-11e4-9a96-6f43481453e9.png)

**iptables**
![iptables](https://cloud.githubusercontent.com/assets/10846095/6683643/b7d1f65e-ccaa-11e4-9f1c-0bba86519de5.png)
**Mongodb**
![mongodb](https://cloud.githubusercontent.com/assets/10846095/6683645/c0e91c72-ccaa-11e4-9a16-140902618ae2.png)
**Packet Capture**
![packetcaptures](https://cloud.githubusercontent.com/assets/10846095/6683649/cbf43ab6-ccaa-11e4-9a6c-6277df10ace5.png)

**Comment by MobikSargam** [comment]
I am also facing the same issue.
