### ISSUE TITLE
Incorrect time on Attacks page

### ISSUE THREAD

**Issue by EMOziko** [threatstream/mhn#148]
Hello.

I just deployed MHN and it's working very good! Thank you for this great product.

But i have one problem, time on attacks page is not correct.

date -R shows this:
Thu, 02 Apr 2015 17:42:04 +0400

and page, this: 
2015-04-02 13:41:57

It's probably time zone problem. 

Can you help me?

**Comment by jt6211** [comment]
Time is displayed in UTC​.

**Comment by EMOziko** [comment]
Is there any way to display it in GMT?

Thanks.

**Comment by jt6211** [comment]
There is no time difference between Coordinated Universal Time and
Greenwich Mean Time​.

**Comment by EMOziko** [comment]
As you can see i have GMT+4 on my system. So there should be UTC+4? 
I just need to display correct time on attack page.

**Comment by Kiwawa** [comment]
Fix (from a COMLETE novice on Python):

In "/opt/mhn/server/mhn/__init__.py" add:

```
from mhn.common.templatetags import format_local_date
mhn.jinja_env.filters['fldate'] = format_local_date
```


In "/opt/mhn/server/mhn/common/templatetags.py" add :

```
from dateutil import tz

def format_local_date(dt):
    from_zone = tz.tzutc()
    to_zone = tz.tzlocal()
    utc = dt
    utc = utc.replace(tzinfo=from_zone)
    dt2 = utc.astimezone(to_zone)
    return dt2.strftime('%Y-%m-%d %H:%M:%S')
```


Then modify templates in "/opt/mhn/server/mhn/templates/ui", (rules.html & attacks.html) to use "fldate" instead of "fdate".
