### ISSUE TITLE
bad character in password encounter by kippo is causing an error in /image/top_passwords.svg

### ISSUE THREAD

**Issue by saveyour** [threatstream/mhn#150]
the error message when i try to access /image/top_passwords.svg is:
"error on line 4 at column 5942: Char 0x0 out of allowed range"

is their a way to find the password and remove it or clear the logs to fix this issue? thanks

**Comment by aabed** [comment]
Can you give me a full error message please?

**Comment by saveyour** [comment]
where can i get a full error message? the logs look empty in /opt/mhn/server/mhn.log

**Comment by aabed** [comment]
I believe that is not the only error message that appears on the web page
Also you can run MHN in the debug mode 
Modify 

mhn/server/mhn.py
 mhn.run(debug=False, host='0.0.0.0', port=8000)
TO
 mhn.run(debug=True, host='0.0.0.0', port=8000)

Then restart MHN and you will get a full error message

Regards,

**Comment by cloughrm** [comment]
Closing, no response
