### ISSUE TITLE
Any hint on how to autoupdate iptable of a honeypot

### ISSUE THREAD

**Issue by alphaaurigae** [threatstream/mhn#151]
I would like to use mhn snort honeypot on my local VM (KVM) system where i deploy VPS for customers.
Is there any proven method to integrate mhn with iptabled on a honeypot node?
If not, any idea how to do so? Maybe some modded autosnort script?

Regards,

**Comment by jt6211** [comment]
Hey alphaaurigae,

Can you explain a little more.  I am not sure I understand what you mean.

Do you mean what iptables rules can be deployed on an MHN Server machine to
lock it down?  Or do you mean what iptables rules should be deployed on
various honeypots deployed by MHN to lock them down?  Or do you mean, you
want IPs that cause snort rules to fire to automatically add iptables drop
rules to some firewall?  ​

**Comment by alphaaurigae** [comment]
Dear Jason,
the scenario i thought about was to deploy a honeypot on the dedicated servers and integrate iptable  rules collected with the MHN node vserver across those dedicated servers.

Best Regards,

**Comment by JayMaree** [comment]
You could synchronize the iptables files between the servers/nodes right? Example: rSync

**Comment by jt6211** [comment]
@alphaaurigae I'm sorry but, MHN does not currently support this use case.

**Comment by alphaaurigae** [comment]
THX @ JayMaree
@jt6211 with the potential of MHN this would be awesome, it could provide an awesome IDS solution with this function (if im not missing a point here)

**Comment by GringaoGit** [comment]
This would become an IPS.

**Comment by gregtampa** [comment]
Well said GringaoGit :)
