### ISSUE TITLE
Will mhn server periodically update snort rule ?

### ISSUE THREAD

**Issue by sidra-asa** [threatstream/mhn#152]
The snort sensor will update snort daily, getting the rules from mhn server.
But it seems no cron jobs related with updating snort rules from https://rules.emergingthreats.net/open/ in mhn server. Will it be scheduled to improve?
Also, if I add rule source in rules management page, the server will automatically get rules or not ?

**Comment by jt6211** [comment]
MHN uses celery and celerybeat to accomplish this.  By default it is
configured to pull down the new rules every 12 hours and reload the
database.

https://github.com/threatstream/mhn/blob/cf5c3c2de147356a882e7102e12f0031461ed3f9/server/config.py.template#L42-L48

**Comment by sidra-asa** [comment]
Thanks for your reply. I'll take a look.
