### ISSUE TITLE
Internal Server Error - NoneType object is not iterable

### ISSUE THREAD

**Issue by Equ1n0x** [threatstream/mhn#154]
Hi all,

Trying to setup a MHN server at a friends house on an Ubuntu 14.04 Virtual Machine. When login in to the dashboard we get an Internal server error.

Installation worked fine although we had to sudo chown www-data /var/log/mhn/mhn.log && sudo supervisorctl start mhn-celery-worker to get that running.

1. Nginx is running
3. supervisor is running
3. sudo supervisorctl status:

geoloc                           RUNNING    pid 23390, uptime 11:09:31
honeymap                         RUNNING    pid 23391, uptime 11:09:31
hpfeeds-broker                   RUNNING    pid 11664, uptime 11:33:51
mhn-celery-beat                  RUNNING    pid 25184, uptime 10:29:10
mhn-celery-worker                RUNNING    pid 25434, uptime 0:12:38
mhn-collector                    RUNNING    pid 25187, uptime 10:29:10
mhn-uwsgi                        RUNNING    pid 25194, uptime 10:29:10
mnemosyne                        RUNNING    pid 20885, uptime 11:18:51

MHN.log contains:

2015-04-11 21:10:02,795 -  /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on /ui/dashboard/ [GET]
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "./mhn/ui/views.py", line 73, in dashboard
    get_flag_ip=get_flag_ip)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/server/mhn/templates/ui/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/mhn/server/mhn/templates/base.html", line 74, in top-level template code
    {% block content %}{% endblock %}
  File "/opt/mhn/server/mhn/templates/ui/dashboard.html", line 29, in block "content"
    {% for ip in top_attackers %}
TypeError: 'NoneType' object is not iterable

Any idea how we can fix this?
Same problem occurs on Ubuntu 12.04.

Kind Regards,

EQ

**Comment by jt6211** [comment]
It appears pymongo's latest release changed a bunch of things and broke compatibility with the older versions.  This should be fixed by https://github.com/threatstream/mhn/pull/155.  

If you have an already installed MHN, you should be able to fix by doing this:

```
sudo su -
source /opt/mhn/env/bin/activate
pip uninstall pymongo # enter "y" when prompted...
pip install pymongo==2.7.2 
supervisorctl restart all
```

**Comment by fheuer** [comment]
Having this problem as described above.
System:
virtual Ubuntu 12.04

Installation was not smooth and besides already mentioned "sudo chown www-data /var/log/mhn/mhn.log && sudo supervisorctl start mhn-celery-worker" I had to handle [mongodb fault - issue #209] (https://github.com/threatstream/mhn/issues/209) to get that running.

```
root@mhn-server:~# service nginx status
 * nginx is running

root@mhn-server:~# supervisorctl status
geoloc                           RUNNING    pid 30715, uptime 0:14:07
honeymap                         RUNNING    pid 30741, uptime 0:14:05
hpfeeds-broker                   RUNNING    pid 30696, uptime 0:14:08
mhn-celery-beat                  RUNNING    pid 30695, uptime 0:14:08
mhn-celery-worker                RUNNING    pid 30769, uptime 0:12:02
mhn-collector                    RUNNING    pid 30733, uptime 0:14:05
mhn-uwsgi                        RUNNING    pid 30719, uptime 0:14:06
mnemosyne                        RUNNING    pid 30708, uptime 0:14:07
```

MHN logfile:
```
[fetching rules done...]

/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on /ui/login/ [GET]
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/decorators.py", line 203, in wrapper
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
```

No solution yet, any advice?

**Comment by jt6211** [comment]
Can you do the following and provide output?

```
cd /opt/mhn
source env/bin/activate
pip freeze
git log | head
```

**Comment by fheuer** [comment]
pip freeze
```
(env)root@mhn-server:/opt/mhn# pip freeze
alembic==0.8.2
amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.20
blinker==1.4
celery==3.1.16
Flask==0.10.1
Flask-Login==0.3.0
Flask-Mail==0.9.1
Flask-Migrate==1.2.0
Flask-Principal==0.4.0
Flask-Script==2.0.5
Flask-Security==1.7.4
Flask-SQLAlchemy==2.0
Flask-Testing==0.4.2
Flask-WTF==0.10.3
GeoIP==1.3.2
hpfeeds-logger==0.0.5a0
hpfeeds-threatstream==1.0
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.26
Mako==1.0.2
MarkupSafe==0.23
passlib==1.6.5
py-bcrypt==0.4
pygal==1.7.0
pymongo==2.7.2
python-dateutil==2.2
python-editor==0.4
pytz==2015.4
redis==2.10.3
requests==2.4.3
six==1.9.0
SQLAlchemy==1.0.8
uWSGI==2.0.8
Werkzeug==0.10.4
wheel==0.24.0
WTForms==2.0.2
xmltodict==0.9.0
```

git log | head
```
(env)root@mhn-server:/opt/mhn# git log |  head
commit 02e4b75d966b426921d49602613bfa122d58c47e
Merge: 2f5256a 3c66cc7
Author: Jason Trost <jason.trost@gmail.com>
Date:   Sun Aug 2 05:47:20 2015 -0400

    Merge pull request #198 from threatstream/elk-install-fixes

    restored the original install_elk.sh as install_elk_raw_hpfeeds.sh

commit 3c66cc768558d0d4da03bdc14e1b35e4310ec1b8
```

**Comment by jt6211** [comment]
I believe this is the issue: https://github.com/mattupstate/flask-security/issues/416

and this is the fix:

```
sudo su -
cd /opt/mhn
source env/bin/activate
pip uninstall Flask-Login==0.3.0  # enter "y" when prompted
pip install Flask-Login==0.2.11
supervisorctl restart mhn-uwsgi
```

Also, I added this: https://github.com/threatstream/mhn/commit/37a2dec8e34a9ec06287bce6cebd7fcc5580fef7 to prevent this in the future.

**Comment by fheuer** [comment]
Thanks, Jason! fixed #154
:+1:

**Comment by mhorenykie** [comment]
I have tried all the corrections here and the specified links, yet i am still getting the Internal Server Error

MHN Log 

2015-10-18 14:03:08,443 -  /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on /ui/dashboard/ [GET]
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "./mhn/ui/views.py", line 62, in dashboard
    top_attackers = clio.session.top_attackers(top=5, hours_ago=24)
  File "./mhn/common/clio.py", line 316, in top_attackers
    return self._tops('source_ip', top, hours_ago)
  File "./mhn/common/clio.py", line 304, in _tops
    res = self.collection.aggregate(query)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 1336, in aggregate
    "aggregate", self.__name, **command_kwargs)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/database.py", line 351, in _command
    msg, allowable_errors)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('aggregate', u'session'), ('pipeline', [{'$match': {'timestamp': {'$gte': datetime.datetime(2015, 10, 17, 14, 3, 8, 442762)}, 'source_ip': {'$ne': None}}}, {'$group': {'count': {'$sum': 1}, '_id': {'source_ip': '$source_ip'}}}, {'$sort': SON([('count', -1)])}])]) failed: no such cmd: aggregate
2015-10-18 14:03:09,335 -  /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on /ui/dashboard/ [GET]
Traceback (most recent call last):
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()

pip freeze
alembic==0.8.3
amqp==1.4.7
anyjson==0.3.3
billiard==3.3.0.20
blinker==1.4
celery==3.1.16
Flask==0.10.1
Flask-Login==0.2.11
Flask-Mail==0.9.1
Flask-Migrate==1.2.0
Flask-Principal==0.4.0
Flask-Script==2.0.5
Flask-Security==1.7.4
Flask-SQLAlchemy==2.0
Flask-Testing==0.4.2
Flask-WTF==0.10.3
GeoIP==1.3.2
hpfeeds-logger==0.0.5a0
hpfeeds-threatstream==1.0
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.28
Mako==1.0.2
MarkupSafe==0.23
passlib==1.6.5
py-bcrypt==0.4
pygal==1.7.0
pymongo==2.7.2
python-dateutil==2.2
python-editor==0.4
pytz==2015.6
redis==2.10.3
requests==2.4.3
six==1.10.0
SQLAlchemy==1.0.8
uWSGI==2.0.8
Werkzeug==0.10.4
wheel==0.24.0
WTForms==2.0.2
xmltodict==0.9.0

(env)ubuntumhn@ubuntumhn-VirtualBox:/opt/mhn$ git log | head
commit f38f310caa3ce6ce86c48c39268fa1fb2be512e1
Merge: 36f0b8f 53a7e90
Author: Jason Trost <jason.trost@gmail.com>
Date:   Fri Oct 2 12:17:39 2015 -0400

    Merge pull request #213 from maf23/kippo_persistent
    
    Make IP-forwarding persistent

commit 53a7e90c4d7acb76e549d1ef3f1e5beacb9d7fe4

Any help on how to fix this.... I an running on Ubuntu 12.04 on virtualbox

**Comment by jt6211** [comment]
This is a different error.  I believe you are using an older version of
mongo that doesn't support the agrregate command.  Can you run this and
provide the output? It should be 2.6.7 or greater.

$ mongod --version
Here is how to update mongo:

sudo apt-get update
sudo apt-get install mongodb-org



On Sun, Oct 18, 2015 at 9:38 AM, mhorenykie <notifications@github.com>
wrote:

> I have tried all the corrections here and the specified links, yet i am
> still getting the Internal Server Error
>
> MHN Log
>
> 2015-10-18 14:03:08,443 -
> /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on
> /ui/dashboard/ [GET]
> Traceback (most recent call last):
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1817, in wsgi_app
> response = self.full_dispatch_request()
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1477, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1381, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1475, in full_dispatch_request
> rv = self.dispatch_request()
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1461, in dispatch_request
> return self.view_functionsrule.endpoint <http://**req.view_args>
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_login.py", line
> 758, in decorated_view
> return func(*args, **kwargs)
> File "./mhn/ui/views.py", line 62, in dashboard
> top_attackers = clio.session.top_attackers(top=5, hours_ago=24)
> File "./mhn/common/clio.py", line 316, in top_attackers
> return self._tops('source_ip', top, hours_ago)
> File "./mhn/common/clio.py", line 304, in _tops
> res = self.collection.aggregate(query)
> File
> "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/collection.py",
> line 1336, in aggregate
> "aggregate", self.__name, **command_kwargs)
> File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/database.py",
> line 351, in _command
> msg, allowable_errors)
> File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/helpers.py",
> line 178, in _check_command_response
> raise OperationFailure(msg % errmsg, code, response)
> OperationFailure: command SON([('aggregate', u'session'), ('pipeline',
> [{'$match': {'timestamp': {'$gte': datetime.datetime(2015, 10, 17, 14, 3,
> 8, 442762)}, 'source_ip': {'$ne': None}}}, {'$group': {'count': {'$sum':
> 1}, '_id': {'source_ip': '$source_ip'}}}, {'$sort': SON([('count',
> -1)])}])]) failed: no such cmd: aggregate
> 2015-10-18 14:03:09,335 -
> /opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py - Exception on
> /ui/dashboard/ [GET]
> Traceback (most recent call last):
> File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line
> 1817, in wsgi_app
> response = self.full_dispatch_request()
>
> pip freeze
> alembic==0.8.3
> amqp==1.4.7
> anyjson==0.3.3
> billiard==3.3.0.20
> blinker==1.4
> celery==3.1.16
> Flask==0.10.1
> Flask-Login==0.2.11
> Flask-Mail==0.9.1
> Flask-Migrate==1.2.0
> Flask-Principal==0.4.0
> Flask-Script==2.0.5
> Flask-Security==1.7.4
> Flask-SQLAlchemy==2.0
> Flask-Testing==0.4.2
> Flask-WTF==0.10.3
> GeoIP==1.3.2
> hpfeeds-logger==0.0.5a0
> hpfeeds-threatstream==1.0
> itsdangerous==0.24
> Jinja2==2.8
> kombu==3.0.28
> Mako==1.0.2
> MarkupSafe==0.23
> passlib==1.6.5
> py-bcrypt==0.4
> pygal==1.7.0
> pymongo==2.7.2
> python-dateutil==2.2
> python-editor==0.4
> pytz==2015.6
> redis==2.10.3
> requests==2.4.3
> six==1.10.0
> SQLAlchemy==1.0.8
> uWSGI==2.0.8
> Werkzeug==0.10.4
> wheel==0.24.0
> WTForms==2.0.2
> xmltodict==0.9.0
>
> (env)ubuntumhn@ubuntumhn-VirtualBox:/opt/mhn$ git log | head
> commit f38f310
> <https://github.com/threatstream/mhn/commit/f38f310caa3ce6ce86c48c39268fa1fb2be512e1>
> Merge: 36f0b8f
> <https://github.com/threatstream/mhn/commit/36f0b8f9835293e99396ddc4eda644cc49ade025>
> 53a7e90
> <https://github.com/threatstream/mhn/commit/53a7e90c4d7acb76e549d1ef3f1e5beacb9d7fe4>
> Author: Jason Trost jason.trost@gmail.com
> Date: Fri Oct 2 12:17:39 2015 -0400
>
> Merge pull request #213 from maf23/kippo_persistent
>
> Make IP-forwarding persistent
>
> commit 53a7e90
> <https://github.com/threatstream/mhn/commit/53a7e90c4d7acb76e549d1ef3f1e5beacb9d7fe4>
>
> Any help on how to fix this.... I an running on Ubuntu 12.04 on virtualbox
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/154#issuecomment-149017372>.
>



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost
