### ISSUE TITLE
How can I integrate my existing honeypot with MHN.

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/mhn#156]
Hi,
I want to integrate my existing honeypots with mhn is there some thing I can do ?

**Comment by gregtampa** [comment]
https://github.com/threatstream/mhn/wiki/Howto:-Add-Support-for-New-Sensors-to-the-MHN

I prefer to use the api though and just pass feeds through it.
https://github.com/threatstream/mhn/wiki/MHN-REST-APIs
I forgot I added that to my code...if you want to use api let me know I can publish my revision.

**Comment by jt6211** [comment]
I just wrote this up.  Feedback welcome:

https://github.com/threatstream/mhn/wiki/Incorporate-an-already-deployed-Honeypot-into-MHN

**Comment by Waseem-farooqui** [comment]
Thanks @gregtampa and @jt6211 for your guidance.
