### ISSUE TITLE
Sensors Change IP address, lead to no updated data in MHN server

### ISSUE THREAD

**Issue by xmlx** [threatstream/mhn#157]
I'm currently testing on MHN, and so far it running smoothly with data collected from multiple honeypot (sensor). I just noticed since currently my honeypot are running on DHCP, whenever the honeypot change to different IP, there will be no data flowing in the MHN server. 

Can you point to me how can i solve this? that i can update my MHN server on existing honeypot that been assign to new ip. Thanks.

**Comment by Waseem-farooqui** [comment]
If you have assign the static IP address to the mhn server (machine) and now you want to change the IP address of mhn server than change the MHN configurations at `/opt/mhn/server/config.py` in my case here change the *SERVER_BASE_URL* and *HONEYMAP_URL*, and restart the mhn-uwsgi by  `sudo supervisorctl restart mhn-uwsgi`.
here is the reference https://github.com/threatstream/MHN/wiki/MHN-Troubleshooting-Guide

**Comment by jt6211** [comment]
If your MHN Server gets its IP from DHCP, you could use a dynamic DNS service and use this name in your `/opt/mhn/server/config.py`, `SERVER_BASE_URL` variable and the sensors will follow it.

If your sensors are using DHCP, they should still be able to connect to your MHN server and data should still flow unless you had to open up firewall ports for each sensor IP.

**Comment by Gerd-k** [comment]
I have sensors running on different networks and I have hit the same problem, since the ips are dynamic I have no easy way to know what ips my sensors have. The data is still flowing but I do not know from where any more.
