### ISSUE TITLE
Support for hpfeeds over ssl

### ISSUE THREAD

**Issue by jgedeon120** [threatstream/mhn#158]
Has anyone configured hpfeeds to send and receive over SSL?  Having the data sent to the MHN Server over plain text is not an option.

**Comment by gregtampa** [comment]
I would like to see this also.

**Comment by nicholastripp** [comment]
I think this would be useful for my purposes as well.

**Comment by d1str0** [comment]
Will not be supported. If we support TLS it will be in addition to http reporting.
