### ISSUE TITLE
Problem in Installation of hpfeeds for Glastopf.

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/mhn#163]
I run the deploying script for Glastopf at Ubuntu 14.04.
It throw me this error.

```
  Could not find any downloads that satisfy the requirement hpfeeds (from glastopf)
    Some externally hosted files were ignored (use --allow-external hpfeeds to allow).
  Cleaning up...
  No distributions at all found for hpfeeds (from glastopf)
  Storing debug log for failure in /home/sensor02/.pip/pip.log
```

In the pip.log I got this 

```
Downloading/unpacking hpfeeds (from glastopf)
  Getting page https://pypi.python.org/simple/hpfeeds/
  Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/hpfeeds/ when looking for download links for hpfeeds (from glastopf)
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for hpfeeds (from glastopf):
  * https://pypi.python.org/simple/hpfeeds/
  Getting page https://pypi.python.org/simple/hpfeeds/
  **Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client Error: Not Found**
  Will skip URL https://pypi.python.org/simple/hpfeeds/ when looking for download links for hpfeeds (from glastopf)
  Could not find any downloads that satisfy the requirement hpfeeds (from glastopf)
  Some externally hosted files were ignored (use --allow-external hpfeeds to allow).
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for hpfeeds (from glastopf)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
```

Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client Error: Not Found
is the reason but why ?

**Comment by jt6211** [comment]
Can you try this again?  I just uploaded hpfeeds to pypi since it looks
like the previous one may have been taken down.

https://pypi.python.org/pypi/hpfeeds

On Wed, May 13, 2015 at 8:39 AM, Waseem ud din <notifications@github.com>
wrote:

> I run the deploying script for Glastopf at Ubuntu 14.04.
> It throw me this error.
>
>   Could not find any downloads that satisfy the requirement hpfeeds (from glastopf)
>     Some externally hosted files were ignored (use --allow-external hpfeeds to allow).
>   Cleaning up...
>   No distributions at all found for hpfeeds (from glastopf)
>   Storing debug log for failure in /home/sensor02/.pip/pip.log
>
> In the pip.log I got this
>
> Downloading/unpacking hpfeeds (from glastopf)
>   Getting page https://pypi.python.org/simple/hpfeeds/
>   Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client Error: Not Found
>   Will skip URL https://pypi.python.org/simple/hpfeeds/ when looking for download links for hpfeeds (from glastopf)
>   Getting page https://pypi.python.org/simple/
>   URLs to search for versions for hpfeeds (from glastopf):
>   * https://pypi.python.org/simple/hpfeeds/
>   Getting page https://pypi.python.org/simple/hpfeeds/
>   **Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client Error: Not Found**
>   Will skip URL https://pypi.python.org/simple/hpfeeds/ when looking for download links for hpfeeds (from glastopf)
>   Could not find any downloads that satisfy the requirement hpfeeds (from glastopf)
>   Some externally hosted files were ignored (use --allow-external hpfeeds to allow).
> Cleaning up...
>   Removing temporary dir /tmp/pip_build_root...
> No distributions at all found for hpfeeds (from glastopf)
> Exception information:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
>     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1177, in prepare_files
>     url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
>   File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
>     raise DistributionNotFound('No distributions at all found for %s' % req)
>
> Could not fetch URL https://pypi.python.org/simple/hpfeeds/: 404 Client
> Error: Not Found
> is the reason but why ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/163>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by cloughrm** [comment]
@Waseem-farooqui were you able to resolve this issue?
