### ISSUE TITLE
where is the amun capture malware save?

### ISSUE THREAD

**Issue by jjjan** [threatstream/mhn#165]
Hello,
where is the amun capture malware save?
what about dionaea honeypot?

**Comment by Waseem-farooqui** [comment]
Dionaea stores binaries at `/var/dionaea/binaries` and Amun Stores at `/opt/amun/malware`.

**Comment by jjjan** [comment]
thanks for replay but my honeypot doesn't save any binaries!
is there any way to check what's the problem?

**Comment by jt6211** [comment]
I recommend reaching out to the Amun maintainer (@zeroq).  He wrote the
deploy script for MHN and he will likely be able to solve this issue the
fastest.​

**Comment by Waseem-farooqui** [comment]
@jjjan According to Dionaea configuration binaries are stored with `hashname.tmp` extension while Amun stores malware with their `md5sum.bin`.
When an attacker downloads a binary than honeypot saves it otherwise for testing purpose attack yourself and test it.
