### ISSUE TITLE
Kippo Dashboard

### ISSUE THREAD

**Issue by devopsstack** [threatstream/mhn#167]
hello, in my case i have trouble with some views in the mhn kippo dashboard. the views kippo top password and kippo top user/passwords shows following error:  error on line 4 at column 6577: PCDATA invalid Char value 27

![mhn_err](https://cloud.githubusercontent.com/assets/9567028/8032996/1dbe55e0-0ddb-11e5-9d28-edecf8509dbc.jpg)

**Comment by jt6211** [comment]
I wonder if this is an escaping issue where a password contains HTML/XML markup that is causing this.

@aabed any ideas?

**Comment by aabed** [comment]
Yes, I believe so, it's an XML problem 
Maybe if you can give me that record that makes this problem I can make some tests and add a code to escape xml

**Comment by devopsstack** [comment]
hello aabed, what you need exactly? how do I do that?

**Comment by aabed** [comment]
Well, you can try this query 
open a mongo shell then

>use mnemosyne
>db.session.find({"auth_attempts.password":/.*DATA.*/})

and send me the results 

Regards,

**Comment by cloughrm** [comment]
Closing, no response after 7 months
