### ISSUE TITLE
nginx problem

### ISSUE THREAD

**Issue by jjjan** [threatstream/mhn#168]
hello i always get this error "504 Gateway Time-out nginx/1.1.19"
my server configuration is:
ubuntu 12.04
4 GB ram
200 GB hard disk
cpu 4 core 2.0

any solution please

**Comment by jt6211** [comment]
What page/pages does this occur on?  Have you tried restarting the MHN uwsgi service?

```
supervisorctl restart mhn-uwsgi
```

Are there any errors in `/var/log/mhn/mhn-uwsgi.*`?

**Comment by jjjan** [comment]
well thanks for replay. what is default dashboard url? after i login i just enter my server ip address

nginx error log

2015/06/09 00:02:03 [error] 26019#0: *387 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/ui/dashboard/"
2015/06/09 00:02:25 [error] 26019#0: *386 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x., server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/"
2015/06/09 00:02:31 [error] 26019#0: *393 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /ui/dashboard/ HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "x.x.x.x"
2015/06/09 00:02:32 [error] 26019#0: *395 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "x.x.x.x"
2
---------------------------------------------------------------------------------------------------------------------------------
mhn-uwsgi 
*** Starting uWSGI 2.0.8 (32bit) on [Sun Apr 26 13:12:21 2015] ***
compiled with version: 4.6.3 on 26 April 2015 13:01:39
os: Linux-3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:42:40 UTC 2014
nodename: static
machine: i686
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/mhn/server
detected binary path: /opt/mhn/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 32121
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
Python version: 2.7.3 (default, Dec 18 2014, 19:15:23)  [GCC 4.6.3]
Set PythonHome to /opt/mhn/env
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8a24b68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 63988 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x8a24b68 pid: 29976 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 29976, cores: 1)

[pid: 29976|app: 0|req: 290/290] 62.60.138.3 () {32 vars in 408 bytes} [Mon May  4 09:35:58 2015] GET /api/script/?text=true&script_id=7 => generated 3402 bytes in 58 msecs (HTTP/1.1 200) 4 headers in 291 bytes (1 switches on core 0)
[pid: 29976|app: 0|req: 291/291] 62.60.138.3 () {34 vars in 409 bytes} [Mon May  4 09:36:00 2015] POST /api/sensor/ => generated 334 bytes in 412 msecs (HTTP/1.1 200) 3 headers in 229 bytes (1 switches on core 0)
Mon May  4 09:56:50 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /ui/dashboard/ (ip x.x.x.x) !!!
Mon May  4 09:56:50 2015 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 287] during GET /ui/dashboard/ (x.x.x.x)
IOError: write error
[pid: 29976|app: 0|req: 292/292] x.x.x.x () {42 vars in 1058 bytes} [Mon May  4 09:56:24 2015] GET /ui/dashboard/ => generated 0 bytes in 26443 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)
Mon May  4 09:56:51 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip x.x.x.x) !!!
Mon May  4 09:56:51 2015 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 287] during GET / (x.x.x.x)
IOError: write error
[pid: 29976|app: 0|req: 293/293] x.x.x.x () {40 vars in 968 bytes} [Mon May  4 09:56:50 2015] GET / => generated 0 bytes in 656 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)
Mon May  4 09:56:51 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip x.x.x.x) !!!
Mon May  4 09:56:51 2015 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 287] during GET / (x.x.x.x)
IOError: write error
[pid: 29976|app: 0|req: 294/294] x.x.x.x () {40 vars in 968 bytes} [Mon May  4 09:56:51 2015] GET / => generated 0 bytes in 142 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)

**Comment by jjjan** [comment]
i also mentioned for all page i have this problem

**Comment by jt6211** [comment]
@jjjan How much data do you have in MHN?  I am wondering if mongo is timing out on your visits to the dashboard.  You might need more RAM or to age off some older data.  Can you try this?

```
sudo supervisorctl restart mhn-uwsgi
sudo /etc/init.d/nginx restart
```

Then try linking directly to a page besides the dashboard, like /ui/add-user/ or /ui/manage-deploy/.  Do these timeout?  What about /ui/manage-deploy/?  

Lastly, what is the output of this command?

```
cd /opt/mhn
git log | head
```

**Comment by aabed** [comment]
@jt6211 I think you shall use this command in supervisor instead of the current one

command=/opt/mhn/env/bin/uwsgi --http-socket 0.0.0.0:8000 -w mhn:mhn -H /opt/mhn/env --chmod-socket=666
and you can try to increase the timeout
  proxy_read_timeout 300;
in the location block in nginx

**Comment by jjjan** [comment]
git log | head output. whats is the usage of "git log | head" ?
commit 21fa9703c52d460ca1950499043f7eabd1802c4d
Merge: 234163b 5ca19b7
Author: <xxxxxx@gmail.com>
Date:   Sat Apr 18 19:57:52 2015 -0400

    Merge remote-tracking branch 'public/master'

commit 234163b1ab3be449c5d0a7d7ae2229dd9559012f
Author: <xxxxxx@gmail.com>
Date:   Sat Apr 18 19:57:19 2015 -0400

**Comment by jjjan** [comment]
thanks aabed where should i put proxy_read_timeout 300 ?
in nginx.conf?
thnaks

**Comment by aabed** [comment]
/etc/nginx/sites-enabled/default.conf

**Comment by cloughrm** [comment]
Closing as this issue appears to be resolved. Thanks for the help @aabed!

**Comment by yangjerry110** [comment]
i can't see you cuurent problem for this all page ,hhhhhhh

**Comment by sikhan555** [comment]
face same issue.. 504 gateway timeout
