### ISSUE TITLE
MHN Docker Container

### ISSUE THREAD

**Issue by Epicism** [threatstream/mhn#169]
Hello all,

This isn't an issue as much as sharing post. I have hacked my way into configuring MHN on a docker container for simplicity. Because docker doesn't use standard services, I had to hack supervisord to start services at appropriate times. 

To start a docker container, use the command 
```
docker run -p 10000:10000 -p 80:80 -p 3000:3000 -p 8089:8089 --name mhn -t -i ubuntu:14.04.2 /bin/bash
```
*Note: 8089 is if you are using the Splunk forwarder, and you can chose between 80 and 443. You can also make the host OS' port separate from the docker container's port by using [hostport]:[dockerport], which is convenient for honeypots.

Next, create and run the following script:
```
#!/bin/bash

set -x

apt-get update 
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
cd /opt/ 
git clone https://github.com/threatstream/mhn.git 
cd mhn

cat > /etc/supervisor/conf.d/mhntodocker.conf <<EOF
[program:mongod]
command=/usr/bin/mongod
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
autorestart=true
autostart=true

[program:nginx]
command=/usr/sbin/nginx
stdout_events_enabled=true
stderr_events_enabled=true
autostart=true
autorestart=true

EOF

mkdir -p /data/db /var/log/mhn /var/log/supervisor

supervisord &

#Starts the mongod service after installation
echo supervisorctl start mongod >> /opt/mhn/scripts/install_mongo.sh

./install.sh

supervisorctl restart all
```

I haven't started deploying honeypots yet, which is my next task. Unfortunately, due to the interactive nature of MHN's installation, supervisord is manually running in the background instead of as a started service. To restart the container later use 
```
docker start <containerID> 
docker exec <containerID> supervisord &
```

Don't forget to reference the host's IP address or Hostname as the MHN server's IP unless you are using Docker's internal networking. You could also pass the script during the docker container creation, but since you have to execute it inside of the container it doesn't really matter.

If there is enough interest in this my hope is that we can create a process to generate a docker image/honeypot images on the fly, perhaps by passing a simple config file to the image on run which configures the server as required.

Cheers.
Epic

**Comment by jt6211** [comment]
Thats awesome.  Thanks for Sharing!

**Comment by cloughrm** [comment]
Thank you @Epicism! I have added this to the wiki here: https://github.com/threatstream/mhn/wiki/Running-MHN-in-Docker

**Comment by Epicism** [comment]
My pleasure :)

**Comment by Epicism** [comment]
Hello all,

I had to rebuild my MHN server and I thought that I would complete the instructions towards how to install the remaining containers. The container setup is based on my environment configuration so please feel free to modify it to your requirements.

#Create the Kippo container:
`docker run -p 2222:22 --name kippo -h kippo.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
apt-get install --yes --force-yes -y openssh-server
supervisord &
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=7" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```

Then create a Supervisord script to manage MHN:
```
cat > /etc/supervisor/conf.d/mhntodocker.conf <<EOF
[program:kippo]
command=/opt/kippo/start.sh
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
autorestart=true
autostart=true
EOF
supervisord &
```


#Create the Wordpot container:
`docker run -p 8080:80 --name kippo -h kippo.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
supervisord &

wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=17" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```

#Create the cowrie container:
`docker run -p 23:22 --name cowrie -h cowrie.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
apt-get install --yes --force-yes -y openssh-server
supervisord &
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=14" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```


#Create the Dionaea container:
`docker run -p 3306:3306 -p 42:42 -p 8081:80 -p 21:21 -p 1433:1433 -p 2443:443 -p 445:445 -p 5060:5060 -p 5061:5061 -p 135:135 -p 5060:5060/udp -p 69:69/udp --name dionaea -h dionaea.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
supervisord &
apt-get install software-properties-common -y
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=4" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```

#Create the Shockpot container:
`docker run -p 8082:80 --name shockpot -h shockpot.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
supervisord &

wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=15" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```


#Create the conpot container:
`docker run -p 82:80 -p 502:502 -p 102:102 -p 623:623/udp -p 47808:47808/udp -p 161:161/udp --name conpot -h conpot.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`

#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
supervisord &

wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=9" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```

#Create the elastichoney container:
`docker run -p 9200:9200 --name elastichoney -h elastichoney.projectmayhem.local -t -i ubuntu:14.04.5 /bin/bash`
#In the docker container, run the following commands:
```
apt-get update
apt-get upgrade -y 
apt-get install git wget gcc supervisor -y 
supervisord &

wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=6" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
wget "http://xxx.xxx.xxx.xxx/api/script/?text=true&script_id=16" -O deploy.sh && sudo bash deploy.sh http://xxx.xxx.xxx.xxx <KEY>
```

Step 4. ???

Step 5. Profit!
