### ISSUE TITLE
problem installing GeoIp

### ISSUE THREAD

**Issue by aabed** [threatstream/mhn#177]
this error is produced on installing geoip package

Building wheels for collected packages: GeoIp
  Running setup.py bdist_wheel for GeoIp
  Complete output from command /opt/hpfeeds/env/bin/python -c "import setuptools;**file**='/tmp/pip-build-ETWxI9/GeoIp/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmpebCwYIpip-wheel-:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

---

  Failed building wheel for GeoIp

I believe it's cause because of installing evnet 
pip install -e git+https://github.com/rep/evnet.git#egg=evnet-dev

kindly check that issue 
https://github.com/rep/evnet/issues/7

Thanks

**Comment by jt6211** [comment]
What OS and version?

-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by aabed** [comment]
ubuntu 14.04

**Comment by jt6211** [comment]
I tried this morning and I got the same error, but I am not sure this
matters.  See at the end of the GeoIP install, it ultimately succeeds.  Are
you experiencing an issues related to GeoIP?  Or you just noticed this
error message and were concerned?


+ /opt/hpfeeds/env/bin/pip install GeoIP
Collecting GeoIP
/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90:
InsecurePlatformWarning: A true SSLContext object is not available. This
prevents urllib3 from configuring SSL appropriately and may cause certain
SSL connections to fail. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
.
  InsecurePlatformWarning
  Downloading GeoIP-1.3.2.tar.gz
Building wheels for collected packages: GeoIP
  Running setup.py bdist_wheel for GeoIP
  Complete output from command /opt/hpfeeds/env/bin/python -c "import
setuptools;__file__='/tmp/pip-build-NqXGop/GeoIP/setup.py';exec(compile(open(__file__).read().replace('\r\n',
'\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpxkJZW8pip-wheel-:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'bugtrack_url'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for GeoIP
Failed to build GeoIP
Installing collected packages: GeoIP
  Running setup.py install for GeoIP
*Successfully installed GeoIP-1.3.2*

**Comment by Keldo** [comment]
Although it may eventually successfully install, it still does not show the Honeypot (Yellow dot) on the map. Ive tried with both Ubuntu 12.04.5 and 14.04

**Comment by aabed** [comment]
As for me I did not proceed with the installation ,but I though it was the problem that is happening with @Keldo and I was right :)

**Comment by Tigzy** [comment]
Hello, same problem here, plus flags don't appear in the panel.

**Comment by sqqqs** [comment]
Tigzy, you need to install libgeoip-dev.
apt-get libgeoip-dev

**Comment by jdt3000** [comment]
It because of evnet use library distribute-0.6.15 that incompatible with easy_install. 

So I edit install script to use local git for evnet and use distribute-0.6.49. It work fine.

**Comment by pmontrasio** [comment]
I'm trying to follow the idea of @jdt3000 but I'm running into another problem, with a ```NameError: name 'sys_platform' is not defined``` I'll work on it. From what I googled it seems that distribute is no more the way to go and it's included in setuptools now.

This issue has been reported to evnet time ago: https://github.com/rep/evnet/issues/7

The maintainer commented "To be honest I haven't used evnet in over a year. I should probably just discontinue the repository." Maybe it's time to find a replacement for evnet.

**Comment by jdt3000** [comment]
You can try other version between distribute 0.6.35 or greater

**Comment by d1str0** [comment]
Please try/test with the latest codebase. Ubuntu 14.04 should be fully supported ATM.
