### ISSUE TITLE
Problem repository install_mongo.sh raspberry

### ISSUE THREAD

**Issue by LeonCloud** [threatstream/mhn#178]
Hi, if we install MHN on raspberry pi by ./install when the script execute install_mongo.sh there is some problems: "W: Impossibile recuperare http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/Release  Impossibile trovare la voce "10gen/binary-armhf/Packages" nel file Release (voce in sources.list errata o file danneggiato)"
I see the code and i notice that:
1) " http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen " doesn't exist. The directory is http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/ ..
2) If modify the line with "http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/ dist 10gen" on sources.list.d/mongodb.list there still error: " Err http://downloads-distro.mongodb.org dist/10gen armhf Packages" 
In fact in the repository there isn't any armhf folder.

How can i fix it ??

Thanks a lot.

**Comment by jt6211** [comment]
Unfortunately, we don't currently support installing MHN a on a raspberry
pi.  I believe this is technically possible, but the install scripts will
need to be modified to do this.  This might be helpful:
http://www.widriksson.com/install-mongodb-raspberrypi/

--Jason


On Fri, Jun 26, 2015 at 5:49 AM, LeonCloud <notifications@github.com> wrote:

> Hi, if we install MHN on raspberry pi by ./install when the script execute
> install_mongo.sh there is some problems: "W: Impossibile recuperare
> http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/Release
> Impossibile trovare la voce "10gen/binary-armhf/Packages" nel file Release
> (voce in sources.list errata o file danneggiato)"
> I see the code and i notice that:
> 1) " http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen "
> doesn't exist. The directory is
> http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/dist/ ..
> 2) If modify the line with "
> http://downloads-distro.mongodb.org/repo/ubuntu-upstart/dists/ dist
> 10gen" on sources.list.d/mongodb.list there still error: " Err
> http://downloads-distro.mongodb.org dist/10gen armhf Packages"
> In fact in the repository there isn't any armhf folder.
>
> How can i fix it ??
>
> Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/178>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by LeonCloud** [comment]
Okk.. Thanks a lot for the doc. I'll see it !
