### ISSUE TITLE
conpot deploy from mhn

### ISSUE THREAD

**Issue by joe3523** [threatstream/mhn#182]
Hello everyone,

I am attempting to deploy conpot from a MHN server to an Ubuntu 12.x virtual server, but I get the below error when attempting to "supervisorctl status".  Its true "conpot" is missing in that directory. I have refreshed my server  and ran through the deploy a couple times, but I still run into this issue. 

:~# supervisorctl status
conpot                           FATAL      can't find command '/opt/conpot/env/bin/conpot'

Any help would be much appreciated.

**Comment by jt6211** [comment]
Can you provide the install log?  And what specific version of Ubuntu 12?

On Thu, Jul 9, 2015 at 12:28 AM, joe3523 <notifications@github.com> wrote:

> Hello everyone,
>
> I am attempting to deploy conpot from a MHN server to an Ubuntu 12.x
> virtual server, but I get the below error when attempting to "supervisorctl
> status". Its true "conpot" is missing in that directory. I have refreshed
> my server and ran through the deploy a couple times, but I still run into
> this issue.
>
> :~# supervisorctl status
> conpot FATAL can't find command '/opt/conpot/env/bin/conpot'
>
> Any help would be much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/182>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by joe3523** [comment]
Thanks for the response Jason.

I tried this on Ubuntu 14 first but had the same issues and saw an old thread that stated Ubuntu 14 wasn't officially supported. So I moved to Ubuntu 12.

Ubuntu 12.04.5 LTS (GNU/Linux 2.6.32-042stab108.5 x86_64)

2015-07-09 10:10:04,111 CRIT Supervisor running as root (no user in config file)
2015-07-09 10:10:04,217 INFO RPC interface 'supervisor' initialized
2015-07-09 10:10:04,217 WARN cElementTree not installed, using slower XML parser for XML-RPC
2015-07-09 10:10:04,217 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-07-09 10:10:04,234 INFO daemonizing the supervisord process
2015-07-09 10:10:04,237 INFO supervisord started with pid 5929
2015-07-09 10:21:47,906 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:21:48,912 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:21:50,914 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:21:53,917 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:21:53,917 INFO gave up: conpot entered FATAL state, too many start retries too quickly
2015-07-09 10:22:03,517 WARN received SIGTERM indicating exit request
2015-07-09 10:22:18,274 CRIT Supervisor running as root (no user in config file)
2015-07-09 10:22:18,274 WARN Included extra file "/etc/supervisor/conf.d/conpot.conf" during parsing
2015-07-09 10:22:18,551 INFO RPC interface 'supervisor' initialized
2015-07-09 10:22:18,552 WARN cElementTree not installed, using slower XML parser for XML-RPC
2015-07-09 10:22:18,552 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-07-09 10:22:18,552 INFO daemonizing the supervisord process
2015-07-09 10:22:18,553 INFO supervisord started with pid 371
2015-07-09 10:22:19,554 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:22:20,556 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:22:22,558 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:22:25,561 INFO spawnerr: can't find command '/opt/conpot/env/bin/conpot'
2015-07-09 10:22:25,561 INFO gave up: conpot entered FATAL state, too many start retries too quickly
2015-07-09 10:24:17,552 CRIT Supervisor running as root (no user in config file)
2015-07-09 10:24:17,552 WARN Included extra file "/etc/supervisor/conf.d/conpot.conf" during parsing

**Comment by jt6211** [comment]
This looks like the supervisord log.  I need the output from the console
when you ran the deploy command that you copied/pasted from your MHN
webapp.​

**Comment by joe3523** [comment]
You are correct.

I had to break some of the deploy script up because of an error.  Erorr is at the end and stops the deploy. I had read online that this might be due to lxml already being installed in previous packages and to ignore it.

Thanks for the help!

2015-07-09 11:02:59 (224 MB/s) - `registration.sh' saved [1206/1206]

Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
Created sensor:  978a7628-264b-11e5-9c02-adda104669fd
Hit http://archive.ubuntu.com precise Release.gpg
Hit http://archive.ubuntu.com precise-updates Release.gpg
Hit http://security.ubuntu.com precise-security Release.gpg
Hit http://archive.ubuntu.com precise Release
Hit http://security.ubuntu.com precise-security Release
Hit http://archive.ubuntu.com precise-updates Release
Hit http://security.ubuntu.com precise-security/main amd64 Packages
Hit http://archive.ubuntu.com precise/main amd64 Packages
Hit http://archive.ubuntu.com precise/restricted amd64 Packages
Hit http://archive.ubuntu.com precise/universe amd64 Packages
Hit http://archive.ubuntu.com precise/main i386 Packages
Hit http://archive.ubuntu.com precise/restricted i386 Packages
Hit http://archive.ubuntu.com precise/universe i386 Packages
Hit http://archive.ubuntu.com precise/main TranslationIndex
Hit http://archive.ubuntu.com precise/restricted TranslationIndex
Hit http://archive.ubuntu.com precise/universe TranslationIndex
Hit http://security.ubuntu.com precise-security/restricted amd64 Packages
Hit http://security.ubuntu.com precise-security/universe amd64 Packages
Hit http://security.ubuntu.com precise-security/multiverse amd64 Packages
Hit http://security.ubuntu.com precise-security/main i386 Packages
Hit http://security.ubuntu.com precise-security/restricted i386 Packages
Hit http://security.ubuntu.com precise-security/universe i386 Packages
Hit http://security.ubuntu.com precise-security/multiverse i386 Packages
Hit http://security.ubuntu.com precise-security/main TranslationIndex
Hit http://security.ubuntu.com precise-security/multiverse TranslationIndex
Hit http://security.ubuntu.com precise-security/restricted TranslationIndex
Hit http://archive.ubuntu.com precise-updates/main amd64 Packages
Hit http://archive.ubuntu.com precise-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com precise-updates/universe amd64 Packages
Hit http://archive.ubuntu.com precise-updates/main i386 Packages
Hit http://archive.ubuntu.com precise-updates/restricted i386 Packages
Hit http://archive.ubuntu.com precise-updates/universe i386 Packages
Hit http://archive.ubuntu.com precise-updates/main TranslationIndex
Hit http://archive.ubuntu.com precise-updates/restricted TranslationIndex
Hit http://archive.ubuntu.com precise-updates/universe TranslationIndex
Hit http://archive.ubuntu.com precise/main Translation-en
Hit http://archive.ubuntu.com precise/restricted Translation-en
Hit http://archive.ubuntu.com precise/universe Translation-en
Hit http://archive.canonical.com precise Release.gpg
Hit http://archive.ubuntu.com precise-updates/main Translation-en
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Hit http://security.ubuntu.com precise-security/universe TranslationIndex
Hit http://security.ubuntu.com precise-security/main Translation-en
Hit http://security.ubuntu.com precise-security/multiverse Translation-en
Hit http://security.ubuntu.com precise-security/restricted Translation-en
Hit http://security.ubuntu.com precise-security/universe Translation-en
Hit http://archive.canonical.com precise Release
Hit http://archive.canonical.com precise/partner amd64 Packages
Hit http://archive.canonical.com precise/partner i386 Packages
Ign http://archive.canonical.com precise/partner TranslationIndex
Ign http://archive.canonical.com precise/partner Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libsmi2ldbl is already the newest version.
python-pip is already the newest version.
git is already the newest version.
libmysqlclient-dev is already the newest version.
libxml2-dev is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
Downloading/unpacking distribute
  Downloading distribute-0.7.3.zip (145Kb): 145Kb downloaded
  Running setup.py egg_info for package distribute

Downloading/unpacking setuptools>=0.7 (from distribute)
  Downloading setuptools-18.0.1.tar.gz (630Kb): 630Kb downloaded
  Running setup.py egg_info for package setuptools

Installing collected packages: distribute, setuptools
  Found existing installation: distribute 0.7.3
    Uninstalling distribute:
      Successfully uninstalled distribute
  Running setup.py install for distribute

  Found existing installation: setuptools 18.0.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for setuptools

    Installing easy_install script to /usr/local/bin
    Installing easy_install-2.7 script to /usr/local/bin
Successfully installed distribute setuptools
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /usr/local/lib/python2.7/dist-packages
Cleaning up...
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
/opt/conpot/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: setuptools in ./env/lib/python2.7/site-packages
Obtaining hpfeeds from git+https://github.com/threatstream/hpfeeds.git#egg=hpfeeds-dev
  Updating ./env/src/hpfeeds clone
Installing collected packages: hpfeeds
  Running setup.py develop for hpfeeds
Successfully installed hpfeeds
Obtaining conpot from git+https://github.com/glastopf/conpot.git#egg=conpot-dev
  Updating ./env/src/conpot clone
Requirement already satisfied (use --upgrade to upgrade): gevent>=1.0 in ./env/lib/python2.7/site-packages (from conpot)
Requirement already satisfied (use --upgrade to upgrade): pysnmp>=4.2.4 in ./env/lib/python2.7/site-packages (from conpot)
Collecting lxml (from conpot)
/opt/conpot/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached lxml-3.4.4.tar.gz
Collecting bottle (from conpot)
Collecting jinja2 (from conpot)
Collecting beautifulsoup4 (from conpot)
  Using cached beautifulsoup4-4.4.0-py2-none-any.whl
Collecting requests (from conpot)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Collecting sphinx (from conpot)
  Using cached Sphinx-1.3.1-py2.py3-none-any.whl
Collecting libtaxii>=1.1.0 (from conpot)
Collecting MySQL-python (from conpot)
Collecting xlrd (from conpot)
Collecting crc16 (from conpot)
Collecting enum (from conpot)
Collecting hpfeeds (from conpot)
Requirement already satisfied (use --upgrade to upgrade): modbus-tk in ./env/src/modbus-tk (from conpot)
Collecting stix-validator (from conpot)
Collecting stix (from conpot)
Collecting cybox (from conpot)
Collecting bacpypes (from conpot)
  Using cached BACpypes-0.12.0-py2-none-any.whl
Collecting pyghmi (from conpot)
  Using cached pyghmi-0.8.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in ./env/lib/python2.7/site-packages (from gevent>=1.0->conpot)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.2 in ./env/lib/python2.7/site-packages (from pysnmp>=4.2.4->conpot)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.4.1 in ./env/lib/python2.7/site-packages (from pysnmp>=4.2.4->conpot)
Collecting markupsafe (from jinja2->conpot)
Collecting sphinx-rtd-theme<0.2,>=0.1 (from sphinx->conpot)
  Using cached sphinx_rtd_theme-0.1.8-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx->conpot)
Collecting six>=1.4 (from sphinx->conpot)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx->conpot)
  Using cached Pygments-2.0.2-py2-none-any.whl
Collecting docutils>=0.11 (from sphinx->conpot)
Collecting babel>=1.3 (from sphinx->conpot)
Collecting alabaster<0.8,>=0.7 (from sphinx->conpot)
  Using cached alabaster-0.7.6-py2-none-any.whl
Collecting python-dateutil>=1.4.1 (from libtaxii>=1.1.0->conpot)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./env/lib/python2.7/site-packages (from enum->conpot)
Collecting ordereddict (from stix-validator->conpot)
Collecting pytz>=0a (from babel>=1.3->sphinx->conpot)
  Using cached pytz-2015.4-py2.py3-none-any.whl
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command /opt/conpot/env/bin/python -c "import setuptools;__file__='/tmp/pip-build-QgDxfR/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpsJYiA1pip-wheel-:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  Building lxml version 3.4.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.26
  Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
  creating build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-QgDxfR/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
  error: command 'gcc' failed with exit status 4

  ----------------------------------------
  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, bottle, markupsafe, jinja2, beautifulsoup4, requests, sphinx-rtd-theme, snowballstemmer, six, Pygments, docutils, pytz, babel, alabaster, sphinx, python-dateutil, libtaxii, MySQL-python, xlrd, crc16, enum, hpfeeds, ordereddict, stix-validator, cybox, stix, bacpypes, pyghmi, conpot
  Running setup.py install for lxml
    Complete output from command /opt/conpot/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-QgDxfR/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v6Bayp-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conpot/env/include/site/python2.7/lxml:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-QgDxfR/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
    error: command 'gcc' failed with exit status 4

    ----------------------------------------
Command "/opt/conpot/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-QgDxfR/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v6Bayp-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conpot/env/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-QgDxfR/lxml

**Comment by joe3523** [comment]
I did an install on Debian and had zero errors but still no conpot.

supervisorctl status
conpot                           BACKOFF    can't find command '/opt/conpot/env/bin/conpot'

**Comment by d1str0** [comment]
Please try on 14.04 or 16.04 with the latest codebase. I haven't seen this issue personally.

**Comment by Wheaties466** [comment]
tried on the latest codebase and i am seeing this issue.
