### ISSUE TITLE
Conpot - ImportError: No module named mixbox

### ISSUE THREAD

**Issue by zoneoutaussie** [threatstream/mhn#184]
Hello,

I attempted to install conpot on a Ubuntu-14.04.1-LTS-64bit and Ubuntu 12.04.5 LTS-64bit servers using MHN Server's script but received the following error when attempting to run.

Traceback (most recent call last):
  File "/opt/conpot/env/bin/conpot", line 6, in <module>
    exec(compile(open(**file**).read(), **file**, 'exec'))
  File "/opt/conpot/env/src/conpot/bin/conpot", line 39, in <module>
    from conpot.core.loggers.log_worker import LogWorker
  File "/opt/conpot/env/src/conpot/conpot/core/loggers/log_worker.py", line 33,$
    from conpot.core.loggers.taxii_log import TaxiiLogger
  File "/opt/conpot/env/src/conpot/conpot/core/loggers/taxii_log.py", line 25, $
    from conpot.core.loggers.stix_transform import StixTransformer
  File "/opt/conpot/env/src/conpot/conpot/core/loggers/stix_transform.py", line$
    from mixbox import idgen
ImportError: No module named mixbox

**Comment by johnnykv** [comment]
This is a Conpot related issue and should be reported on the Conpot issue tracker. 

It seems like you are running cutting edge Conpot, be aware that the only thing that we guarantee from the cutting edge versions is that it will crash in mysterious ways! :-)

**Comment by jt6211** [comment]
Is there a branch or package of conpot we should use instead?

On Tuesday, July 14, 2015, Johnny Vestergaard <notifications@github.com>
wrote:

> This is a Conpot related issue and should be reported on the Conpot issue
> tracker.
>
> It seems like you are running cutting edge Conpot, be aware that the only
> thing that we guarantee from the cutting edge versions is that it will
> crash in mysterious ways! :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/184#issuecomment-121423268>.
>


-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by zoneoutaussie** [comment]
Hi,

All I did was build up a clean, base vm and then executed the conpot script from MHN Server. Nothing else.

**Comment by katkad** [comment]
@jt6211 Hi, we don't have recent stable release right now. I guess we will discuss it.
quick fix for this situation is
git checkout 12bcff1061d496f5fe4e47073edc108a372bffe6

after you clone conpot. it is last working commit that I know of. I didn' test commits after this one.

**Comment by katkad** [comment]
well, previous comment should go rather ti this issue https://github.com/threatstream/mhn/issues/185 as mixbox is fixed in conpot master

**Comment by RCARODZ** [comment]
Hi,

Im installing conpot and having a problem running it with the MHN server. This is what happens:

Traceback (most recent call last):
  File "/opt/conpot/env/bin/conpot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/conpot/env/src/conpot/bin/conpot", line 389, in <module>
    main()
  File "/opt/conpot/env/src/conpot/bin/conpot", line 303, in main
    log_worker = LogWorker(config, dom_base, session_manager, public_ip)
  File "/opt/conpot/env/src/conpot/conpot/core/loggers/log_worker.py", line 66, in __init__
    if config.getboolean('json', 'enabled'):
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'json'

**Comment by Antelox** [comment]
Are you using the last conpot deploy script? Seems that no [json] entry are present inside conpot config file...

**Comment by RCARODZ** [comment]
Im not sure if im using it, I installed the conpot with the script provided by the MHN server. No, the [json] is not in the conpot.cfg file, what can I do?

**Comment by Antelox** [comment]
Go here: https://github.com/threatstream/mhn/blob/master/scripts/deploy_conpot.sh
and copy&past from row 36 to 89 the last right copont config and make a try restarting conpot honeypot:

sudo supervisorctl restart conpot

BTW for sure, you are not using updated script! Update you local MHN repo:

https://github.com/threatstream/mhn/wiki/Updating-MHN

**Comment by Antelox** [comment]
This issue can be closed. (mixbox package is present inside requirements.txt file -> https://github.com/mushorg/conpot/blob/b28e1be2b1229590d10d038232a8df71f8be0b3f/requirements.txt#L21

**Comment by RCARODZ** [comment]
THANK YOU, IT WORKED :)

**Comment by RCARODZ** [comment]
Hi again, 

Now im getting a new error,

Traceback (most recent call last):
  File "/opt/conpot/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/conpot/env/local/lib/python2.7/site-packages/gevent/_socket2.py", line 228, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused
WARNING:pyhpfeeds:FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].

The conpot is working but its not registering any attacks to the MHN.

**Comment by Antelox** [comment]
Because hpfeeds entry in your config file is configured to send attacks informations to hpfriends.honeycloud.net (which is down at moment), instead you must set it to send these informations to your MHN server. But did you deploy conpot through MHN web interface???

**Comment by RCARODZ** [comment]
The conpot is in a different Ubuntu computer, it was installed using the script in the MHN server. Im doing it first in another MHN Server (used for testing) and its giving me the same problem. Can i replace that with a direct connection to the server.

**Comment by RCARODZ** [comment]
Update, 
I eliminated the error, but it is still not communicating with the MHN Server. I think its in the config file, in the [hpfriends] what does the secret means? Is it something from the MHN Server?

**Comment by d1str0** [comment]
Please try with the latest code base. I have not experienced any issues with conpot recently.
