### ISSUE TITLE
delete attacks

### ISSUE THREAD

**Issue by gregtampa** [threatstream/mhn#189]
would be nice to be able to delete or clear the attack data feeds...
https://groups.google.com/forum/#!msg/modern-honey-network/i1jmAwdYlNA/u8z50V7nqUsJ doesn't work ...

**Comment by Waseem-farooqui** [comment]
If you want to clear or delete all attacks data than I suggest to drop the **session** collection.
First stop the `mnemosyne` service.
than `db.session.drop()`.
Start the `mnemosyne` it will automatically create new session collection.
