### ISSUE TITLE
geoloc keeps crashing then reloading.

### ISSUE THREAD

**Issue by zoneoutaussie** [threatstream/mhn#190]
Hello,

I have noticed on the MHN Server that the geoloc process sees to crash every < 10 minutes or so then seems to reboot and be happy for another few minutes then crashes.

My honeypots are reporting and the honeymap is updated. However
when I create a new Ubunut 14.04 vm and install conpot - conpt installs but on the first ping to the server geoloc on the MHN Server crashes and cannot load again - going to fatal. Then when I remove the conpot honeypot from the sensor list and restart the geoloc process its back to normal.

Traceback (most recent call last):
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 100, in main
    hpc.run(on_message, on_error)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 188, in run
    message_callback(str(ident), str(chan), content)
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 85, in on_message
    traceback.print_exc(file=sys.stdout)
NameError: free variable 'traceback' referenced before assignment in enclosing scope
Parsing config file: /opt/hpfeeds/geoloc.json
connected to @hp2
Traceback (most recent call last):
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 100, in main
    hpc.run(on_message, on_error)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 188, in run
    message_callback(str(ident), str(chan), content)
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 85, in on_message
    traceback.print_exc(file=sys.stdout)
NameError: free variable 'traceback' referenced before assignment in enclosing scope
Parsing config file: /opt/hpfeeds/geoloc.json
connected to @hp2

**Comment by zaniskiwi** [comment]
I also get this issue as well. Installing conpot crashes the geoloc process.

**Comment by jt6211** [comment]
We had another user report this same issue.  I applied their fix (
https://github.com/threatstream/hpfeeds/commit/4d894ef606bb5b951ae0fd867ac513175b565a6a).
Can you do this and see if it crashes again?

cd /opt/hpfeeds
sudo git pull
sudo supervisorctl restart geloc

On Fri, Jul 24, 2015 at 1:45 PM, zaniskiwi <notifications@github.com> wrote:

> I also get this issue as well. Installing conpot crashes the geoloc
> process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/190#issuecomment-124716894>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by jt6211** [comment]
sudo supervisorctl restart geoloc

On Fri, Jul 24, 2015 at 3:31 PM, Jason Trost <jason.trost@threatstream.com>
wrote:

> We had another user report this same issue.  I applied their fix (
> https://github.com/threatstream/hpfeeds/commit/4d894ef606bb5b951ae0fd867ac513175b565a6a).
> Can you do this and see if it crashes again?
>
> cd /opt/hpfeeds
> sudo git pull
> sudo supervisorctl restart geloc
>
> On Fri, Jul 24, 2015 at 1:45 PM, zaniskiwi <notifications@github.com>
> wrote:
>
>> I also get this issue as well. Installing conpot crashes the geoloc
>> process.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/threatstream/mhn/issues/190#issuecomment-124716894>.
>>
>
>
>
> --
> Jason Trost | Director of ThreatStream Labs | www.threatstream.com
> 2317 Broadway, 3rd Floor| Redwood City, CA 94063
> Phone:  386.235.0078 | Twitter:  @jason_trost
>
>


-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by zaniskiwi** [comment]
Thanks - I did that and got this in the geoloc err log. for some reason I had to stash before I could successfully run the command. I updated mhn a few days ago.

Now the geoloc refuses to load - goes to FATAL

Parsing config file: /opt/hpfeeds/geoloc.json
connected to @hp2
 -> errormessage from server: authfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.
 -> errormessage from server: identfail.

**Comment by zaniskiwi** [comment]
Hmm now hpfeeds-broker  process keeps starting for a few seconds then crashes then restarts.

**Comment by zaniskiwi** [comment]
I did a complete reinstall of MHN Server on a clean VM - now all working but I get this error in splunk. IP addresses replaced with xxx

invalid message {"remote": ["xxx.xxx.xxx.xxx", 50640], "data_type": "http", "timestamp": "2015-07-25T20:56:02.938605", "public_ip": "xxx.xxx.xxx.xxx", "data": {"request": "('/index.html', ['Host: xxx.xxx.xxx.xxx\\r\\n', 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0\\r\\n', 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\\r\\n', 'Accept-Language: en-US,en;q=0.5\\r\\n', 'Accept-Encoding: gzip, deflate\\r\\n', 'Cookie: remember_token=WyIxIiwiODI2ODg4MDJkMjk3OGQwODFlMzI0OTNjM2M5OWJkNWEiXQ.CIMeWg.g9EfIAoRDDWbkIiyAQnTHvcxK-E; session=.eJw9zr0KwjAUQOFXkTt36d9S6CK1QeFefKSSUZClaU1vTKDSKmtJ3VxwczvpxZmi6Sbsesu4wOh1AM5wgm2F1hAyQ06iKtZW-ipDJhIqzlxfxrbTIREqstHveGyqqHJYAWjd1zf1m9PVPvSF72VGOsavFCj6n07Zv8bkArvGJkFG9D5JuY7DZBrgxGVULP_Mc9nJ5-OxDC8gEl7TZP.CJQ2VA.Dc4bbuGmK_KsnsOtzsD99jyWcrE\\r\\n', 'Via: 1.1 BC5-ACLD\\r\\n', 'Cache-Control: max-stale=0\\r\\n', 'Connection: Keep-Alive\\r\\n'], None)", "response": "200"}, "id": "4150e704-3dd2-40c4-ad46-b5e26afc9eac"} Traceback (most recent call last): File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 82, in on_message m = p(identifier, payload, gi) File "/opt/hpfeeds/examples/geoloc/processors.py", line 90, in conpot_events return create_message('conpot.events-'+dec.data_type, identifier, gi, src_ip=dec.remote, dst_ip=dec.public_ip) File "/opt/hpfeeds/examples/geoloc/processors.py", line 131, in create_message a_family = get_addr_family(src_ip) File "/opt/hpfeeds/examples/geoloc/processors.py", line 25, in get_addr_family ainfo = socket.getaddrinfo(addr, 1, socket.AF_UNSPEC, socket.SOCK_STREAM) TypeError: getaddrinfo() argument 1 must be string o

**Comment by jt6211** [comment]
It looks like you found a bug.  This should fix it: https://github.com/threatstream/hpfeeds/pull/16
