### ISSUE TITLE
Dionaea and Glastopf Honeypot are not installed on  Ubuntu 14.10 missing utopic

### ISSUE THREAD

**Issue by Nuemera** [threatstream/mhn#192]
Dionaea and Glastopf Honeypot are not installed Ubuntu 14.10 (GNU/Linux 3.16.0-23-generic x86_64)

Looks like package utopic package is missing. Below is the error message:

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

Thanks in advance.

**Comment by aabed** [comment]
Well, Unfortunately honeynet repo doesn't support  14.10

**Comment by Nuemera** [comment]
Does it Support Ubuntu 12.0

**Comment by gregtampa** [comment]
I got it installed, but I had to add the repo honeynet

**Comment by cloughrm** [comment]
Closing as it appears the issue has been resolved
