### ISSUE TITLE
How to remove Dionaea which has been installed through MHN Script

### ISSUE THREAD

**Issue by MustaqueA** [threatstream/mhn#199]
I am unable to see binaries and need to install Dionaea from the scratch. 

At the time of installation it gaves the message like there is some error in your script line 3 and need the path to fix and 

--- /etc/dionaea/dionaea.conf
+++ /etc/dionaea/dionaea.conf.new

and the command prompt to fix the path. Now not sure what have to be done at this phase. Any help is appreciated.

**Comment by jt6211** [comment]
When you are prompted like this, you should copy the file path of the top file and paste it into the prompt.  Some of the new Ubuntu's ship with a new version of `patch` that is causing this issue.  I haven't had a chance to fix it yet.

To remove dionaea, do this:

```
if [[ `lsb_release -cs` == "trusty" ]] ; then apt-get remove -y dionaea-phibo; else apt-get remove -y dionaea ; fi
rm -rf /var/dionaea/wwwroot /var/dionaea/binaries /var/dionaea/log /etc/dionaea/dionaea.conf /etc/supervisor/conf.d/dionaea.conf
supervisorctl update
```

**Comment by MustaqueA** [comment]
Not Sure What do you mean by top file. First one is top file.

 

--- /etc/dionaea/dionaea.conf     This one is top file?

+++ /etc/dionaea/dionaea.conf.new

 

One more help may be stupid question however, where to put this “if [[ `lsb_release -cs` == "trusty" ]]”

 

I am planning to do fresh installation. Thanks in advance.

**Comment by jt6211** [comment]
/etc/dionaea/dionaea.conf    <-- this would be the top file.  You will get
prompted again for a 2nd file as well.  You will want to copy and paste the
file path that does not end with .new each time.

You will copy that command I sent and paste it into the terminal (i.e. just
like you did with the long deploy command when you deployed the honeypot).

On Mon, Aug 3, 2015 at 11:52 AM, MustaqueA <notifications@github.com> wrote:

> Not Sure What do you mean by top file. First one is top file.
>
>
>
> --- /etc/dionaea/dionaea.conf This one is top file?
>
> +++ /etc/dionaea/dionaea.conf.new
>
>
>
> One more help may be stupid question however, where to put this “if [[
> `lsb_release -cs` == "trusty" ]]”
>
>
>
> I am planning to do fresh installation. Thanks in advance.
>
>
>
> From: Jason Trost [mailto:notifications@github.com]
> Sent: Monday, 3 August, 2015 11:14 PM
> To: threatstream/mhn <mhn@noreply.github.com>
> Cc: MustaqueA <mustaque.ahmad@ascendsys.com>
> Subject: Re: [mhn] How to remove Dionaea which has been installed through
> MHN Script (#199)
>
>
>
> When you are prompted like this, you should copy the file path of the top
> file and paste it into the prompt. Some of the new Ubuntu's ship with a new
> version of patch that is causing this issue. I haven't had a chance to fix
> it yet.
>
> To remove dionaea, do this:
>
> if [[ `lsb_release -cs` == "trusty" ]] ; then apt-get remove -y
> dionaea-phibo; else apt-get remove -y dionaea ; fi
> rm -rf /var/dionaea/wwwroot /var/dionaea/binaries /var/dionaea/log
> /etc/dionaea/dionaea.conf /etc/supervisor/conf.d/dionaea.conf
> supervisorctl update
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/threatstream/mhn/issues/199#issuecomment-127273754> . <
> https://github.com/notifications/beacon/AM_gXr5OSZH8mLQ1Wn4TChuVHxhB3b7vks5oj3zLgaJpZM4Fkgn0.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/199#issuecomment-127285499>.
>



-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by MustaqueA** [comment]
Ok after I run the below suggested command, below are the supervisor status. 

 

sudo supervisorctl status

dionaea                          FATAL      can't find command 'dionaea'

 

I can still see the directory related to Dionaea. Just curious to know if it has completely gone from my box. 

 

Thanks and Regards

**Comment by jt6211** [comment]
You need to run those commands as root

On Monday, August 3, 2015, MustaqueA <notifications@github.com> wrote:

> Ok after I run the below suggested command, below are the supervisor
> status.
>
>
>
> sudo supervisorctl status
>
> dionaea FATAL can't find command 'dionaea'
>
>
>
> I can still see the directory related to Dionaea. Just curious to know if
> it has completely gone from my box.
>
>
>
> Thanks and Regards
>
>
>
> From: Jason Trost [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Tuesday, 4 August, 2015 12:04 AM
> To: threatstream/mhn <mhn@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','mhn@noreply.github.com');>>
> Cc: MustaqueA <mustaque.ahmad@ascendsys.com
> <javascript:_e(%7B%7D,'cvml','mustaque.ahmad@ascendsys.com');>>
> Subject: Re: [mhn] How to remove Dionaea which has been installed through
> MHN Script (#199)
>
>
>
> /etc/dionaea/dionaea.conf <-- this would be the top file. You will get
> prompted again for a 2nd file as well. You will want to copy and paste the
> file path that does not end with .new each time.
>
> You will copy that command I sent and paste it into the terminal (i.e. just
> like you did with the long deploy command when you deployed the honeypot).
>
> On Mon, Aug 3, 2015 at 11:52 AM, MustaqueA <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');> <mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> > wrote:
>
> > Not Sure What do you mean by top file. First one is top file.
> >
> >
> >
> > --- /etc/dionaea/dionaea.conf This one is top file?
> >
> > +++ /etc/dionaea/dionaea.conf.new
> >
> >
> >
> > One more help may be stupid question however, where to put this “if [[
> > `lsb_release -cs` == "trusty" ]]”
> >
> >
> >
> > I am planning to do fresh installation. Thanks in advance.
> >
> >
> >
> > From: Jason Trost [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> > Sent: Monday, 3 August, 2015 11:14 PM
> > To: threatstream/mhn <mhn@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','mhn@noreply.github.com');> <mailto:
> mhn@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','mhn@noreply.github.com');>> >
> > Cc: MustaqueA <mustaque.ahmad@ascendsys.com
> <javascript:_e(%7B%7D,'cvml','mustaque.ahmad@ascendsys.com');> <mailto:
> mustaque.ahmad@ascendsys.com
> <javascript:_e(%7B%7D,'cvml','mustaque.ahmad@ascendsys.com');>> >
> > Subject: Re: [mhn] How to remove Dionaea which has been installed through
> > MHN Script (#199)
> >
> >
> >
> > When you are prompted like this, you should copy the file path of the top
> > file and paste it into the prompt. Some of the new Ubuntu's ship with a
> new
> > version of patch that is causing this issue. I haven't had a chance to
> fix
> > it yet.
> >
> > To remove dionaea, do this:
> >
> > if [[ `lsb_release -cs` == "trusty" ]] ; then apt-get remove -y
> > dionaea-phibo; else apt-get remove -y dionaea ; fi
> > rm -rf /var/dionaea/wwwroot /var/dionaea/binaries /var/dionaea/log
> > /etc/dionaea/dionaea.conf /etc/supervisor/conf.d/dionaea.conf
> > supervisorctl update
> >
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/threatstream/mhn/issues/199#issuecomment-127273754>
> . <
> >
> https://github.com/notifications/beacon/AM_gXr5OSZH8mLQ1Wn4TChuVHxhB3b7vks5oj3zLgaJpZM4Fkgn0.gif
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/threatstream/mhn/issues/199#issuecomment-127285499>.
> >
>
>
>
> --
> Jason Trost | Director of ThreatStream Labs | www.threatstream.com <
> http://www.threatstream.com>
> 2317 Broadway, 3rd Floor| Redwood City, CA 94063
> Phone: 386.235.0078 | Twitter: @jason_trost
>
>
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/threatstream/mhn/issues/199#issuecomment-127288540> . <
> https://github.com/notifications/beacon/AM_gXmLIJCqewpJbudkIX2T2LBr3aApnks5oj4hvgaJpZM4Fkgn0.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/199#issuecomment-127457400>.
>


-- 
Jason Trost | Director of ThreatStream Labs | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by MustaqueA** [comment]
I am running those command as root. And it does mentioned that Dionaea removed. However, when I checked the status it gives

 

root@mhn02:~# sudo supervisorctl status

dionaea                          FATAL      can't find command 'dionaea'

 

Also all the folders related to Dionaea still exist.

**Comment by jt6211** [comment]
Can you do this?

```
sudo rm -rf /etc/supervisor/conf.d/dionaea.conf
sudo supervisorctl update
sudo supervisorctl status
```

the update command is supposed to recgonize when a supervisor config is missing/added and update what should be running accordingly.
