### ISSUE TITLE
add cowrie support

### ISSUE THREAD

**Issue by xmppadmin** [threatstream/mhn#203]
Source:: https://github.com/micheloosterhof/cowrie

it seems a promising honeypot

**Comment by putsi** [comment]
This would be nice to have because of the new features and also even the original Kippo recommends using Cowrie instead.

**Comment by sh4t** [comment]
I have completed adding cowrie support to MHN and need to setup a vanilla MHN with the changes to issue a PR to add it in.  I will try to make this a priority next week @jt6211 so you can get it added.

**Comment by jt6211** [comment]
Thanks Justin

On Wed, Mar 23, 2016 at 4:52 PM, Justin Shattuck <notifications@github.com>
wrote:

> I have completed adding cowrie support to MHN and need to setup a vanilla
> MHN with the changes to issue a PR to add it in. I will try to make this a
> priority next week @jt6211 <https://github.com/jt6211> so you can get it
> added.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/203#issuecomment-200539342>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Antelox** [comment]
Hi, I wrote also on MHN's Google Groups but no answer got. For this enhancement you can see here:
https://groups.google.com/forum/#!topic/modern-honey-network/fBE1QnfYWRE

BR,

Antelox

**Comment by Antelox** [comment]
Finally problem solved! It was a cowrie related problem about lexer. Michel fixed it really quickly, tnx so much!!! =)

You can see Michel's commit here:

https://github.com/micheloosterhof/cowrie/commit/7fa2178629594c406ea3bca42da67136e24590e7

So now ticket can be closed if you accept my pull request.

BR,

Antelox

**Comment by andpast** [comment]
Hi All!

First of all thanks for great work!

But it's now enough for my environment (.

My question is how to get cowrie events in Splunk?

Is it possible in general?


Thanks,
Andrii

**Comment by jt6211** [comment]
@Antelox thanks for your work on this.  All your commits have been merged into MHN and I added hpfeeds-logger support as well.  Sorry for the delay.  I personally test all these contributions before merging (since I have to deal with the support questions :) ).

**Comment by jt6211** [comment]
ref: 
https://github.com/threatstream/mhn/pull/269
https://github.com/threatstream/mhn/pull/268
https://github.com/threatstream/mhn/pull/267
https://github.com/threatstream/mhn/pull/266
