### ISSUE TITLE
No attacks displayed on Honeymap

### ISSUE THREAD

**Issue by TheHades** [threatstream/mhn#204]
Hello Folks,

i dont see any action on my honeymap.

root@honeynest:~# sudo /etc/init.d/supervisor status
 is running

root@honeynest:~# sudo supervisorctl status
geoloc                           RUNNING    pid 1041, uptime 0:28:21
honeymap                         RUNNING    pid 1126, uptime 0:28:20
hpfeeds-broker                   RUNNING    pid 1129, uptime 0:28:20
hpfeeds-logger-json              RUNNING    pid 1061, uptime 0:28:21
kibana                           FATAL      Exited too quickly (process log may have details)
logstash                         RUNNING    pid 6499, uptime 0:00:10
mhn-celery-beat                  RUNNING    pid 1019, uptime 0:28:21
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)
mhn-collector                    STOPPED    Not started
mhn-uwsgi                        RUNNING    pid 1062, uptime 0:28:21
mnemosyne                        RUNNING    pid 1036, uptime 0:28:21

I also tried the solution in the troubleshoot guide (https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide), but this didnt worked.

root@honeynest:/opt/mhn/server# sudo chown www-data mhn.log
root@honeynest:/opt/mhn/server# sudo supervisorctl start mhn-celery-worker
mhn-celery-worker: ERROR (abnormal termination)

$MHN_HOME/server/worker.err  -> log is not created
$MHN_HOME/server/worker.log -> log is not created
$MHN_HOME/server/mhn.log -> log is empty

Do i have to install Splunk and Arcsight as well?

Thanks in advance, :)

**Comment by Waseem-farooqui** [comment]
Sorry but **troubleshooting-Guide** needs up-gradation.
The location of the logs has been changed, it is now at `/var/log/mhn/`.
Run  `sudo chown www-data /var/log/mhn/mhn.log` 
than run `sudo supervisorctl restart all`
 This will work after it you will be able to see events on honeymap at realtime.

**Comment by jt6211** [comment]
I updated the wiki. Thanks @Waseem-farooqui

What sensors types have you deployed? And where (internal network or public)?  Any chance they have a private IP?

Are you sure there is traffic going to them?  Who do you know?

**Comment by TheHades** [comment]
Hello @jt6211 
After executing the commands from @Waseem-farooqui post it worked. :)
