### ISSUE TITLE
Install crashes at hpfeeds

### ISSUE THREAD

**Issue by Tigzy** [threatstream/mhn#206]
Hello, I'm running install script on a naked Ubuntu 15.04, and it crashes while installing hpfeeds:
As a consequence, install script doesn't continue...

	+ python /opt/hpfeeds/broker/add_user.py mnemosyne 79c9aa9edc644e0d93f6e22607c4d63b '' amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events,elastichoney.events
	Traceback (most recent call last):
	  File "/opt/hpfeeds/broker/add_user.py", line 29, in <module>
		res = client.hpfeeds.auth_key.update({"identifier": ident}, {"$set": rec}, upsert=True)
	  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 1956, in update
		with self._socket_for_writes() as sock_info:
	  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
		return self.gen.next()
	  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 663, in _get_socket
		server = self._get_topology().select_server(selector)
	  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
		address))
	  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
		self._error_message(selector))
	pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by aabed** [comment]
make sure that mongo is installed and running properly 
dpkg --list |grep mongo
Examine /var/log/mongodb/mongod.log
and let us know

**Comment by Tigzy** [comment]
Is mongo a prerequisite? I'll run this later,thanks for the answer.

**Comment by aabed** [comment]
well, the installation script for hpfeeds installs mongo
install_hpfeeds.sh calls instakk_mongo.sh

**Comment by Tigzy** [comment]
osboxes@osboxes:/opt/mhn$ dpkg --list |grep mongo
ii  mongodb-org                                          2.6.11                                     amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                                   2.6.11                                     amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                                   2.6.11                                     amd64        MongoDB database server
ii  mongodb-org-shell                                    2.6.11                                     amd64        MongoDB shell client
ii  mongodb-org-tools                                    2.6.11                                     amd64        MongoDB tools
osboxes@osboxes:/opt/mhn$ tail -f /var/log/mongodb/mongod.log
tail: cannot open ‘/var/log/mongodb/mongod.log’ for reading: No such file or directory

**Comment by Tigzy** [comment]
I tried on a Ubuntu 14.04, install completed without error.
So I think this has to do with Ubuntu 15.04.

**Comment by lolorz12** [comment]
same issue exact same log output as tigzy I wonder if mongo didnt install correctly? tried -repair on mongo and restarting mongo --no-luck

**Comment by Aaron-Hartwig** [comment]
Running the install on Ubuntu 14.04 rather than 15 solved this issue for me as well.

**Comment by slw07g** [comment]
I modified  scripts/install_mongo.sh` so that it ran
`apt-get install mongodb` instead of `apt-get install mongodb-org`

(using lubuntu 16.04).
