### ISSUE TITLE
Honeymap not showing attacks

### ISSUE THREAD

**Issue by Tigzy** [threatstream/mhn#208]
Hello, I have attacks, I can see the flags of countries, but honeymap stays empty. 
I think something is miconfigured, could you tell me where to look?

Thanks.

**Comment by Waseem-farooqui** [comment]
Honey map Shows the attacks at real-time **of public IPs**. If you are not watching at real time too than check the status of  `geoloc` and `honeymap` whether they are running by `sudo supervisorctl status`.

**Comment by Tigzy** [comment]
Everything is up and running. And I can see the map.

root@ubuntu:/opt/mhn/server# sudo supervisorctl status
geoloc                           RUNNING    pid 6638, uptime 1:26:08
honeymap                         RUNNING    pid 6629, uptime 1:26:09
hpfeeds-broker                   RUNNING    pid 6646, uptime 1:26:05
mhn-celery-beat                  RUNNING    pid 6628, uptime 1:26:09
mhn-celery-worker                RUNNING    pid 6718, uptime 1:23:57
mhn-collector                    RUNNING    pid 6645, uptime 1:26:06
mhn-uwsgi                        RUNNING    pid 6639, uptime 1:26:07
mnemosyne                        RUNNING    pid 6636, uptime 1:26:09

"the attacks at real-time of public IPs" What do you mean? My honeypot is on a public IP (server) and the attacks are coming from public IP as well.

**Comment by Tigzy** [comment]
Ok I understand where the problem is. It's not showing PAST attacks, but only the ones that occured AFTER you open the map. Is it wanted behavior?

**Comment by Waseem-farooqui** [comment]
Yes this is it, It does not show Past Attacks, it shows real-time attacks.

**Comment by Tigzy** [comment]
Ok, that's fine then. Thanks.

**Comment by ferdasonmez** [comment]
Hi,
Can we use maltrail to visualize past mhn log files? I mean not real time visualization but visualization of pat events. Thank you for your interest.

Regards,
Ferda

**Comment by jt6211** [comment]
i have not heard of anyone doing this. It may be possible. MHN uses
hpfeed-logger to log hpfeeds data in various formats. You may be able to
ingest one of these into maltrail depending on what formats it accepts

**Comment by ferdasonmez** [comment]
Hi Jason :)
Thank you for your reply. I think the question that I asked is an ordinary scenario may be I should further clarify it. I just mean if I can visualize log outputs of for example last week's mhn execution using Maltrail. I think the answer should be yes but I am not sure and I can not try cause I do not have data for the time being. 
Best Regards,
Ferda
