### ISSUE TITLE
Kippo deploy fails if SSH server is not installed

### ISSUE THREAD

**Issue by putsi** [threatstream/mhn#212]
The Kippo deployment script fails if a SSH server is not installed (Ubuntu 14.04). 

The failure happens in [Line 26 of deploy_kippo.sh](https://github.com/threatstream/mhn/blob/master/scripts/deploy_kippo.sh#L26) due to the missing sshd_config-file.

**Comment by Waseem-farooqui** [comment]
yes you need to install ssh server it is pre-requirement  @jt6211 it good to update line 22 **from** 
`apt-get -y install python-dev openssl python-openssl python-pyasn1 python-twisted git python-pip supervisor authbind`
**to** 
`apt-get -y install openssh-server python-dev openssl python-openssl python-pyasn1 python-twisted git python-pip supervisor authbind`
This will resolve this issue.

**Comment by cloughrm** [comment]
Closing this issue, as it appears to have been resolved.
