### ISSUE TITLE
Add existing Sensor to MHN Server-Need Help

### ISSUE THREAD

**Issue by MarcoGeek** [threatstream/mhn#214]
Add Sensor to MHN Server= This I can see

Add hpfeeds user = I believe this needs to be done at MHN server. However, Could you tell where in hpfeeds we will make this changes in detail. 

cd /opt/hpfeeds/broker and changes would be database.py if yes wehre in this file.

source env/bin/activate= What is this? 

python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS" = Where exactly to add this.

3. Configure the honeypot= This I can see on the honeypot conf file. Only UUID and IP needs to be added. correct?

Any detail help and information is appreciated.

Thanks

**Comment by jt6211** [comment]
> Add hpfeeds user = I believe this needs to be done at MHN server. However, Could you tell where in hpfeeds we will make this changes in detail.

Yes, this needs to be done on the MHN server.  See list of commands to run here: https://github.com/threatstream/mhn/wiki/Incorporate-an-already-deployed-Honeypot-into-MHN#2-add-hpfeeds-user.  The top part of the commands are setting environment variables.  Run these in a terminal.  After these commands are run the auth_key collection in the hpfeeds database in MongoDB will be updated.

> source env/bin/activate= What is this?

MHN uses virtualenv to isolate python package dependencies.  This is how to load up the already installed python packages.

> python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS" = 
> Where exactly to add this.

You don't add this.  You run this in a terminal.

> Configure the honeypot= This I can see on the honeypot conf file. Only UUID and IP needs to be added. correct?

No all the fields need to be configured.  It would be easier if you mentioned which sensor you are trying to deploy.

**Comment by cloughrm** [comment]
Closing ticket, as the issue appears to have been resolved
