### ISSUE TITLE
deleted sensor yet still recieving data

### ISSUE THREAD

**Issue by gregtampa** [threatstream/mhn#216]
in Sensors I pressed the trash icon next to some sensors.
I look in attacks and it seem it is still pushing data from those sensors into the database.
should I restart or something after deletion?

**Comment by jt6211** [comment]
Currently deleting the sensor removes it from management, but it does not undeploy or halt the actual sensor.

**Comment by gregtampa** [comment]
removing it from the mongodb and restarting the service will stop the alerts from being recorded.
problem was the sensors that i removed was still feeding data to the api and causing bad data.
trying to split sensors to multiple user accounts.
