### ISSUE TITLE
Export to mySQL

### ISSUE THREAD

**Issue by Keldo** [threatstream/mhn#217]
Can anyone explain how to export the data from MHN to mySQL to report on a website? My site is PHP / MySQLi based.

**Comment by gregtampa** [comment]
I would like to know this too.

**Comment by gregtampa** [comment]
Or even convert the whole mhm mongo to mysql

**Comment by jt6211** [comment]
The easiest way to do this might be to export the data from mongo to CSV
and then load the CSV directly into MySQL.

See
https://github.com/threatstream/mhn/wiki/Exporting-Honeypot-Data-from-MHN

And

https://dev.mysql.com/doc/refman/5.1/en/load-data.html

Switching MHNs backend to MySQL would be quite a bit of work though.

On Sunday, October 18, 2015, Gregory Hanis <notifications@github.com> wrote:

> Or even convert the whole mhm mongo to mysql
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/217#issuecomment-149028256>.
>


-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Keldo** [comment]
Im not looking to change the data scheme to mysql, Im just looking to export activity to display on my primary site.

**Comment by Keldo** [comment]
importing this csv puts things like "source_port" : XXXXX, how do I get rid of the "" and the :

**Comment by jt6211** [comment]
I think you ran the wrong command.  You need to run the CSV output'ing command:

Example:

```
mongoexport --db mnemosyne --collection session --fields=_id,destination_ip,protocol,hpfeed_id,timestamp,source_ip,source_port,destination_port,identifier,honeypot --csv
```

**Comment by Keldo** [comment]
Thanks,
It's working..  https://www.twistedsecurity.com/attacks.php
