### ISSUE TITLE
honeymap-FATAL-Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by Akhitha** [threatstream/mhn#219]
I have followed the link below to install mhn in server.
https://zeltser.com/modern-honey-network-experiments/
'supervisorctl status' shows honeymap status as honeymap-FATAL-Exited too quickly (process log may have details).
Console output of installation 

=============================================
root@server:/opt/mhn/scripts# ./install_honeymap.sh
+ apt-get install -y git mercurial make coffeescript
Reading package lists... Done
Building dependency tree
Reading state information... Done
make is already the newest version.
coffeescript is already the newest version.
git is already the newest version.
mercurial is already the newest version.
The following packages were automatically installed and are no longer required:
  libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
  linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
  linux-image-extra-3.13.0-66-generic
Use 'apt-get autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
++ uname -m
+ '[' x86_64 == x86_64 ']'
+ GO_PACKAGE=go1.4.2.linux-amd64.tar.gz
+ cd /usr/local/
+ wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
--2015-11-08 13:07:09--  https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.208.80, 2a00:1450:4009:80a::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.208.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62442704 (60M) [application/x-gzip]
Saving to: ‘go1.4.2.linux-amd64.tar.gz’

100%[===============================================================================================>] 62,442,704  72.2MB/s   in 0.8s

2015-11-08 13:07:11 (72.2 MB/s) - ‘go1.4.2.linux-amd64.tar.gz’ saved [62442704/62442704]

+ tar zxf go1.4.2.linux-amd64.tar.gz
+ rm go1.4.2.linux-amd64.tar.gz
+ cd /usr/bin/
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/go
/usr/local/go/bin/go
+ ln -s /usr/local/go/bin/go
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/godoc
/usr/local/go/bin/godoc
+ ln -s /usr/local/go/bin/godoc
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/gofmt
/usr/local/go/bin/gofmt
+ ln -s /usr/local/go/bin/gofmt
++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
+ SECRET=43db3840047f4180b6beb0d0e137aedd
+ /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py honeymap 43db3840047f4180b6beb0d0e137aedd '' geoloc.events
updated {'subscribe': ['geoloc.events'], 'secret': '43db3840047f4180b6beb0d0e137aedd', 'identifier': 'honeymap', 'publish': []}
+ cd /opt
+ git clone https://github.com/threatstream/honeymap.git
Cloning into 'honeymap'...
remote: Counting objects: 817, done.
remote: Total 817 (delta 0), reused 0 (delta 0), pack-reused 817
Receiving objects: 100% (817/817), 1.02 MiB | 0 bytes/s, done.
Resolving deltas: 100% (403/403), done.
Checking connectivity... done.
+ cd /opt/honeymap/server
++ pwd
+ export GOPATH=/opt/honeymap/server
+ GOPATH=/opt/honeymap/server
+ go get
go install: no install location for directory /opt/honeymap/server outside GOPATH
+ go build
+ cat
+ cd ..
+ make
coffee -cj client/js/honeymap.js client/coffee/*.coffee client/coffee/feeds/hpfeeds.coffee
cd server; go build
+ mkdir -p /var/log/mhn
+ apt-get install -y supervisor
Reading package lists... Done
Building dependency tree
Reading state information... Done
supervisor is already the newest version.
The following packages were automatically installed and are no longer required:
  libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
  linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
  linux-image-extra-3.13.0-66-generic
Use 'apt-get autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
+ cat
+ apt-get install -y libgeoip-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgeoip-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
  linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
  linux-image-extra-3.13.0-66-generic
Use 'apt-get autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
+ /opt/hpfeeds/env/bin/pip install GeoIP
Requirement already satisfied (use --upgrade to upgrade): GeoIP in /opt/hpfeeds/env/lib/python2.7/site-packages
+ cd /opt/
+ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
--2015-11-08 13:07:29--  http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... 141.101.114.190, 141.101.115.190, 2400:cb00:2048:1::8d65:73be, ...
Connecting to geolite.maxmind.com (geolite.maxmind.com)|141.101.114.190|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12315807 (12M) [application/octet-stream]
Saving to: ‘GeoLiteCity.dat.gz’

100%[===============================================================================================>] 12,315,807  --.-K/s   in 0.1s

2015-11-08 13:07:29 (116 MB/s) - ‘GeoLiteCity.dat.gz’ saved [12315807/12315807]

+ gzip -d GeoLiteCity.dat.gz
+ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
--2015-11-08 13:07:29--  http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... 141.101.115.190, 141.101.114.190, 2400:cb00:2048:1::8d65:73be, ...
Connecting to geolite.maxmind.com (geolite.maxmind.com)|141.101.115.190|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12606986 (12M) [application/octet-stream]
Saving to: ‘GeoLiteCityv6.dat.gz’

100%[===============================================================================================>] 12,606,986  --.-K/s   in 0.1s

2015-11-08 13:07:29 (113 MB/s) - ‘GeoLiteCityv6.dat.gz’ saved [12606986/12606986]

+ gzip -d GeoLiteCityv6.dat.gz
+ wget http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
--2015-11-08 13:07:29--  http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
Resolving download.maxmind.com (download.maxmind.com)... 141.101.114.190, 141.101.115.190, 2400:cb00:2048:1::8d65:72be, ...
Connecting to download.maxmind.com (download.maxmind.com)|141.101.114.190|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2184298 (2.1M) [application/octet-stream]
Saving to: ‘GeoIPASNum.dat.gz’

100%[===============================================================================================>] 2,184,298   --.-K/s   in 0.04s

2015-11-08 13:07:30 (51.6 MB/s) - ‘GeoIPASNum.dat.gz’ saved [2184298/2184298]

+ gzip -d GeoIPASNum.dat.gz
++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
+ SECRET=40d69a8e261749f590a493ebfcda3431
+ /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py geoloc 40d69a8e261749f590a493ebfcda3431 geoloc.events amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,conpot.events,snort.alerts,kippo.alerts,wordpot.events,shockpot.events,p0f.events,suricata.events,elastichoney.events
updated {'subscribe': ['amun.events', 'dionaea.connections', 'dionaea.capture', 'glastopf.events', 'beeswarm.hive', 'kippo.sessions', 'conpot.events', 'snort.alerts', 'kippo.alerts', 'wordpot.events', 'shockpot.events', 'p0f.events', 'suricata.events', 'elastichoney.events'], 'secret': '40d69a8e261749f590a493ebfcda3431', 'identifier': 'geoloc', 'publish': ['geoloc.events']}
+ cat
+ cat
+ supervisorctl update

=============================================

=============================================
root@server:/opt/mhn/scripts# cat /var/log/mhn/geoloc.err
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
connected to @hp2
=============================================

=============================================
root@server:/opt/mhn/scripts# cat /var/log/mhn/honeymap.err
2015/11/08 07:23:34 Binding Honeymap webserver to 0.0.0.0:3000...
2015/11/08 07:23:34 listen tcp 0.0.0.0:3000: bind: address already in use
2015/11/08 07:23:35 Binding Honeymap webserver to 0.0.0.0:3000...
2015/11/08 07:23:35 listen tcp 0.0.0.0:3000: bind: address already in use
2015/11/08 07:23:37 Binding Honeymap webserver to 0.0.0.0:3000...
2015/11/08 07:23:37 listen tcp 0.0.0.0:3000: bind: address already in use
2015/11/08 07:23:41 Binding Honeymap webserver to 0.0.0.0:3000...
2015/11/08 07:23:41 listen tcp 0.0.0.0:3000: bind: address already in use
=============================================

**Comment by jt6211** [comment]
The installation has changed slightly.  Can you try the installation shown
on the main MHN githib page?

https://github.com/threatstream/mhn#installing-server-tested-ubuntu-12043-x86_64

On Sun, Nov 8, 2015 at 8:17 AM, Akhitha <notifications@github.com> wrote:

> I have followed the link below to install mhn in server.
> https://zeltser.com/modern-honey-network-experiments/
> 'supervisorctl status' shows honeymap status as honeymap-FATAL-Exited too
> quickly (process log may have details).
> Console output of installation
>
> root@server:/opt/mhn/scripts# ./install_honeymap.sh
>
>    - apt-get install -y git mercurial make coffeescript Reading package
>    lists... Done Building dependency tree Reading state information... Done
>    make is already the newest version. coffeescript is already the newest
>    version. git is already the newest version. mercurial is already the newest
>    version. The following packages were automatically installed and are no
>    longer required: libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
>    linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
>    linux-image-extra-3.13.0-66-generic Use 'apt-get autoremove' to remove
>    them. 0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
>    ++ uname -m
>    - '[' x86_64 == x86_64 ']'
>    - GO_PACKAGE=go1.4.2.linux-amd64.tar.gz
>    - cd /usr/local/
>    - wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
>    --2015-11-08 13:07:09--
>    https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
>    Resolving storage.googleapis.com (storage.googleapis.com)...
>    216.58.208.80, 2a00:1450:4009:80a::2010 Connecting to
>    storage.googleapis.com (storage.googleapis.com)|216.58.208.80|:443...
>    connected. HTTP request sent, awaiting response... 200 OK Length: 62442704
>    (60M) [application/x-gzip] Saving to: ‘go1.4.2.linux-amd64.tar.gz’
>
> 100%[===============================================================================================>]
> 62,442,704 72.2MB/s in 0.8s
>
> 2015-11-08 13:07:11 (72.2 MB/s) - ‘go1.4.2.linux-amd64.tar.gz’ saved
> [62442704/62442704]
>
>    - tar zxf go1.4.2.linux-amd64.tar.gz
>    - rm go1.4.2.linux-amd64.tar.gz
>    - cd /usr/bin/
>    - for X in '/usr/local/go/bin/*'
>    - echo /usr/local/go/bin/go /usr/local/go/bin/go
>    - ln -s /usr/local/go/bin/go
>    - for X in '/usr/local/go/bin/*'
>    - echo /usr/local/go/bin/godoc /usr/local/go/bin/godoc
>    - ln -s /usr/local/go/bin/godoc
>    - for X in '/usr/local/go/bin/*'
>    - echo /usr/local/go/bin/gofmt /usr/local/go/bin/gofmt
>    - ln -s /usr/local/go/bin/gofmt ++ python -c 'import uuid;print
>    str(uuid.uuid4()).replace("-","")'
>    - SECRET=43db3840047f4180b6beb0d0e137aedd
>    - /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py honeymap
>    43db3840047f4180b6beb0d0e137aedd '' geoloc.events updated {'subscribe':
>    ['geoloc.events'], 'secret': '43db3840047f4180b6beb0d0e137aedd',
>    'identifier': 'honeymap', 'publish': []}
>    - cd /opt
>    - git clone https://github.com/threatstream/honeymap.git Cloning into
>    'honeymap'... remote: Counting objects: 817, done. remote: Total 817 (delta
>    0), reused 0 (delta 0), pack-reused 817 Receiving objects: 100% (817/817),
>    1.02 MiB | 0 bytes/s, done. Resolving deltas: 100% (403/403), done.
>    Checking connectivity... done.
>    - cd /opt/honeymap/server ++ pwd
>    - export GOPATH=/opt/honeymap/server
>    - GOPATH=/opt/honeymap/server
>    - go get go install: no install location for directory
>    /opt/honeymap/server outside GOPATH
>    - go build
>    - cat
>    - cd ..
>    - make coffee -cj client/js/honeymap.js client/coffee/*.coffee
>    client/coffee/feeds/hpfeeds.coffee cd server; go build
>    - mkdir -p /var/log/mhn
>    - apt-get install -y supervisor Reading package lists... Done Building
>    dependency tree Reading state information... Done supervisor is already the
>    newest version. The following packages were automatically installed and are
>    no longer required: libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
>    linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
>    linux-image-extra-3.13.0-66-generic Use 'apt-get autoremove' to remove
>    them. 0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
>    - cat
>    - apt-get install -y libgeoip-dev Reading package lists... Done
>    Building dependency tree Reading state information... Done libgeoip-dev is
>    already the newest version. The following packages were automatically
>    installed and are no longer required: libgsoap4 libvncserver0
>    linux-cloud-tools-3.13.0-66 linux-cloud-tools-3.13.0-66-generic
>    linux-image-3.13.0-66-generic linux-image-extra-3.13.0-66-generic Use
>    'apt-get autoremove' to remove them. 0 to upgrade, 0 to newly install, 0 to
>    remove and 0 not to upgrade.
>    - /opt/hpfeeds/env/bin/pip install GeoIP Requirement already satisfied
>    (use --upgrade to upgrade): GeoIP in
>    /opt/hpfeeds/env/lib/python2.7/site-packages
>    - cd /opt/
>    - wget
>    http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
>    --2015-11-08 13:07:29--
>    http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
>    Resolving geolite.maxmind.com (geolite.maxmind.com)...
>    141.101.114.190, 141.101.115.190, 2400:cb00:2048:1::8d65:73be, ...
>    Connecting to geolite.maxmind.com (geolite.maxmind.com)|141.101.114.190|:80...
>    connected. HTTP request sent, awaiting response... 200 OK Length: 12315807
>    (12M) [application/octet-stream] Saving to: ‘GeoLiteCity.dat.gz’
>
> 100%[===============================================================================================>]
> 12,315,807 --.-K/s in 0.1s
>
> 2015-11-08 13:07:29 (116 MB/s) - ‘GeoLiteCity.dat.gz’ saved
> [12315807/12315807]
>
>    - gzip -d GeoLiteCity.dat.gz
>    - wget
>    http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
>    --2015-11-08 13:07:29--
>    http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
>    Resolving geolite.maxmind.com (geolite.maxmind.com)...
>    141.101.115.190, 141.101.114.190, 2400:cb00:2048:1::8d65:73be, ...
>    Connecting to geolite.maxmind.com (geolite.maxmind.com)|141.101.115.190|:80...
>    connected. HTTP request sent, awaiting response... 200 OK Length: 12606986
>    (12M) [application/octet-stream] Saving to: ‘GeoLiteCityv6.dat.gz’
>
> 100%[===============================================================================================>]
> 12,606,986 --.-K/s in 0.1s
>
> 2015-11-08 13:07:29 (113 MB/s) - ‘GeoLiteCityv6.dat.gz’ saved
> [12606986/12606986]
>
>    - gzip -d GeoLiteCityv6.dat.gz
>    - wget
>    http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
>    --2015-11-08 13:07:29--
>    http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
>    Resolving download.maxmind.com (download.maxmind.com)...
>    141.101.114.190, 141.101.115.190, 2400:cb00:2048:1::8d65:72be, ...
>    Connecting to download.maxmind.com (download.maxmind.com)|141.101.114.190|:80...
>    connected. HTTP request sent, awaiting response... 200 OK Length: 2184298
>    (2.1M) [application/octet-stream] Saving to: ‘GeoIPASNum.dat.gz’
>
> 100%[===============================================================================================>]
> 2,184,298 --.-K/s in 0.04s
>
> 2015-11-08 13:07:30 (51.6 MB/s) - ‘GeoIPASNum.dat.gz’ saved
> [2184298/2184298]
>
>    - gzip -d GeoIPASNum.dat.gz ++ python -c 'import uuid;print
>    str(uuid.uuid4()).replace("-","")'
>    - SECRET=40d69a8e261749f590a493ebfcda3431
>    - /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py geoloc
>    40d69a8e261749f590a493ebfcda3431 geoloc.events
>    amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,conpot.events,snort.alerts,kippo.alerts,wordpot.events,shockpot.events,p0f.events,suricata.events,elastichoney.events
>    updated {'subscribe': ['amun.events', 'dionaea.connections',
>    'dionaea.capture', 'glastopf.events', 'beeswarm.hive', 'kippo.sessions',
>    'conpot.events', 'snort.alerts', 'kippo.alerts', 'wordpot.events',
>    'shockpot.events', 'p0f.events', 'suricata.events', 'elastichoney.events'],
>    'secret': '40d69a8e261749f590a493ebfcda3431', 'identifier': 'geoloc',
>    'publish': ['geoloc.events']}
>    - cat
>    - cat
>    - supervisorctl update
>
> root@server:/opt/mhn/scripts# cat /var/log/mhn/geoloc.err
> Parsing config file: /opt/hpfeeds/geoloc.json
> Traceback (most recent call last):
> File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line
> 137, in connect
> self.s.connect((addr, self.port))
> File "/usr/lib/python2.7/socket.py", line 224, in meth
> return getattr(self._sock,name)(*args)
> error: [Errno 111] Connection refused
> connected to @hp2 <https://github.com/hp2>
>
> root@server:/opt/mhn/scripts# cat /var/log/mhn/honeymap.err
> 2015/11/08 07:23:34 Binding Honeymap webserver to 0.0.0.0:3000...
> 2015/11/08 07:23:34 listen tcp 0.0.0.0:3000: bind: address already in use
> 2015/11/08 07:23:35 Binding Honeymap webserver to 0.0.0.0:3000...
> 2015/11/08 07:23:35 listen tcp 0.0.0.0:3000: bind: address already in use
> 2015/11/08 07:23:37 Binding Honeymap webserver to 0.0.0.0:3000...
> 2015/11/08 07:23:37 listen tcp 0.0.0.0:3000: bind: address already in use
> 2015/11/08 07:23:41 Binding Honeymap webserver to 0.0.0.0:3000...
> 2015/11/08 07:23:41 listen tcp 0.0.0.0:3000: bind: address already in use
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/219>.
>



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Akhitha** [comment]
I tried the mentioned guide. Now, am getting nginx dependency errors. I tried several fix for broken packages. Still, its error. The last portion of installation output from console.
=====================================
+ apt-get install -y nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgsoap4 libvncserver0 linux-cloud-tools-3.13.0-66
  linux-cloud-tools-3.13.0-66-generic linux-image-3.13.0-66-generic
  linux-image-extra-3.13.0-66-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  nginx-common nginx-core
Suggested packages:
  fcgiwrap nginx-doc
The following NEW packages will be installed
  nginx nginx-common nginx-core
0 to upgrade, 3 to newly install, 0 to remove and 0 not to upgrade.
Need to get 348 kB of archives.
After this operation, 1,297 kB of additional disk space will be used.
Get:1 http://gb.archive.ubuntu.com/ubuntu/ trusty-updates/main nginx-common all 1.4.6-1ubuntu3.3 [18.1 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu/ trusty-updates/main nginx-core amd64 1.4.6-1ubuntu3.3 [324 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu/ trusty-updates/main nginx all 1.4.6-1ubuntu3.3 [5,452 B]
Fetched 348 kB in 0s (1,398 kB/s)
(Reading database ... 241407 files and directories currently installed.)
Preparing to unpack .../nginx-common_1.4.6-1ubuntu3.3_all.deb ...
Unpacking nginx-common (1.4.6-1ubuntu3.3) ...
dpkg: error processing archive /var/cache/apt/archives/nginx-common_1.4.6-1ubuntu3.3_all.deb (--unpack):
 trying to overwrite '/etc/default/nginx', which is also in package sw-nginx 1.9.4-ubuntu14.04.15091112
Preparing to unpack .../nginx-core_1.4.6-1ubuntu3.3_amd64.deb ...
Unpacking nginx-core (1.4.6-1ubuntu3.3) ...
dpkg: error processing archive /var/cache/apt/archives/nginx-core_1.4.6-1ubuntu3.3_amd64.deb (--unpack):
 trying to overwrite '/usr/sbin/nginx', which is also in package sw-nginx 1.9.4-ubuntu14.04.15091112
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package nginx.
Preparing to unpack .../nginx_1.4.6-1ubuntu3.3_all.deb ...
Unpacking nginx (1.4.6-1ubuntu3.3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/nginx-common_1.4.6-1ubuntu3.3_all.deb
 /var/cache/apt/archives/nginx-core_1.4.6-1ubuntu3.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
===================================

**Comment by Akhitha** [comment]
I have fixed nginx errors. For the below errors, I found that drwebd daemon was already using port 3000.

/var/log/mhn/honeymap.err
2015/11/09 08:37:09 Binding Honeymap webserver to 0.0.0.0:3000...
2015/11/09 08:37:09 listen tcp 0.0.0.0:3000: bind: address already in use

So, I stopped the service and honeymap is now running. 

geoloc                           RUNNING    pid 4271, uptime 0:41:20
honeymap                         RUNNING    pid 8026, uptime 0:04:56
hpfeeds-broker                   RUNNING    pid 4293, uptime 0:41:18
mhn-celery-beat                  RUNNING    pid 4259, uptime 0:41:20
mhn-celery-worker                RUNNING    pid 4771, uptime 0:35:21
mhn-collector                    RUNNING    pid 4287, uptime 0:41:19
mhn-uwsgi                        RUNNING    pid 4275, uptime 0:41:19
mnemosyne                        RUNNING    pid 4266, uptime 0:41:20


But, I would like to know if I can change honeymap to a different port. When I edited the scripts , it didnt work.

**Comment by jt6211** [comment]
You can change honeymap to a different port like this:

cd /opt/honeymap/server
vi honeymap.go

Change the line that looks like this (change 3000 to whatever port you want):

const bind = "0.0.0.0:3000"

Then run:

cd /opt/honeymap/server
export GOPATH=`pwd`
go get
go build
sudo supervisorctl restart honeymap

cd /opt/mhn/server
vi config.py

change the port defined in HONEYMAP_URL from 3000 to the new port.

Then run:

sudo supervisorctl restart mhn-uwsgi



On Mon, Nov 9, 2015 at 4:19 AM, Akhitha <notifications@github.com> wrote:
> I have fixed nginx errors. For the below errors, I found that drwebd daemon
> was already using port 3000.
>
> /var/log/mhn/honeymap.err
> 2015/11/09 08:37:09 Binding Honeymap webserver to 0.0.0.0:3000...
> 2015/11/09 08:37:09 listen tcp 0.0.0.0:3000: bind: address already in use
>
> So, I stopped the service and honeymap is now running.
>
> geoloc RUNNING pid 4271, uptime 0:41:20
> honeymap RUNNING pid 8026, uptime 0:04:56
> hpfeeds-broker RUNNING pid 4293, uptime 0:41:18
> mhn-celery-beat RUNNING pid 4259, uptime 0:41:20
> mhn-celery-worker RUNNING pid 4771, uptime 0:35:21
> mhn-collector RUNNING pid 4287, uptime 0:41:19
> mhn-uwsgi RUNNING pid 4275, uptime 0:41:19
> mnemosyne RUNNING pid 4266, uptime 0:41:20
>
> But, I would like to know if I can change honeymap to a different port. When
> I edited the scripts , it didnt work.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Akhitha** [comment]
Thank You..

**Comment by Akhitha** [comment]
With reference to https://github.com/threatstream/mhn/issues/221, will changing the web server listening port resolve the issue?  I want MHN to appear only for my domain.

Can I add a dedicated IP address for my domain and use that IP address for server base url, honeymap url etc? Can I change the IP address or domain without re-installation? Please help.
