### ISSUE TITLE
MHN installation

### ISSUE THREAD

**Issue by Akhitha** [threatstream/mhn#220]
I have done MHN installation as per the guide below.
https://github.com/threatstream/mhn#installing-server-tested-ubuntu-12043-x86_64

I can see only the following processes running.

root@server:/var/log/mhn# supervisorctl status
geoloc                           RUNNING    pid 3788, uptime 2:36:25
honeymap                         RUNNING    pid 3789, uptime 2:36:25
hpfeeds-broker                   RUNNING    pid 16921, uptime 2:41:12
mnemosyne                        RUNNING    pid 2472, uptime 2:38:39
root@server:/var/log/mhn#

The other processes mhn-celery-beat, mhn-celery-worker, mhn-collector, mhn-uwsgi are not coming up. 

root@server:/opt/mhn# supervisorctl start mhn-celery-worker
mhn-celery-worker: ERROR (no such process)

**Comment by jt6211** [comment]
What OS and version?

Can you post the following logs to modern-honey-network@googlegroups.com?

* installation log (output on the terminal from when you ran install.sh if you still have it?
* tar zcvf mhn-logs.tar.gz /var/log/mhn/*.log /var/log/mhn/*.err
