### ISSUE TITLE
change MHN domain

### ISSUE THREAD

**Issue by Akhitha** [threatstream/mhn#221]
I have installed MHN in an ubuntu 14.04.3 LTS server. While installation, I did not change the server base URL and honeynet URL. By default, server IP address was taken.

But now I see that honeymap map appears on other domains at port 3000. Is there a solution to change MHN to appear only for my domain (like mydomain.com, mydomain.com:3000 etc)? 
Is there a solution to change it without re-installing MHN from scratch? Please help.

**Comment by jt6211** [comment]
MHN uses nginx to handle the web requests.  You can modify the nginx config so it will only respond to requests for your domain.  You should just need to edit this file:

/etc/nginx/sites-enabled/mhn-http and change `server_name  _;` to `server_name  www.mysite.com;`.  You can do something similar with honeymap, but this is a little more involved.  

If you do this, you will also need to modify your /opt/mhn/server/config.py and change the URLs for your site.  And then run: `sudo supervisorctl restart mhn-uwsgi `

Here is a related reference but for https: https://github.com/threatstream/mhn/wiki/Running-MHN-Over-HTTPS.
