### ISSUE TITLE
Debian install 404  Not Found

### ISSUE THREAD

**Issue by Madmaner107** [threatstream/mhn#222]
W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/wheezy/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/wheezy/main/binary-armhf/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

why？

**Comment by Madmaner107** [comment]
@jt6211 help!!!

**Comment by fheuer** [comment]
It looks like there is no wheezy directory. I'd choose trusty.

http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/

**Comment by jt6211** [comment]
Which honeypot are you installing? Dionaea?

**Comment by Madmaner107** [comment]
yes

wget "http://ip/api/script/?text=true&script_id=10" -O deploy.sh && sudo bash deploy.sh http://ip 8vbCTdXG

**Comment by Madmaner107** [comment]
Raspberry Pi  install  node

**Comment by jt6211** [comment]
It looks like you ran the dionaea install script not the raspberry pi Dionaea script: https://github.com/threatstream/mhn/blob/master/scripts/deploy_raspberrypi.sh

Can you try this one?

**Comment by cloughrm** [comment]
@Madmaner107 any update on this issue?

**Comment by cloughrm** [comment]
Closing issue, no response
