### ISSUE TITLE
Customize MHN

### ISSUE THREAD

**Issue by Akhitha** [threatstream/mhn#223]
I am trying to add more links in MHN dashboard. I have edited /opt/mhn/server/mhn/templates/base.html and added the link as follows.

 <li><a href="{{ url_for('ui.newlink') }}">newlink</a></li>

Also, I have modified /opt/mhn/server/mhn/ui/views.py and added the below lines.

@ui.route('/newlink/', methods=['GET'])
@login_required
def newlink():
    return render_template('ui/newlink.html')

But, it loads internal server error in dashboard. In base.html, if I change the line as belo, it just shows the new link.
<li><a>newlink</a></li>

So, I see the problem is with specifying url_for of flask. Is there any other changes I have to make to add new options.

Thank You

**Comment by jt6211** [comment]
Can you fork the MHN repo and push your code to a branch in your repo so I can look at your full code?

**Comment by cloughrm** [comment]
@Akhitha any update on this issue?

**Comment by cloughrm** [comment]
Closing issue, no response
