### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by Madmaner107** [threatstream/mhn#224]
- pip install -r requirements.txt
  Collecting git+https://github.com/defnull/bottle/ (from -r requirements.txt (line 5))
  Cloning https://github.com/defnull/bottle/ to /tmp/pip-D5nqwO-build
  Collecting pymongo==2.7.2 (from -r requirements.txt (line 1))
  /opt/mnemosyne/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  /opt/mnemosyne/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement pymongo==2.7.2 (from -r requirements.txt (line 1)) (from versions: )
  No matching distribution found for pymongo==2.7.2 (from -r requirements.txt (line 1))
  /opt/mnemosyne/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by cloughrm** [comment]
Can you please provide more details? What OS and version? What version of python are you using?
