### ISSUE TITLE
The port 80 is conflict between mhn and conpot 

### ISSUE THREAD

**Issue by ppmorning** [threatstream/mhn#227]
The port 80 is needed in conpot. So when I deploy the conpot in the mhn, the conpot is always exit on the http port 80. I try to modify the conpot port 80 to 8080 , but it is failed, and I try to modify the mhn port 80 to 8888, but it is also failed . What should I do?

**Comment by ppmorning** [comment]
I solved it. I modify the file in path /etc/nginx/sites-enabled/default to port 8080

**Comment by cloughrm** [comment]
Closing this issue, as it appears to have been resolved.
