### ISSUE TITLE
css broke after changing everything to tls from regular. http->https

### ISSUE THREAD

**Issue by ChrisFernandez** [threatstream/mhn#229]
followed the ssl instructions on the wiki, I did this but now the CSS is broke, even do I edited the mhn config to reflect https instead of http.
example:
server/config.py:SERVER_BASE_URL = 'https://myserver.org'
server/config.py:HONEYMAP_URL = 'https://myserver.org:8443'
im sure im missing something.. 
I did the install it was all working then I saw the wiki and decided to follow up to enable ssl for everything. thats when it broke.

**Comment by jt6211** [comment]
Did you also make the required changes to nginx? If so can you send me your
nginx config

On Wednesday, January 13, 2016, Fernandez, Chris <notifications@github.com>
wrote:

> hello I did this but now the CSS is broke, even do I edited the mhn config
> to reflect https instead of http.
> example:
> server/config.py:SERVER_BASE_URL = 'https://myserver.org'
> server/config.py:HONEYMAP_URL = 'https://myserver.org:8443'
> im sure im missing something..
> I did the install it was all working then I saw the wiki and decided to
> follow up to enable ssl for everything. thats when it broke.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/229>.
>


-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
Hello, is exactly the same as this but of course the name of the certs are different.
https://github.com/threatstream/mhn/wiki/Running-MHN-Over-HTTPS
tls is working, is just the CSS seens like it may still be calling http from somewhere. here is a snapshot.
![screenshot_20160113_125902](https://cloud.githubusercontent.com/assets/5316229/12307669/86e994aa-b9f5-11e5-9dc7-463b419314ac.png)

**Comment by jt6211** [comment]
Can you open google developer tools and report any error messages seen.
For instance, what requests are failing for the CSS (and likely
javascript)?

On Wed, Jan 13, 2016 at 4:00 PM, Fernandez, Chris <notifications@github.com>
wrote:

> Hello, is exactly the same as this but of course the name of the certs are
> different.
> https://github.com/threatstream/mhn/wiki/Running-MHN-Over-HTTPS
> tls is working, is just the CSS seens like it may still be calling http
> from somewhere. here is a snapshot.
> [image: screenshot_20160113_125902]
> <https://cloud.githubusercontent.com/assets/5316229/12307669/86e994aa-b9f5-11e5-9dc7-463b419314ac.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/229#issuecomment-171430803>.
>



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
sure, here is the result, i'm surprised because I only have changed settings in nginx did not move files around etc.
![screenshot_20160113_133451](https://cloud.githubusercontent.com/assets/5316229/12308545/9cdce46a-b9fa-11e5-888d-4196a76432c0.png)

**Comment by jt6211** [comment]
I've heard from one of our developers that they have seen a similar issue
on another site and it was related to the SSL cert being self signed or
invalid.  This could be the issue given your cert doesn't look valid.

Other item to check.  Does your nginx config contain this block and does
that file path actually exist? And are the permissions such that nginx can
read them?

location  /static {
      alias /opt/mhn/server/mhn/static;
    }


On Wed, Jan 13, 2016 at 4:36 PM, Fernandez, Chris <notifications@github.com>
wrote:

> sure, here is the result, i'm surprised because I only have changed
> settings in nginx did not move files around etc.
> [image: screenshot_20160113_133451]
> <https://cloud.githubusercontent.com/assets/5316229/12308545/9cdce46a-b9fa-11e5-888d-4196a76432c0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/229#issuecomment-171442124>.
>



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
is def self signed, let me check the block, yap you were right there, I think I got the issue. the default wiki points the alias to the /opt folder while I did the install of mhn on my home directory.
ok I test it is working now, getting all the JS stuff and images.
Thanks for the help.
