### ISSUE TITLE
get free tls cert for mhn using letsencript

### ISSUE THREAD

**Issue by ChrisFernandez** [threatstream/mhn#230]
sorry I can't edit the wiki, wanted to put it there. so if someone can here is the link on a howto to do it for nginx, mhn uses nginx and I just added it to my mhn admin server and works like a charm.
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

cheers!
Fernandez Chris.

**Comment by jt6211** [comment]
Thanks Chris. wiki updated.

**Comment by cloughrm** [comment]
Closing this issue, as it appears to have been resolved
