### ISSUE TITLE
Failed Install of MHN

### ISSUE THREAD

**Issue by AJSNetworks** [threatstream/mhn#238]
Hello,
Spun up a Ubuntu 12.04.5 x64 from DO and getting errors from installation script.

Please advise if there is a new updated installation procedure.

Followed instructions and received first error:
<pre>
root@mhn:/opt/# apt-get update
root@mhn:/opt/# apt-get install git
root@mhn:/opt/# git clone https://github.com/threatstream/mhn.git
root@mhn:/opt/# cd mhn
root@mhn:/opt/mhn# ./install.sh 
[Mon Jan 25 11:34:43 EST 2016] Starting Installation of all MHN packages
[Mon Jan 25 11:34:43 EST 2016] ========= Installing hpfeeds =========
+++ readlink -f ./install_hpfeeds.sh
++ dirname /opt/mhn/scripts/install_hpfeeds.sh
+ SCRIPTS=/opt/mhn/scripts
+ MHN_HOME=/opt/mhn/scripts/..
+ '[' -f /etc/debian_version ']'
+ OS=Debian
+ INSTALLER=apt-get
+ REPOPACKAGES='libffi-dev build-essential python-pip python-dev git libssl-dev supervisor'
++ which python
+ PYTHON=/usr/bin/python
++ which pip
+ PIP=
root@mhn:/opt/mhn#
</pre>

Made slight modifications to avoid missing package issue:
<pre>
apt-get install libffi-dev build-essential python-pip python-dev git libssl-dev supervisor
./install
</pre>

Installation starts successfully but about 5 minutes in see a few random issues:
<pre>
+ /opt/hpfeeds/env/bin/pip install GeoIP
Collecting GeoIP
/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading GeoIP-1.3.2.tar.gz
Building wheels for collected packages: GeoIP
  Running setup.py bdist_wheel for GeoIP ... error
  Complete output from command /opt/hpfeeds/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-urbxnV/GeoIP/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpMv_311pip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for GeoIP
  Running setup.py clean for GeoIP
Failed to build GeoIP
</pre>

and

<pre>
building 'pysqlite2._sqlite' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -Ish: -I1: -Ipkg-config: -Inot -Ifound -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
  In file included from src/module.c:24:0:
  src/connection.h:33:21: fatal error: sqlite3.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pysqlite
  Running setup.py clean for pysqlite
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for blinker ... done
  Stored in directory: /root/.cache/pip/wheels/f2/c3/e5/ee0b56ce61cac874efcee8d98a9a9e9415cb8e229cde993c7f
  Running setup.py bdist_wheel for alembic ... done
  Stored in directory: /root/.cache/pip/wheels/97/1b/9e/d5de8ded6091e30dc43e345f7b38be025ff5ec200ad7c87b79
  Running setup.py bdist_wheel for Flask-Script ... done
  Stored in directory: /root/.cache/pip/wheels/42/85/3d/fca6d4a04f7852ce8322be36ff8918ceff9bce568e7144c813
  Running setup.py bdist_wheel for SQLAlchemy ... done
  Stored in directory: /root/.cache/pip/wheels/56/75/7a/d0a2571fed74e00b0cf2678b4dd7924caa90ae306349c12ecb
  Running setup.py bdist_wheel for Flask-Principal ... done
  Stored in directory: /root/.cache/pip/wheels/19/e8/b8/0c02bed1e07ab83bb911a8644c18ee0972c96b47eba0aad1b0
  Running setup.py bdist_wheel for WTForms ... done
  Stored in directory: /root/.cache/pip/wheels/06/b6/4a/6dae35583a348364dbdcc36ac0b742e05d698acee1010bcf5c
  Running setup.py bdist_wheel for billiard ... done
  Stored in directory: /root/.cache/pip/wheels/f2/75/4e/fef459428cb93c4e47d6d624e4341edb030bef6a54f4d2b17b
  Running setup.py bdist_wheel for Mako ... done
  Stored in directory: /root/.cache/pip/wheels/41/c3/cb/921697f388fa8b0bb5462324d47dc4a62b28186d39a171cb00
  Running setup.py bdist_wheel for python-editor ... done
  Stored in directory: /root/.cache/pip/wheels/1c/92/b9/20a176d34724afeaff19be6dbd57c19e4084047fb1c3a4f76c
  Running setup.py bdist_wheel for anyjson ... done
  Stored in directory: /root/.cache/pip/wheels/3d/9e/de/9bd4afad0b092b039d7b6414f34a1350c53f0bc15fa6bf0647
Successfully built Flask Flask-Login Flask-Mail Flask-Migrate Flask-SQLAlchemy Flask-Security Flask-Testing py-bcrypt python-dateutil redis xmltodict uWSGI hpfeeds-threatstream pygal hpfeeds-logger GeoIP itsdangerous blinker alembic Flask-Script SQLAlchemy Flask-Principal WTForms billiard Mako python-editor anyjson
Failed to build pysqlite
</pre>

and then finally...

<pre>
Running setup.py install for pysqlite ... error
    Complete output from command /opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qJzi7d/pysqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tHSten-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python2.7/pysqlite:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2
    copying lib/dbapi2.py -> build/lib.linux-x86_64-2.7/pysqlite2
    creating build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/dump.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/types.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/userfunctions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/dbapi.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/factory.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/transactions.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/__init__.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/hooks.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    copying lib/test/regression.py -> build/lib.linux-x86_64-2.7/pysqlite2/test
    running build_ext
    building 'pysqlite2._sqlite' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -Ish: -I1: -Ipkg-config: -Inot -Ifound -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
    In file included from src/module.c:24:0:
    src/connection.h:33:21: fatal error: sqlite3.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qJzi7d/pysqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tHSten-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python2.7/pysqlite" failed with error code 1 in /tmp/pip-build-qJzi7d/pysqlite
root@mhn:/opt/mhn# 
</pre>

**Comment by jt6211** [comment]
The MHN install script is slightly broken at the moment. I am working on a
fix now.

On Mon, Jan 25, 2016 at 11:55 AM, AJSNetworks <notifications@github.com>
wrote:

> Hello,
> Spun up a Ubuntu 12045 x64 from DO and getting errors from installation
> script
>
> Please advise if there is a new updated installation procedure
>
> Followed instructions and received first error:
>
> root@mhn:/opt/# apt-get update
> root@mhn:/opt/# apt-get install git
> root@mhn:/opt/# git clone https://githubcom/threatstream/mhngit
> root@mhn:/opt/# cd mhn
> root@mhn:/opt/mhn# /installsh
> [Mon Jan 25 11:34:43 EST 2016] Starting Installation of all MHN packages
> [Mon Jan 25 11:34:43 EST 2016] ========= Installing hpfeeds =========
> +++ readlink -f /install_hpfeedssh
> ++ dirname /opt/mhn/scripts/install_hpfeedssh
> + SCRIPTS=/opt/mhn/scripts
> + MHN_HOME=/opt/mhn/scripts/
> + '[' -f /etc/debian_version ']'
> + OS=Debian
> + INSTALLER=apt-get
> + REPOPACKAGES='libffi-dev build-essential python-pip python-dev git libssl-dev supervisor'
> ++ which python
> + PYTHON=/usr/bin/python
> ++ which pip
> + PIP=
> root@mhn:/opt/mhn#
>
> Made slight modifications to avoid missing package issue:
>
> apt-get install libffi-dev build-essential python-pip python-dev git libssl-dev supervisor
> /install
>
> Installation starts successfully but about 5 minutes in see a few random
> issues:
>
> + /opt/hpfeeds/env/bin/pip install GeoIP
> Collecting GeoIP
> /opt/hpfeeds/env/local/lib/python27/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform This may cause the server to present an incorrect TLS certificate, which can cause validation failures For more information, see https://urllib3readthedocsorg/en/latest/securityhtml#snimissingwarning
>   SNIMissingWarning
> /opt/hpfeeds/env/local/lib/python27/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_py:120: InsecurePlatformWarning: A true SSLContext object is not available This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail For more information, see https://urllib3readthedocsorg/en/latest/securityhtml#insecureplatformwarning
>   InsecurePlatformWarning
>   Downloading GeoIP-132targz
> Building wheels for collected packages: GeoIP
>   Running setuppy bdist_wheel for GeoIP  error
>   Complete output from command /opt/hpfeeds/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-urbxnV/GeoIP/setuppy';exec(compile(getattr(tokenize, 'open', open)(__file__)read()replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpMv_311pip-wheel- --python-tag cp27:
>   /usr/lib/python27/distutils/distpy:267: UserWarning: Unknown distribution option: 'bugtrack_url'
>     warningswarn(msg)
>   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ]
>      or: -c --help [cmd1 cmd2 ]
>      or: -c --help-commands
>      or: -c cmd --help
>
>   error: invalid command 'bdist_wheel'
>
>   ----------------------------------------
>   Failed building wheel for GeoIP
>   Running setuppy clean for GeoIP
> Failed to build GeoIP
>
> and
>
> building 'pysqlite2_sqlite' extension
>   creating build/templinux-x86_64-27
>   creating build/templinux-x86_64-27/src
>   gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2dbapi2" -Ish: -I1: -Ipkg-config: -Inot -Ifound -I/usr/include/python27 -c src/modulec -o build/templinux-x86_64-27/src/moduleo
>   In file included from src/modulec:24:0:
>   src/connectionh:33:21: fatal error: sqlite3h: No such file or directory
>   compilation terminated
>   error: command 'gcc' failed with exit status 1
>
>   ----------------------------------------
>   Failed building wheel for pysqlite
>   Running setuppy clean for pysqlite
>   Running setuppy bdist_wheel for itsdangerous  done
>   Stored in directory: /root/cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
>   Running setuppy bdist_wheel for blinker  done
>   Stored in directory: /root/cache/pip/wheels/f2/c3/e5/ee0b56ce61cac874efcee8d98a9a9e9415cb8e229cde993c7f
>   Running setuppy bdist_wheel for alembic  done
>   Stored in directory: /root/cache/pip/wheels/97/1b/9e/d5de8ded6091e30dc43e345f7b38be025ff5ec200ad7c87b79
>   Running setuppy bdist_wheel for Flask-Script  done
>   Stored in directory: /root/cache/pip/wheels/42/85/3d/fca6d4a04f7852ce8322be36ff8918ceff9bce568e7144c813
>   Running setuppy bdist_wheel for SQLAlchemy  done
>   Stored in directory: /root/cache/pip/wheels/56/75/7a/d0a2571fed74e00b0cf2678b4dd7924caa90ae306349c12ecb
>   Running setuppy bdist_wheel for Flask-Principal  done
>   Stored in directory: /root/cache/pip/wheels/19/e8/b8/0c02bed1e07ab83bb911a8644c18ee0972c96b47eba0aad1b0
>   Running setuppy bdist_wheel for WTForms  done
>   Stored in directory: /root/cache/pip/wheels/06/b6/4a/6dae35583a348364dbdcc36ac0b742e05d698acee1010bcf5c
>   Running setuppy bdist_wheel for billiard  done
>   Stored in directory: /root/cache/pip/wheels/f2/75/4e/fef459428cb93c4e47d6d624e4341edb030bef6a54f4d2b17b
>   Running setuppy bdist_wheel for Mako  done
>   Stored in directory: /root/cache/pip/wheels/41/c3/cb/921697f388fa8b0bb5462324d47dc4a62b28186d39a171cb00
>   Running setuppy bdist_wheel for python-editor  done
>   Stored in directory: /root/cache/pip/wheels/1c/92/b9/20a176d34724afeaff19be6dbd57c19e4084047fb1c3a4f76c
>   Running setuppy bdist_wheel for anyjson  done
>   Stored in directory: /root/cache/pip/wheels/3d/9e/de/9bd4afad0b092b039d7b6414f34a1350c53f0bc15fa6bf0647
> Successfully built Flask Flask-Login Flask-Mail Flask-Migrate Flask-SQLAlchemy Flask-Security Flask-Testing py-bcrypt python-dateutil redis xmltodict uWSGI hpfeeds-threatstream pygal hpfeeds-logger GeoIP itsdangerous blinker alembic Flask-Script SQLAlchemy Flask-Principal WTForms billiard Mako python-editor anyjson
> Failed to build pysqlite
>
> and then finally
>
> Running setuppy install for pysqlite  error
>     Complete output from command /opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qJzi7d/pysqlite/setuppy';exec(compile(getattr(tokenize, 'open', open)(__file__)read()replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tHSten-record/install-recordtxt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python27/pysqlite:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/liblinux-x86_64-27
>     creating build/liblinux-x86_64-27/pysqlite2
>     copying lib/dumppy -> build/liblinux-x86_64-27/pysqlite2
>     copying lib/__init__py -> build/liblinux-x86_64-27/pysqlite2
>     copying lib/dbapi2py -> build/liblinux-x86_64-27/pysqlite2
>     creating build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/dumppy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/typespy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/userfunctionspy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/dbapipy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/factorypy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/transactionspy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/__init__py -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/hookspy -> build/liblinux-x86_64-27/pysqlite2/test
>     copying lib/test/regressionpy -> build/liblinux-x86_64-27/pysqlite2/test
>     running build_ext
>     building 'pysqlite2_sqlite' extension
>     creating build/templinux-x86_64-27
>     creating build/templinux-x86_64-27/src
>     gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlite2dbapi2" -Ish: -I1: -Ipkg-config: -Inot -Ifound -I/usr/include/python27 -c src/modulec -o build/templinux-x86_64-27/src/moduleo
>     In file included from src/modulec:24:0:
>     src/connectionh:33:21: fatal error: sqlite3h: No such file or directory
>     compilation terminated
>     error: command 'gcc' failed with exit status 1
>
>     ----------------------------------------
> Command "/opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qJzi7d/pysqlite/setuppy';exec(compile(getattr(tokenize, 'open', open)(__file__)read()replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tHSten-record/install-recordtxt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python27/pysqlite" failed with error code 1 in /tmp/pip-build-qJzi7d/pysqlite
> root@mhn:/opt/mhn#
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/238>.
>



-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by AJSNetworks** [comment]
Saw a bunch of commits and tried re-installing again. Success.

Did have to adjust permission on log file though:

cd /var/log/mhn/
sudo chown www-data mhn.log
sudo supervisorctl start mhn-celery-worker

Thanks for the fix!
