### ISSUE TITLE
honeymap diff?

### ISSUE THREAD

**Issue by ChrisFernandez** [threatstream/mhn#242]
Hello when I go to github and check on the main honeymap git repo and even in the fork under threatstream I see no "**honeymap.js**" apparently the one in the github repos use coffeescript for the front end and golang for the back.. in the recent install I did of MHN it installs that files and apart of that also a** honeymap.js** also seens like is actually using this .js file instead of the coffeescript .... I was about to modify it and notice all this.. what should I modify? and why is this using still the .js instead of the coffeescript ones?

**Comment by jt6211** [comment]
Modify the coffee script file. The JavaScript file is the output from
compiling the coffee script

On Sunday, February 21, 2016, Fernandez, Chris <notifications@github.com>
wrote:

> Hello when I go to github and check on the main honeymap git repo and even
> in the fork under threatstream I see no "*honeymap.js*" apparently the
> one in the github repos use coffeescript for the front end and golang for
> the back.. in the recent install I did of MHN it installs that files and
> apart of that also a** honeymap.js** also seens like is actually using this
> .js file instead of the coffeescript .... I was about to modify it and
> notice all this.. what should I modify? and why is this using still the .js
> instead of the coffeescript ones?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/242>.
>


-- 
Jason Trost | VP of Threat Research | www.threatstream.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
ahhh ok that makes total sense now. thanks
