### ISSUE TITLE
mhn-celery-worker 

### ISSUE THREAD

**Issue by boxrice007** [threatstream/mhn#243]
# mhn-celery-worker is fatal
## As follows：

supervisorctl status
geoloc                           RUNNING    pid 30171, uptime 5:21:01
honeymap                         RUNNING    pid 4180, uptime 1:38:23
hpfeeds-broker                   RUNNING    pid 10591, uptime 5:31:13
hpfeeds-logger-splunk            RUNNING    pid 14010, uptime 0:38:14
mhn-celery-beat                  RUNNING    pid 13707, uptime 0:53:42
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)
mhn-collector                    RUNNING    pid 13709, uptime 0:53:42
mhn-uwsgi                        RUNNING    pid 13710, uptime 0:53:42
mnemosyne                        RUNNING    pid 28472, uptime 5:22:52
## mhn-celery-worker.err as follows:

supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
##

**Comment by Waseem-farooqui** [comment]
In my case just change the ownership of the **mhn log file** located at `/var/log/mhn/mhn.log`.
run the command `chown www-data /var/log/mhn/mhn.log`
Than start the **mhn-celery-worker** process by `sudo supervisorctl start mhn-celery-worker`

**Comment by Antelox** [comment]
I think this can be closed! =)

**Comment by B00100790** [comment]
still won't spawn even with chown changed

**Comment by d1str0** [comment]
@B00100790 please try again with the latest code. If you're still having issues, provide OS, and system details.

**Comment by HollywoodMarks** [comment]
Issue is present on latest code.  OS: Ubuntu 16.04   .  Ran with sudo permissions.  Server is a VM.
Error: Permission denied 'var/log/mhn/mhn.log'
Fixed by doing the same as above.  
$ sudo chown www-data:www-data /var/log/mhn/mhn.log
$ sudo /etc/init.d/supervisor restart

**Comment by IJBrowny** [comment]
Its actually work though I went into mhn log file located at /var/log/mhn/mhn.log
then run this command  chown www-data /var/log/mhn/mhn.log
then I start the mhn-celery-worker process by sudo supervisorctl start mhn-celery-worker
