### ISSUE TITLE
deploying problems

### ISSUE THREAD

**Issue by digokos** [threatstream/mhn#249]
Does any one know how to deploy a honeypot with MHN if the server stands on zpanel/sentora or webmin or any one of the WebControlPanels out there with multi websites and users?

**Comment by d1str0** [comment]
This is most likely not possible unless you have all of your honeypot code written in a web language supported by that shared server. Check out https://github.com/threatstream/mhn/wiki/Howto%3A-Add-Support-for-New-Sensors-to-the-MHN
