### ISSUE TITLE
Install scripts terminate if having multiple pip versions. 

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/mhn#254]
While running the install script on **ubuntu 14.04** the install script `install_hpfeeds.sh` gives error at this place 

```
apt-get -y install libffi-dev build-essential python-pip python-dev git libssl-dev supervisor

    PYTHON=`which python`
    PIP=`which pip`
    $PIP install virtualenv
    VIRTUALENV=`which virtualenv
```

If I am having multiple versions of `pip` install like in my case I was having pip,pip2, pip3 and pip3.4 all were in `/usr/local/bin/` the command became `/usr/local/bin/pip install virtualenv` was working fine with _pip2_ but not working with _pip3_ and terminates the script with the `ImportError: No module named pip` error which means my default was _pip3_ and this command not works with _pip3_ the same issue is over here https://github.com/pypa/pip/issues/1918.
I think this issue should be handled in the script.

**Comment by jt6211** [comment]
Did you modify the install script to use pip2/pip3?  Or this fails without
modification?

On Fri, Apr 1, 2016 at 1:03 AM, Waseem ud din <notifications@github.com>
wrote:

> While running the install script on *ubuntu 14.04* the install script
> install_hpfeeds.sh gives error at this place
>
> apt-get -y install libffi-dev build-essential python-pip python-dev git libssl-dev supervisor
>
>     PYTHON=`which python`
>     PIP=`which pip`
>     $PIP install virtualenv
>     VIRTUALENV=`which virtualenv
>
> If I am having multiple versions of pip install like in my case I was
> having pip,pip2, pip3 and pip3.4 all were in /usr/local/bin/ the command
> became /usr/local/bin/pip install virtualenv was working fine with *pip2*
> but not working with *pip3* and terminates the script with the ImportError:
> No module named pip error which means my default was *pip3* and this
> command not works with *pip3* the same issue is over here pypa/pip#1918
> <https://github.com/pypa/pip/issues/1918>.
> I think this issue should be handled in the script.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/254>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Waseem-farooqui** [comment]
No, it use the default pip which was in my case pip3

**Comment by jt6211** [comment]
we are open to pull requests that would address this. We haven't had anyone else with these issues so far.
