### ISSUE TITLE
http://@192.168.1.201/api/script/?text=true: invalid username 

### ISSUE THREAD

**Issue by jacmor01** [threatstream/mhn#255]
Hi, 

I've got two Ubuntu 14.04 VM's one is the MHN server and one is the one I want to deploy kippo onto.
I've copied the files across to the server and completed the installation but when I get the deploy script from the website and try to run it I get the following error: 

http://@192.168.1.201/api/script/?text=true: invalid username.
-0 command not found. 

Anyone know what's going wrong?

Thanks 
Jack

**Comment by jt6211** [comment]
It kind of looks like you didn't paste the full command before running it.
The full deploy command should look something like this (SECRET_KEY
replaced and the script_id may be different):

wget "https://192.168.1.201/api/script/?text=true&script_id=17" -O
deploy.sh && sudo bash deploy.sh https://192.168.1.201 SECRET_KEY

On Sat, Apr 2, 2016 at 5:38 PM, jacmor01 <notifications@github.com> wrote:

> Hi,
>
> I've got two Ubuntu 14.04 VM's one is the MHN server and one is the one I
> want to deploy kippo onto.
> I've copied the files across to the server and completed the installation
> but when I get the deploy script from the website and try to run it I get
> the following error:
>
> http://@192.168.1.201/api/script/?text=true: invalid username.
> -0 command not found.
>
> Anyone know what's going wrong?
>
> Thanks
> Jack
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/255>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by jacmor01** [comment]
Ok, I really hope that's the case, just reinstalling my VM and I shall reinstall the scripts etc 
great piece of software otherwise! Had it working with a pi before :)

**Comment by jacmor01** [comment]
Hi, 

Thanks for the help - it's successfully installed kippo to the honeypot. For some reason it didn't have " marks around the URL, :)
