### ISSUE TITLE
honeymaps only shows data from western countries dst's

### ISSUE THREAD

**Issue by ChrisFernandez** [threatstream/mhn#256]
I been trying to figure out the issue for like 2 months... I thought all this time I was doing something wrong.. but no.. I install the same pots in servers in Europe or North America and they just work.. but when I install a pot on AWS in south America or Asia... even do I do get data into mhn is not showing up at all on the honeymaps web map.... any idea?  first I though.. maybe im just configuring it wrong... but no.. I have copy a AWS IMG and launch it on tokyo... and no.. even do I do get data it will NEVER show up on honeynet web UI...of course I did change all the local host info.. i been banging my head to the wall for a month because of this.. but it got to the point im like.. WTF  something else is wrong here.
update: I open my map so you guys can see for yourself... I have a pot in San Paulo, BR. Singapure and Tokyo... not a single show in the map.. while I do get the attacks on the main mhn ui recorded so data is coming in.
here is the map https://pot.hispagatos.org:8443/

**Comment by jjjan** [comment]
Hello Chris,
may i know how to make a vector from attacker(red dot) to honeypot?
thx

**Comment by ChrisFernandez** [comment]
yeah feel free to fork from my fork, I have submitted the code to upstream to the honeymap people but is been sitting there for 2-3  weeks. https://github.com/ChrisFernandez/honeymap

**Comment by jjjan** [comment]
thx indeed

**Comment by jjjan** [comment]
thx i should install piwik in backgrand ? could you explain more. cause i read code and find out need to install it.

**Comment by jjjan** [comment]
about your question as my experience when the VPS is under NAT or any firewall or IPS the information not shown in map.

**Comment by ChrisFernandez** [comment]
@jjjan no you can strip the JS for piwik,  there I have setup iptables etc but all the ips of my pots are there.. all have same configuration.. I even see data come into the admin interface attacks and sensors list, but is JUST on the map that it does not shows... very very very odd. hopefully someone can point me in the right direction to were to look.
![screenshot_20160409_191144](https://cloud.githubusercontent.com/assets/5316229/14407673/3f33316c-fe87-11e5-9cd9-d4b072812465.png)

**Comment by jt6211** [comment]
Here's how I recommend troubleshooting this:

1. use one of the scripts that comes from hpfeeds to verify that the events
you're expecting from the non western countries are 1) coming through AND
2) have the correct IP in the record that is geolocatable (
https://github.com/threatstream/hpfeeds/tree/master/examples).
2. review the
https://github.com/threatstream/hpfeeds/tree/master/examples/geoloc code to
make sure that the events you're sending are actually geolocatable and will
be picked up correctly.
3. use one of the scripts that comes from hpfeeds to verify that the events
you're expecting from the non western countries are being enriched with IP
geo (or not) and then being sent to the channel that honeymap listens on.
4. Use google developer tools in Chrome to view the events come to your
browser and see if there are any errors with rendering the events.  See
this https://github.com/threatstream/mhn/issues/54

I hope this helps.

On Sat, Apr 9, 2016 at 10:14 PM, Fernandez, Chris, ReK2 <
notifications@github.com> wrote:

> @jjjan <https://github.com/jjjan> no you can strip the JS for piwik,
> there I have setup iptables etc but all the ips of my pots are there.. all
> have same configuration.. I even see data come into the admin interface
> attacks and sensors list, but is JUST on the map that it does not shows...
> very very very odd. hopefully someone can point me in the right direction
> to were to look.
> [image: screenshot_20160409_191144]
> <https://cloud.githubusercontent.com/assets/5316229/14407673/3f33316c-fe87-11e5-9cd9-d4b072812465.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/256#issuecomment-207898083>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
ok so you are right... is issue 54 for seems like it does has the issue with more places..

I am using this [https://github.com/threatstream/mhn/wiki/Customizing-Maxmind-IP-Geo-DB-for-Internal-Networks](url) method to see inside the files: 
so I can probe with:

```
head GeoLiteCity-flat.csv 
16777216,16777471,AU,,,,-27.0000,133.0000,,
16777472,16778239,CN,07,Fuzhou,,26.0614,119.3061,,
16778240,16779263,AU,,,,-27.0000,133.0000,,
16779264,16781311,CN,30,Guangzhou,,23.1167,113.2500,,
16781312,16785407,JP,40,Tokyo,100-0001,35.6850,139.7514,,
16785408,16793599,CN,30,Guangzhou,,23.1167,113.2500,,
16793600,16799231,JP,11,Hiroshima,730-0011,34.3963,132.4594,,
16799232,16799487,JP,36,Matsue,690-0887,35.4722,133.0506,,
16799488,16799743,JP,45,Hofu,747-0801,34.0500,131.5667,,
16799744,16800511,JP,11,Hiroshima,730-0011,34.3963,132.4594,,
(env)root@bladerunner:~/mmutils# cat GeoLiteCity-flat.csv | grep Singapur
(env)root@bladerunner:~/mmutils# cat GeoLiteCity-flat.csv | grep Singapur
```

so I think I am just going to manually add the cities Im missing and as that howto mentions feed it back to MHN... 

but my question.. can we use another Database were is more complete ?

Thanks!!!

**Comment by jt6211** [comment]
Do you know of a source that is more complete (and as performant as
Maxmind's local DB lookups)?

On Tue, Apr 12, 2016 at 3:51 PM, Fernandez, Chris, ReK2 <
notifications@github.com> wrote:

> ok so you are right... is issue 54 for seems like it does has the issue
> with more places..
>
> I am using this
> https://github.com/threatstream/mhn/wiki/Customizing-Maxmind-IP-Geo-DB-for-Internal-Networks
> <http://url> method to see inside the files:
> so I can probe with:
>
> head GeoLiteCity-flat.csv
> 16777216,16777471,AU,,,,-27.0000,133.0000,,
> 16777472,16778239,CN,07,Fuzhou,,26.0614,119.3061,,
> 16778240,16779263,AU,,,,-27.0000,133.0000,,
> 16779264,16781311,CN,30,Guangzhou,,23.1167,113.2500,,
> 16781312,16785407,JP,40,Tokyo,100-0001,35.6850,139.7514,,
> 16785408,16793599,CN,30,Guangzhou,,23.1167,113.2500,,
> 16793600,16799231,JP,11,Hiroshima,730-0011,34.3963,132.4594,,
> 16799232,16799487,JP,36,Matsue,690-0887,35.4722,133.0506,,
> 16799488,16799743,JP,45,Hofu,747-0801,34.0500,131.5667,,
> 16799744,16800511,JP,11,Hiroshima,730-0011,34.3963,132.4594,,
> (env)root@bladerunner:~/mmutils# cat GeoLiteCity-flat.csv | grep Singapur
> (env)root@bladerunner:~/mmutils# cat GeoLiteCity-flat.csv | grep Singapur
>
> so I think I am just going to manually add the cities Im missing and as
> that howto mentions feed it back to MHN...
>
> but my question.. can we use another Database were is more complete ?
>
> Thanks!!!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/256#issuecomment-209076827>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by ChrisFernandez** [comment]
no idea... I did a search online and notice the latest .csv files they have does Include San Paulo and more cities.. so going to try to compile that and feed it to my mhn setup and let you know.

**Comment by ChrisFernandez** [comment]
ok this is something odd too... now.. this is the first time I deal with this type of databases...
but I get the new version...
unzip etc


then I go into the GeoLiteCity_20160412 folder and run:
```
~/mmutils/GeoLiteCity_20160412# grep -r "San Paulo"
GeoLiteCity-Location.csv:48821,"BR","27","San Paulo","",-23.5333,-46.6167,,
```
ok so good.. it has San Paulo.... so I continue..

`../csv2dat.py -l GeoLiteCity-Location.csv flat GeoLiteCity-Blocks.csv > flatcity.csv`

so I get the resulting file flatcity

and for my surprise:
`cat flatcity.csv | grep "San Paulo"`

no result!!! lol...
why is loosing the information? LOL

**Comment by ChrisFernandez** [comment]
ok so seems like what happens is that the block file is missing the block for this cities...
check the format:

```
/mmutils/GeoLiteCity_20160412# tail GeoLiteCity-Location.csv 
782350,"RU","47","Moscow","101700",55.7522,37.6156,,
782351,"IT","07","Rome","03100",41.6376,13.3354,,
782352,"DK","21","Kolding","6640",55.4838,9.2992,,
782353,"RU","48","Moskva","101700",55.7522,37.6156,,
782354,"UA","23","Zhdanovka","",49.6217,27.8987,,
782355,"NL","16","Lelystad","8226 da",52.5083,5.4750,,
782356,"IT","18","Milan","20126",45.4667,9.2000,,
782357,"US","NJ","West Atlantic City","08232",39.3779,-74.4893,504,609
782358,"IN","36","Benda","",25.6630,79.0221,,
782359,"IN","34","Lalganj","733201",25.8667,85.1833,,
(env)root@bladerunner:~/mmutils/GeoLiteCity_20160412# tail GeoLiteCity-Blocks.csv 
"3758091008","3758091263","17"
"3758091264","3758092287","14431"
"3758092288","3758093311","94"
"3758093312","3758093567","103"
"3758093568","3758093823","537809"
"3758093824","3758094335","103"
"3758094336","3758095359","94"
"3758095360","3758095871","104084"
"3758095872","3758096127","191"
"3758096128","3758096383","17"
(env)root@bladerunner:~/mmutils/GeoLiteCity_20160412# tail flatcity.csv 
3758091008,3758091263,AU,,,,-27.0000,133.0000,,
3758091264,3758092287,CN,23,Shanghai,,31.0456,121.3997,,
3758092288,3758093311,HK,,,,22.2500,114.1667,,
3758093312,3758093567,IN,,,,20.0000,77.0000,,
3758093568,3758093823,IN,09,Gondal,360311,21.9667,70.8000,,
3758093824,3758094335,IN,,,,20.0000,77.0000,,
3758094336,3758095359,HK,,,,22.2500,114.1667,,
3758095360,3758095871,CN,07,Fuzhou,,26.0614,119.3061,,
3758095872,3758096127,SG,,,,1.3667,103.8000,,
3758096128,3758096383,AU,,,,-27.0000,133.0000,,
```

when we flat both files it only adds to the resulting file the data that is on both files.. this is why is missing some cities even do they are in the city csv.

**Comment by ChrisFernandez** [comment]
ok well in the mean time a solution will be for people to add their ip's and cities where they have their honeypots just as the same as adding private/internal data... is a hack but should work.

**Comment by ChrisFernandez** [comment]
Hello ok well turn out that because of the console char encoding i was missing San Paulo, but when I put it here https://www.iplocation.net/  is there... I can't confirm is in the one MHN is using.. in any case I have put this latest version.. and I am still having the same issue... so has to be something else. Ill go over the actually data sent from the honeypots.. but I do not think is that because, Im running the same type of honeypots on all cities.. so the data should be the same.. only difference is the city/country/Geo info.
