### ISSUE TITLE
map working but no attackers shown

### ISSUE THREAD

**Issue by jacmor01** [threatstream/mhn#257]
Hi, 

I think this has been posted before but I couldn't see a solution so was wondering if anyone could help me. I've had a couple attacks from china which is showing in my statistic etc but isn't showing on the map. 
The map loads ok but there are no red dots or yellow dots. 
It's an internet facing honeypot as the ports have been forwarded properly. 
Any ideas what could be amiss?

Many thanks, 
Jack

**Comment by Waseem-farooqui** [comment]
Firstly honeymap only displays real time attacks.
If its not displaying it than check the `Honeymap` and `geoloc` service from terminal.
`sudo supervisorctl status`

**Comment by jacmor01** [comment]
Damn, it would be great to see these attacks plotted on a map if there was a way. 
Both services are running properly, so I guess it's working as it should?

**Comment by Waseem-farooqui** [comment]
yes, Its working than.
just **nmap** your honeypot ip you will see the red and yellow dot.
