### ISSUE TITLE
Issue with using mhn with Pi2

### ISSUE THREAD

**Issue by MatthewHKnight** [threatstream/mhn#263]
So, I'm not 100% sure if I followed the correct guide on setting this up on a Raspberry Pi2 But I ran the install.sh shortly after I get this error any fix? Or am I setting this up on the Pi wrong?
![screen shot 2016-04-24 at 11 10 39 am](https://cloud.githubusercontent.com/assets/11364609/14768332/41a4985a-0a0d-11e6-857f-b1204a455583.png)

**Comment by digital-shokunin** [comment]
Looks like no ARM platform packages exist for mongodb on that repo.
