### ISSUE TITLE
Update the repo links inside glastopf and conpot deployment scripts

### ISSUE THREAD

**Issue by Antelox** [threatstream/mhn#272]
Hi, the deployment scripts for glastopf and conpot honeypots must be updated.

s/glastopf/mushorg

Then IMHO, in glastopf deployment script, I would change 2 things:

- Installation: from "pip" to glastopf's github repo.
- installation of "distribute" package -> sudo pip install --upgrade distribute

**Comment by jt6211** [comment]
Have you tested it?  Can you create a PR for this?

**Comment by Antelox** [comment]
Can be closed.

Ref:
https://github.com/threatstream/mhn/pull/273
https://github.com/threatstream/mhn/pull/274
