### ISSUE TITLE
Cannot access web page. 

### ISSUE THREAD

**Issue by mother2110** [threatstream/mhn#275]
I installed MHN on a Ubuntu 14.04 and I can get to the HoneyMap fine but not the login page. I just get a Welcome to nginx. Also I noticed that the mhn-celery-beat/worker and mhn-collector is not showing up.

root@honeyserver:/var/log/mhn# supervisorctl status
geoloc                           FATAL      Exited too quickly (process log may have details)
honeymap                         RUNNING    pid 1309, uptime 0:05:45
hpfeeds-broker                   RUNNING    pid 1310, uptime 0:05:45
mnemosyne                        RUNNING    pid 1587, uptime 0:00:44
root@honeyserver:/var/log/mhn#

**Comment by Antelox** [comment]
I think that something during installation gone wrong... Try to re-execute installation process.

**Comment by d1str0** [comment]
Please try again with latest code if this is still an issue.
