### ISSUE TITLE
Getting Great Data - Can't Get PCAPs/binaries

### ISSUE THREAD

**Issue by riparino** [threatstream/mhn#276]
Hi all - new to MHN but not unfamiliar with pot insfrastructures. I'm wondering if anyone has found a lightweight way to pull pcaps and/or binary payloads. I know it's a feature being worked on in another issue but does anyone have a workaround until we have a drilldown on the MHN Server?

**Comment by Waseem-farooqui** [comment]
Have you deployed any honeypot or any PCAP util for getting payload or pcap ?

**Comment by riparino** [comment]
I think that's really the meat of what I'm trying to get to. I've got a standard dionea + kippo + snort + p0f node running - plenty of attacks on it, plenty of payload data. I'm just trying to find out if snort is running in monitor mode or log mode and if I am able to extract pcaps, also from dionea I should be able to pull binary payloads. I'm just not sure if there is an easy way to do it or if there are any guides for achieving these functions.

**Comment by sh4t** [comment]
@riparino for the binary data you're looking for; check your mongodb collection, from within your mongo client:

`db.getCollection('file').find({})`

```
/* 1 */
{
    "_id" : ObjectId("56bdc529f1dc4fd74e99be17"),
    "hashes" : {
        "sha1" : "d43f120c5d22134de68d5cac90ee0d19641aecb4",
        "sha512" : "1a5f2e785a88a4c811322db75d216cacde556c2ea37d38a7f558e25721f749e40d447c5f195e8dae2e510472980d1f62fadcb5622a680bb5014306a847946f8b",
        "md5" : "d45e70c5209bd8d5ab33890244bb515f"
    },
    "data" : "[redacted due to size]",
    "content_guess" : "data",
    "encoding" : "hex",
    "hpfeed_ids" : [ 
        ObjectId("56bdc529e5645d58a284eb85")
    ]
}

/* 2 */
{
    "_id" : ObjectId("56bdc5d5f1dc4fd74e99be27"),
    "hashes" : {
        "sha1" : "cb612188896839f00258579cba612164bf31a785",
        "sha512" : "712b78c070d0405c75ab95b4f75c2a9d3f57da769a43d8a62d7dda9007fc64d3acf771889e9aba56c17b712a585ec5b5a6be900c29699f444b5e6d80fead2e6a",
        "md5" : "417dc43d2f8d22bdabf03c846c249e8e"
    },
    "data" : "[redacted due to size]",
    "content_guess" : "data",
    "encoding" : "hex",
    "hpfeed_ids" : [ 
        ObjectId("56bdc5d4e5645d58a284f203")
    ]
}
```

**Comment by sh4t** [comment]
@riparino I have not checked myself if `output log_tcpdump: tcpdump.log` is used within the snort that ships/used by MHN itself; though logging pcaps could get a bit hairy in terms of overall size..

What data/detail are you wanting from the pcap? Session details for the connection?  Might be some other options available here.
