### ISSUE TITLE
Update "Migrating MHN to a new Box" wiki page

### ISSUE THREAD

**Issue by Antelox** [threatstream/mhn#277]
I would replace in the last line _mongoimport_ with _mongorestore_ since we use **mongodump** to dump the MHN's mongo dbs.

Then I would add another point (last one) on which can be specified that must be replaced hpfeeds host ip in every sensors deployed through old box with the IP of the new one.

**Comment by d1str0** [comment]
Added the reconfigure bit. Not sure about mongoimport vs. restore but as we move forward we will try and update and improve the wiki as needed.
