### ISSUE TITLE
Python ValueError

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#278]
Error:
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l75ZwH/pyev/setup.py", line 56, in <module>
        check_version(python_version, min_python_versions[major], "Python{0}".format(major))
      File "/tmp/pip-build-l75ZwH/pyev/setup.py", line 40, in check_version
        if StrictVersion(current_version) < StrictVersion(minimum_version):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in **init**
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '2.7.11+'

I don't know what's wrong.Please help me.

**Comment by jt6211** [comment]
What OS and version?

What were you doing when you saw this error? And can you send the
surrounding log messages

On Saturday, May 21, 2016, Dreamwhite <notifications@github.com> wrote:

> Error:
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-build-l75ZwH/pyev/setup.py", line 56, in
> check_version(python_version, min_python_versions[major],
> "Python{0}".format(major))
> File "/tmp/pip-build-l75ZwH/pyev/setup.py", line 40, in check_version
> if StrictVersion(current_version) < StrictVersion(minimum_version):
> File "/usr/lib/python2.7/distutils/version.py", line 40, in *init*
> self.parse(vstring)
> File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
> raise ValueError, "invalid version number '%s'" % vstring
> ValueError: invalid version number '2.7.11+'
>
> I don't know what's wrong.Please help me.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/278>
>


-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Dreamwhite** [comment]
OS:Kali Linux(4.5.0-kali1-amd64)

When I executed the "install.sh" script,it occured this error.

Below is the log info:

+ pip install -e git+https://github.com/rep/evnet.git#egg=evnet-dev
Obtaining evnet from git+https://github.com/rep/evnet.git#egg=evnet-dev
Collecting pyev>=0.5.3-3.8 (from evnet)
  Using cached pyev-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qguU_e/pyev/setup.py", line 56, in <module>
        check_version(python_version, min_python_versions[major], "Python{0}".format(major))
      File "/tmp/pip-build-qguU_e/pyev/setup.py", line 40, in check_version
        if StrictVersion(current_version) < StrictVersion(minimum_version):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '2.7.11+'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qguU_e/pyev/

**Comment by jt6211** [comment]
We had another user via the mailing list and they solved this by
downgrading to Ubuntu 14. MHN isn't supported on this version of Kali yet.

On Wed, May 25, 2016 at 4:42 AM, Dreamwhite <notifications@github.com>
wrote:

> OS:Kali Linux(4.5.0-kali1-amd64)
>
> When I executed the "install.sh" script,it occured this error.
>
> Below is the log info:
>
>    -
>
>    pip install -e git+https://github.com/rep/evnet.git#egg=evnet-dev
>    Obtaining evnet from git+https://github.com/rep/evnet.git#egg=evnet-dev
>    Collecting pyev>=0.5.3-3.8 (from evnet)
>    Using cached pyev-0.9.0.tar.gz
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>    File "", line 1, in
>    File "/tmp/pip-build-qguU_e/pyev/setup.py", line 56, in
>    check_version(python_version, min_python_versions[major],
>    "Python{0}".format(major))
>    File "/tmp/pip-build-qguU_e/pyev/setup.py", line 40, in check_version
>    if StrictVersion(current_version) < StrictVersion(minimum_version):
>    File "/usr/lib/python2.7/distutils/version.py", line 40, in *init*
>    self.parse(vstring)
>    File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
>    raise ValueError, "invalid version number '%s'" % vstring
>    ValueError: invalid version number '2.7.11+'
>    ------------------------------
>
>    Command "python setup.py egg_info" failed with error code 1 in
>    /tmp/pip-build-qguU_e/pyev/
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/278#issuecomment-221510090>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by Dreamwhite** [comment]
Ok,thank you!
