### ISSUE TITLE
geoloc honeymap fatal error may be due to problem in go1.4.2.linux-amd64.tar.gz.5

### ISSUE THREAD

**Issue by muhyousaf** [threatstream/mhn#279]
Hi everyone,
I'm following latest installation guide at https://github.com/threatstream/mhn 
After the completion of the installation, I found the following error:
**/opt/mhn$ sudo supervisorctl status**
geoloc                           FATAL      Exited too quickly (process log may have details)
honeymap                         FATAL      can't find command '/opt/honeymap/server/server'
hpfeeds-broker                   RUNNING    pid 15859, uptime 1 day, 4:23:35
hpfeeds-logger-splunk            RUNNING    pid 62088, uptime 1:02:49
mhn-celery-beat                  RUNNING    pid 61739, uptime 1:07:35
mhn-celery-worker                RUNNING    pid 62091, uptime 1:02:44
mhn-collector                    RUNNING    pid 61741, uptime 1:07:35
mhn-uwsgi                        RUNNING    pid 61743, uptime 1:07:35
mnemosyne                        RUNNING    pid 33919, uptime 1 day, 4:07:32

I have been getting this error from the previous installation guide also given at the link:
https://itandsecuritystuffs.wordpress.com/2015/02/03/honeypot-networks/

For getting the error notification, I again tried the following:
**/opt/mhn/scripts$ sudo ./install_honeymap.sh** 

Everything went fine except the following:
+ GO_PACKAGE=go1.4.2.linux-amd64.tar.gz
+ cd /usr/local/
+ wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
--2016-05-20 22:21:15--  https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.200.128, 2404:6800:4003:804::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.200.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62442704 (60M) [application/x-gzip]
Saving to: ‘go1.4.2.linux-amd64.tar.gz.5’

100%[=====================================================================================================>] 62,442,704   

2016-05-20 22:26:36  - ‘go1.4.2.linux-amd64.tar.gz.5’ saved [62442704/62442704]

+ **tar zxf go1.4.2.linux-amd64.tar.gz**

**gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now**
+ cd /usr/bin/
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/go
/usr/local/go/bin/go
+ ln -s /usr/local/go/bin/go
ln: failed to create symbolic link ‘./go’: File exists
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/godoc
/usr/local/go/bin/godoc
+ ln -s /usr/local/go/bin/godoc
ln: failed to create symbolic link ‘./godoc’: File exists
+ for X in '/usr/local/go/bin/*'
+ echo /usr/local/go/bin/gofmt
/usr/local/go/bin/gofmt
+ ln -s /usr/local/go/bin/gofmt
ln: failed to create symbolic link ‘./gofmt’: File exists
++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
+ SECRET=5fd4885712ca4836a018a76667919946
+ /opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py honeymap 5fd4885712ca4836a018a76667919946 '' geoloc.events
updated {'subscribe': ['geoloc.events'], 'secret': '5fd4885712ca4836a018a76667919946', 'identifier': 'honeymap', 'publish': []}
+ cd /opt
+ git clone https://github.com/threatstream/honeymap.git
fatal: destination path 'honeymap' already exists and is not an empty directory.
+ cd /opt/honeymap/server
++ pwd
+ export GOPATH=/opt/honeymap/server
+ GOPATH=/opt/honeymap/server
+ go get
package bufio: unrecognized import path "bufio"
package bytes: unrecognized import path "bytes"
package container/list: unrecognized import path "container/list"
package crypto/md5: unrecognized import path "crypto/md5"
package crypto/rand: unrecognized import path "crypto/rand"
package crypto/sha1: unrecognized import path "crypto/sha1"
package crypto/tls: unrecognized import path "crypto/tls"
package encoding/base64: unrecognized import path "encoding/base64"
package encoding/binary: unrecognized import path "encoding/binary"
package encoding/json: unrecognized import path "encoding/json"
package errors: unrecognized import path "errors"
package fmt: unrecognized import path "fmt"
package log: unrecognized import path "log"
package net: unrecognized import path "net"
package runtime: unrecognized import path "runtime"
package io: unrecognized import path "io"
package io/ioutil: unrecognized import path "io/ioutil"
package net/http: unrecognized import path "net/http"
package net/url: unrecognized import path "net/url"
package strings: unrecognized import path "strings"
package sync: unrecognized import path "sync"
package time: unrecognized import path "time"
package math/rand: unrecognized import path "math/rand"
package net/http/httputil: unrecognized import path "net/http/httputil"
package os: unrecognized import path "os"
package regexp: unrecognized import path "regexp"
package unicode/utf8: unrecognized import path "unicode/utf8"
package path: unrecognized import path "path"
+ go build
src/github.com/jt6211/sockjs-go/sockjs/protocol.go:4:2: cannot find package "bufio" in any of:
	/usr/local/go/src/bufio (from $GOROOT)
	/opt/honeymap/server/src/bufio (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:7:2: cannot find package "bytes" in any of:
	/usr/local/go/src/bytes (from $GOROOT)
	/opt/honeymap/server/src/bytes (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/session.go:4:2: cannot find package "container/list" in any of:
	/usr/local/go/src/container/list (from $GOROOT)
	/opt/honeymap/server/src/container/list (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/config.go:4:2: cannot find package "crypto/md5" in any of:
	/usr/local/go/src/crypto/md5 (from $GOROOT)
	/opt/honeymap/server/src/crypto/md5 (from $GOPATH)
src/golang.org/x/net/websocket/hybi.go:13:2: cannot find package "crypto/rand" in any of:
	/usr/local/go/src/crypto/rand (from $GOROOT)
	/opt/honeymap/server/src/crypto/rand (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:8:2: cannot find package "crypto/sha1" in any of:
	/usr/local/go/src/crypto/sha1 (from $GOROOT)
	/opt/honeymap/server/src/crypto/sha1 (from $GOPATH)
src/golang.org/x/net/websocket/client.go:9:2: cannot find package "crypto/tls" in any of:
	/usr/local/go/src/crypto/tls (from $GOROOT)
	/opt/honeymap/server/src/crypto/tls (from $GOPATH)
src/golang.org/x/net/websocket/hybi.go:15:2: cannot find package "encoding/base64" in any of:
	/usr/local/go/src/encoding/base64 (from $GOROOT)
	/opt/honeymap/server/src/encoding/base64 (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:9:2: cannot find package "encoding/binary" in any of:
	/usr/local/go/src/encoding/binary (from $GOROOT)
	/opt/honeymap/server/src/encoding/binary (from $GOPATH)
honeymap.go:4:2: cannot find package "encoding/json" in any of:
	/usr/local/go/src/encoding/json (from $GOROOT)
	/opt/honeymap/server/src/encoding/json (from $GOPATH)
src/golang.org/x/net/websocket/websocket.go:13:2: cannot find package "errors" in any of:
	/usr/local/go/src/errors (from $GOROOT)
	/opt/honeymap/server/src/errors (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:10:2: cannot find package "fmt" in any of:
	/usr/local/go/src/fmt (from $GOROOT)
	/opt/honeymap/server/src/fmt (from $GOPATH)
src/golang.org/x/net/websocket/client.go:10:2: cannot find package "io" in any of:
	/usr/local/go/src/io (from $GOROOT)
	/opt/honeymap/server/src/io (from $GOPATH)
src/golang.org/x/net/websocket/hybi.go:19:2: cannot find package "io/ioutil" in any of:
	/usr/local/go/src/io/ioutil (from $GOROOT)
	/opt/honeymap/server/src/io/ioutil (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:11:2: cannot find package "log" in any of:
	/usr/local/go/src/log (from $GOROOT)
	/opt/honeymap/server/src/log (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/info.go:5:2: cannot find package "math/rand" in any of:
	/usr/local/go/src/math/rand (from $GOROOT)
	/opt/honeymap/server/src/math/rand (from $GOPATH)
src/github.com/fw42/go-hpfeeds/hpfeeds.go:12:2: cannot find package "net" in any of:
	/usr/local/go/src/net (from $GOROOT)
	/opt/honeymap/server/src/net (from $GOPATH)
src/golang.org/x/net/websocket/client.go:12:2: cannot find package "net/http" in any of:
	/usr/local/go/src/net/http (from $GOROOT)
	/opt/honeymap/server/src/net/http (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/protocol.go:7:2: cannot find package "net/http/httputil" in any of:
	/usr/local/go/src/net/http/httputil (from $GOROOT)
	/opt/honeymap/server/src/net/http/httputil (from $GOPATH)
src/golang.org/x/net/websocket/client.go:13:2: cannot find package "net/url" in any of:
	/usr/local/go/src/net/url (from $GOROOT)
	/opt/honeymap/server/src/net/url (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/config.go:8:2: cannot find package "os" in any of:
	/usr/local/go/src/os (from $GOROOT)
	/opt/honeymap/server/src/os (from $GOPATH)
honeymap.go:13:2: cannot find package "path" in any of:
	/usr/local/go/src/path (from $GOROOT)
	/opt/honeymap/server/src/path (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/handler.go:5:2: cannot find package "regexp" in any of:
	/usr/local/go/src/regexp (from $GOROOT)
	/opt/honeymap/server/src/regexp (from $GOPATH)
package .
	imports runtime: cannot find package "runtime" in any of:
	/usr/local/go/src/runtime (from $GOROOT)
	/opt/honeymap/server/src/runtime (from $GOPATH)
src/golang.org/x/net/websocket/hybi.go:22:2: cannot find package "strings" in any of:
	/usr/local/go/src/strings (from $GOROOT)
	/opt/honeymap/server/src/strings (from $GOPATH)
src/golang.org/x/net/websocket/websocket.go:19:2: cannot find package "sync" in any of:
	/usr/local/go/src/sync (from $GOROOT)
	/opt/honeymap/server/src/sync (from $GOPATH)
src/golang.org/x/net/websocket/websocket.go:20:2: cannot find package "time" in any of:
	/usr/local/go/src/time (from $GOROOT)
	/opt/honeymap/server/src/time (from $GOPATH)
src/github.com/jt6211/sockjs-go/sockjs/utils.go:11:2: cannot find package "unicode/utf8" in any of:
	/usr/local/go/src/unicode/utf8 (from $GOROOT)
	/opt/honeymap/server/src/unicode/utf8 (from $GOPATH)

**Comment by muhyousaf** [comment]
I'm using ubuntu 14.04 LTS as a vm. I tried it multiple times and every time got the same error.

**Comment by jt6211** [comment]
Is it possible that the download failed the first time.  Here's why:  The
file is saved to go1.4.2.linux-amd64.tar.gz.5 but the tar command is trying
to read go1.4.2.linux-amd64.tar.gz which may have failed to download
originally and it may be truncated.


   - wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
    --2016-05-20 22:21:15--
   https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
    Resolving storage.googleapis.com(storage.googleapis.com)...
   74.125.200.128, 2404:6800:4003:804::2010 Connecting to
   storage.googleapis.com (storage.googleapis.com)|74.125.200.128|:443...
   connected. HTTP request sent, awaiting response... 200 OK Length: 62442704
   (60M) [application/x-gzip] Saving to: ‘go1.4.2.linux-amd64.tar.gz.5’

100%[=====================================================================================================>]
62,442,704

2016-05-20 22:26:36 - ‘go1.4.2.linux-amd64.tar.gz.5’ saved
[62442704/62442704]

   - *tar zxf go1.4.2.linux-amd64.tar.gz*




*gzip: stdin: unexpected end of filetar: Unexpected EOF in archivetar:
Unexpected EOF in archivetar: Error is not recoverable: exiting now*

On Sat, May 21, 2016 at 7:34 AM, muhyousaf <notifications@github.com> wrote:

> I'm using ubuntu 14.04 LTS as a vm. I tried it multiple times and every
> time got the same error.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/279#issuecomment-220772960>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by muhyousaf** [comment]
Thank you Jason,
Yes, you were right. That problem is fixed by removing the faulty downloaded file and then reinstalling the honeymap as follows:  
$ cd /usr/local/
$ sudo rm go1.4.2.linux-amd64.tar.gz
$ cd /opt/mhn/scripts
$ sudo ./install_honeymap.sh

Now, 
$ sudo supervisorctl status
geoloc                           RUNNING    pid 2117, uptime 2:22:56
honeymap                         RUNNING    pid 2164, uptime 2:22:56
hpfeeds-broker                   RUNNING    pid 2114, uptime 2:22:56
hpfeeds-logger-splunk            RUNNING    pid 2113, uptime 2:22:56
mhn-celery-beat                  RUNNING    pid 2108, uptime 2:22:56
mhn-celery-worker                RUNNING    pid 2129, uptime 2:22:56
mhn-collector                    RUNNING    pid 2138, uptime 2:22:56
mhn-uwsgi                        RUNNING    pid 2121, uptime 2:22:56
mnemosyne                        RUNNING    pid 2116, uptime 2:22:56


However, dashboard show this:
**http://localhost/ui/dashboard/**

Attack Stats
Attacks in the last 24 hours:
0
TOP 5 Attacker IPs:

TOP 5 Attacked ports:

TOP 5 Honey Pots:

TOP 5 Sensors:

TOP 5 Attacks Signatures:

and, map:
**http://localhost/ui/honeymap/

Not Found**
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Following is the log for reference:
**user@ubuntu:/var/log/mhn$ cat honeymap.err**
2016/05/26 14:15:22 Binding Honeymap webserver to 0.0.0.0:3000...
2016/05/26 14:15:22 Connecting to localhost:10000...
2016/05/26 14:15:22 Connected to Hpfeeds server.
2016/05/26 14:28:21 Read(): EOF
2016/05/26 14:28:21 Lost connection to localhost:10000 :-(
2016/05/26 14:28:21 Reconnecting to localhost:10000
2016/05/26 14:28:21 Reconnecting to localhost:10000
2016/05/26 14:28:22 Reconnecting to localhost:10000
2016/05/26 14:28:24 Reconnecting to localhost:10000
2016/05/26 14:28:27 Reconnecting to localhost:10000
2016/05/26 14:28:31 Reconnecting to localhost:10000
2016/05/26 14:28:36 Reconnecting to localhost:10000
2016/05/26 14:28:42 Reconnecting to localhost:10000
2016/05/26 14:28:49 Reconnecting to localhost:10000
2016/05/26 14:28:57 Reconnecting to localhost:10000
2016/05/26 14:29:06 Reconnecting to localhost:10000
2016/05/26 14:29:56 Binding Honeymap webserver to 0.0.0.0:3000...
2016/05/26 14:29:56 Connecting to localhost:10000...
2016/05/26 14:29:56 Reconnecting to localhost:10000
2016/05/26 14:29:56 Reconnecting to localhost:10000
2016/05/26 14:29:57 Connected to Hpfeeds server.

Any suggestion?

**Comment by jt6211** [comment]
Your HONEYMAP_URL in your /opt/mhn/server/config.py is likely wrong.  it
should probably be http://localhost:3000.  Once you fix that, restart the
MHN webapp like this:

sudo supervisorctl restart mhn-uwsgi

On Thu, May 26, 2016 at 8:10 AM, Yousaf <notifications@github.com> wrote:

> Thank you Jason,
> Yes, you were right. That problem is fixed by removing the faulty
> downloaded file and then reinstalling the honeymap as follows:
>
> $ cd /usr/local/
> $ sudo rm go1.4.2.linux-amd64.tar.gz
> $ cd /opt/mhn/scripts
> $ sudo ./install_honeymap.sh
>
> Now,
> $ sudo supervisorctl status
> geoloc RUNNING pid 2117, uptime 2:22:56
> honeymap RUNNING pid 2164, uptime 2:22:56
> hpfeeds-broker RUNNING pid 2114, uptime 2:22:56
> hpfeeds-logger-splunk RUNNING pid 2113, uptime 2:22:56
> mhn-celery-beat RUNNING pid 2108, uptime 2:22:56
> mhn-celery-worker RUNNING pid 2129, uptime 2:22:56
> mhn-collector RUNNING pid 2138, uptime 2:22:56
> mhn-uwsgi RUNNING pid 2121, uptime 2:22:56
> mnemosyne RUNNING pid 2116, uptime 2:22:56
>
> However, dashboard show this:
> *http://localhost/ui/dashboard/ <http://localhost/ui/dashboard/>*
>
> Attack Stats
> Attacks in the last 24 hours:
> 0
> TOP 5 Attacker IPs:
>
> TOP 5 Attacked ports:
>
> TOP 5 Honey Pots:
>
> TOP 5 Sensors:
>
> TOP 5 Attacks Signatures:
>
> and, map:
> **http://localhost/ui/honeymap/
>
> Not Found**
> The requested URL was not found on the server. If you entered the URL
> manually please check your spelling and try again.
>
> Following is the log for reference:
> *user@ubuntu:/var/log/mhn$ cat honeymap.err*
> 2016/05/26 14:15:22 Binding Honeymap webserver to 0.0.0.0:3000...
> 2016/05/26 14:15:22 Connecting to localhost:10000...
> 2016/05/26 14:15:22 Connected to Hpfeeds server.
> 2016/05/26 14:28:21 Read(): EOF
> 2016/05/26 14:28:21 Lost connection to localhost:10000 :-(
> 2016/05/26 14:28:21 Reconnecting to localhost:10000
> 2016/05/26 14:28:21 Reconnecting to localhost:10000
> 2016/05/26 14:28:22 Reconnecting to localhost:10000
> 2016/05/26 14:28:24 Reconnecting to localhost:10000
> 2016/05/26 14:28:27 Reconnecting to localhost:10000
> 2016/05/26 14:28:31 Reconnecting to localhost:10000
> 2016/05/26 14:28:36 Reconnecting to localhost:10000
> 2016/05/26 14:28:42 Reconnecting to localhost:10000
> 2016/05/26 14:28:49 Reconnecting to localhost:10000
> 2016/05/26 14:28:57 Reconnecting to localhost:10000
> 2016/05/26 14:29:06 Reconnecting to localhost:10000
> 2016/05/26 14:29:56 Binding Honeymap webserver to 0.0.0.0:3000...
> 2016/05/26 14:29:56 Connecting to localhost:10000...
> 2016/05/26 14:29:56 Reconnecting to localhost:10000
> 2016/05/26 14:29:56 Reconnecting to localhost:10000
> 2016/05/26 14:29:57 Connected to Hpfeeds server.
>
> Any suggestion?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/threatstream/mhn/issues/279#issuecomment-221853523>
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by muhyousaf** [comment]
Thank you dear. Problem solved. 
Earlier it was like this:
**HONEYMAP_URL = ':3000'**
Changing it to **HONEYMAP_URL = 'http://localhost:3000'** solved the problem.

**Comment by SilenCtrl** [comment]
3q,the tips alse help me.
