### ISSUE TITLE
Installation Script Issues

### ISSUE THREAD

**Issue by v0idif** [threatstream/mhn#281]
Hello,

During the installation of any a script on my server (either Dioanae,p0f etc) the installation fail with the follow error:

```
W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Any suggestions how i can fix the specific issue?

Thanks

**Comment by jt6211** [comment]
Are you installing on a Raspberry Pi?  If not, use the other Dioneae
install script (named "Ubuntu - Dionaea").

On Sun, May 29, 2016 at 7:20 AM, v0idif <notifications@github.com> wrote:

> Hello,
>
> During the installation of any a script on my server (either Dioanae,p0f
> etc) the installation fail with the follow error:
>
> W: Failed to fetch
> http://packages.s7t.de/raspbian/dists/wheezy/main/binary-amd64/Packages
> 404 Not Found
>
> W: Failed to fetch
> http://packages.s7t.de/raspbian/dists/wheezy/main/binary-i386/Packages
> 404 Not Found
>
> E: Some index files failed to download. They have been ignored, or old
> ones used instead.
>
> Any suggestions how i can fix the specific issue?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/281>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8GKRi_JB9eSJT5fsoU5LZhXSG6eiks5qGXZ_gaJpZM4IpRMC>
> .
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by v0idif** [comment]
Hello Jason,

Not really, i am installing on a fresh-clean ubuntu server. I have tried to install other scripts as well with the same error, i cant install any of the suggested scripts provided on the panel.

**Comment by jt6211** [comment]
The error you're getting is because you're using the Raspberry Pi Dionaea
script.  You need to use the Ubunut Dionaea script.

On Mon, May 30, 2016 at 9:51 AM, v0idif <notifications@github.com> wrote:

> Hello Jason,
>
> Not really, i am installing on a fresh-clean ubuntu server. I have tried
> to install other scripts as well with the same error, i cant install any of
> the suggested scripts provided on the panel.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/281#issuecomment-222497043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8Eh-f_RqfmFBUSgp89bjZ3CrKvYPks5qGutcgaJpZM4IpRMC>
> .
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by v0idif** [comment]
Ok Thanks, i will let you know as soon as i re-run the script.

However does the Dionaea script capture the binaries and import them on the server as well?

**Comment by jt6211** [comment]
Yes, it should.  MHN uses mnemosyne to collect and process all the hfeeps
data and one of the modules collects the binaries and stories them in Mongo.

https://github.com/threatstream/mnemosyne/blob/master/normalizer/modules/dionaea_binary.py

On Mon, May 30, 2016 at 10:28 AM, v0idif <notifications@github.com> wrote:

> Ok Thanks, i will let you know as soon as i re-run the script.
>
> However does the Dionaea script capture the binaries and import them on
> the server as well?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/281#issuecomment-222504189>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8HanlhFiuUhzTy8qSnFTGyYn3SrTks5qGvQigaJpZM4IpRMC>
> .
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by v0idif** [comment]
Ok Great,Thanks Jason scripts were successfully installed. I will let you know if i face any issues collecting the binaries.

**Comment by mofei-123** [comment]
I have same question，@v0idif you question is ok?
