### ISSUE TITLE
Dionaea not downloading malware

### ISSUE THREAD

**Issue by xsallowed** [threatstream/mhn#282]
Hello everyone 
This seems like more of dionaea issue than mhn issue. Can anyone help me if they are having the problem of dionaea not being able to download the malware from net.  I have been receiving thousands of connections but zero binaries/ payload. Either my isp is doing a wonderful job or something is wrong with dionaea. I need a quick answer and would highly appreciate any help in here. 

Thanks

**Comment by xsallowed** [comment]
any help ???

**Comment by sh4t** [comment]
Are you seeing any payloads within the Payloads section of your MHN gui; believe it is something like: ui/feeds/?channel=dionaea.captures

You should see the individual hashes associated;  Additionally, within mongodb you could search within the mnemosyne.file collection:

`db.getCollection('file').find({});`

should yield results similar to:

```
/* 1 */
{
    "_id" : ObjectId("56bdc529f1dc4fd74e99be17"),
    "hashes" : {
        "sha1" : "d43f120c5d22134de68d5cac90ee0d19641aecb4",
        "sha512" : "1a5f2e785a88a4c811322db75d216cacde556c2ea37d38a7f558e25721f749e40d447c5f195e8dae2e510472980d1f62fadcb5622a680bb5014306a847946f8b",
        "md5" : "d45e70c5209bd8d5ab33890244bb515f"
    },
    "data" : "ef3800...... redacted due to length",
    "content_guess" : "data",
    "encoding" : "hex",
    "hpfeed_ids" : [ 
        ObjectId("56bdc529e5645d58a284eb85")
    ]
}
```

**Comment by mirkathaha** [comment]
Likewise, I have been receiving thousands of connections but zero binaries/ payload.
Honeypot: dionaea Attacks: 2884

Tried running command db.getCollection('file').find({});, it yields no result.

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      969/sshd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1074/python
tcp        0      0 127.0.0.1:28017         0.0.0.0:*               LISTEN      962/mongod
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3416/python
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      962/mongod
tcp6       0      0 :::2222                 :::*                    LISTEN      969/sshd
tcp6       0      0 :::21                   :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::1433                 :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::445                  :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::5060                 :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::5061                 :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::135                  :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::3306                 :::*                    LISTEN      1077/dionaea
tcp6       0      0 :::42                   :::*                    LISTEN      1077/dionaea
udp        0      0 0.0.0.0:68              0.0.0.0:*                           582/dhclient
udp        0      0 0.0.0.0:60000           0.0.0.0:*                           582/dhclient
udp6       0      0 :::5060                 :::*                                1077/dionaea
udp6       0      0 :::69                   :::*                                1077/dionaea
udp6       0      0 :::42820                :::*                                582/dhclient
```

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

```
cowrie                           RUNNING    pid 3416, uptime 3 days, 8:13:14
dionaea                          RUNNING    pid 1077, uptime 4 days, 21:24:02
glastopf                         RUNNING    pid 1074, uptime 4 days, 21:24:02
p0f                              RUNNING    pid 1080, uptime 4 days, 21:24:02
snort                            RUNNING    pid 1087, uptime 4 days, 21:24:01
```

What should I do next to resolve this issue? Thanks!

**Comment by SmUrF3R5** [comment]
I am also having this issue. Dionaea running on multiple sensors.

**Comment by Waseem-farooqui** [comment]
There are list of things you have to check,

1. Your ports are open specially 445.
2. Your firewall is not blocking the following any port.
3. nmap you IP and check whether your port is filtered or open. (Resolve the issue if filtered.) 

There could be following bugs.
https://curl.haxx.se/mail/tracker-2014-02/0025.html
https://curl.haxx.se/mail/tracker-2010-12/0008.html

**Comment by bensmith83** [comment]
I have the same issue. Port is allowed via iptables and is accessible. The curl issue may be valid yet I see nothing referencing curl in the dionaea-errors.log. I have also disabled IPv6 on the interface.

**Comment by Waseem-farooqui** [comment]
Have you tried to nmap your ports ?

**Comment by arnydo** [comment]
Same issue expereinced here.
Ports are open and connections are being made.
However, no payloads are captured.
Followed the steps you have recommended.

**Comment by d1str0** [comment]
Will be tracked further in #326 and #417
