### ISSUE TITLE
add-apt-repository: command not found in Docker installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by pmontrasio** [threatstream/mhn#284]
I'm following the instructions at https://github.com/threatstream/mhn/wiki/Running-MHN-in-Docker on Ubuntu 14.04

I'm getting this at the very end, when installing ELK:

```
+ add-apt-repository -y ppa:webupd8team/java
./install_elk.sh: line 11: add-apt-repository: command not found
```

The `add-apt-repository` command is not available on 14.04 unless explicitly installed.
The line

```
apt-get install -y python-software-properties
```

at https://github.com/threatstream/mhn/blob/master/scripts/install_elk.sh should be

```
apt-get install -y software-properties-common python-software-properties
```

**Comment by d1str0** [comment]
Currently only supporting Ubuntu 16.04 and 18.04
