### ISSUE TITLE
Snaralliance

### ISSUE THREAD

**Issue by polancossj** [threatstream/mhn#285]
Can I add Snare as mhn sensor , it is possible?

**Comment by jt6211** [comment]
I am not familiar with this project.  Can you provide a link?

**Comment by polancossj** [comment]
Yes, Snare (sometimes also written as SNARE, an acronym for System iNtrusion Analysis and Reporting Environment) is a collection of software tools that collect audit log data from a variety of operating systems and applications to facilitate centralised log analysis.

https://sourceforge.net/projects/snare/files/Snare%20for%20Linux/2.1.0/ 
https://en.wikipedia.org/wiki/Snare_(software)
https://www.intersectalliance.com/our-product/snare-agent/

I wonder if is possible establish a communication between them (SNARE and MHN)?

Thanks!!

**Comment by jt6211** [comment]
This should be possible.  We were able to integrate snort, surricata, and
p0f without trouble. You pretty much just need to add code to submit
hpfeeds messages to MHN and then add code in mnemosyne to index it and
honeymap to render it.

On Thu, Jun 9, 2016 at 8:50 PM, polancossj <notifications@github.com> wrote:

> Yes, Snare (sometimes also written as SNARE, an acronym for System
> iNtrusion Analysis and Reporting Environment) is a collection of software
> tools that collect audit log data from a variety of operating systems and
> applications to facilitate centralised log analysis.
>
> https://sourceforge.net/projects/snare/files/Snare%20for%20Linux/2.1.0/
> https://en.wikipedia.org/wiki/Snare_(software)
> https://www.intersectalliance.com/our-product/snare-agent/
>
> I wonder if is possible establish a communication between them (SNARE and
> MHN)?
>
> Thanks!!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/285#issuecomment-225067744>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8EA7MVwZKUYvdJbK_I83hBqBtEJcks5qKLTXgaJpZM4Iyfoi>
> .
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

**Comment by polancossj** [comment]
Ok thanks for your answer, I'll start working on it, if I have new questions I ask you again. 

Thanks!

**Comment by Philelis** [comment]
Did you get any solution?

**Comment by d1str0** [comment]
Definitely interested if OP has created any code for this, in the meantime, closing this issue.
