### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by kayaaaba** [threatstream/mhn#287]
How can i add a link to another html file or deserialize a text file on the web page of the mhn server?
Permissions to files are the same as to other and all installations were completed successfully
(I've tried to do both but got 404 page not found error)

**Comment by jt6211** [comment]
Any file you put in /opt/mhn/server/mhn/static/ should be accessible on via /static/path/to/file.html.  You will probably need to make the permissions 755 on the file.  Look at the permissions of the other files in this directory to see.

**Comment by kayaaaba** [comment]
Thank you! That helped
