### ISSUE TITLE
customization of mhn web application

### ISSUE THREAD

**Issue by nikita-raina** [threatstream/mhn#289]
Can anyone tell if we can customize our MHN web application so that we can see the detailed logs on the web application itself.I want the web application to show what the attacker tried to do apart from the src ip ,dst port and protocol.

**Comment by d1str0** [comment]
In the case of dionaea, you should be able to see the payloads uploaded to the honeypot (if any were).

Of course you are able to customize the web app, whether you fork it or just customise locally, but it will vary depending on the honeypots you choose to support for this extra data.

Which honeypot are you looking to get this extra info from?
