### ISSUE TITLE
Automatic reading of ip's from the logs in mhn and describing its location

### ISSUE THREAD

**Issue by nikita-raina** [threatstream/mhn#291]
Is there any script available which automatically will read the logs from splunk in mhn and get the ip and tell its location i.e. from which country.
or how the mhn is itself describing the location of ip's by showing the flags.

**Comment by jt6211** [comment]
If you are using hpfeeds-logger to produce the log you send to splunk, the
IP geo info should be included.  Look for fields that start with "src_" or
"dst_" and end in one of these names:
https://github.com/threatstream/hpfeeds-logger/blob/master/hpfeedslogger/processors.py#L53-L67

On Wed, Jul 13, 2016 at 12:21 AM, nikita-raina <notifications@github.com>
wrote:

> Is there any script available which automatically will read the logs from
> splunk in mhn and get the ip and tell its location i.e. from which country.
> or how the mhn is itself describing the location of ip's by showing the
> flags.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/291>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8OdTEMEMZ7cn-W1Ak2iCcAUdZOTuks5qVGfRgaJpZM4JLDLX>
> .
>



-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

<https://www.anomali.com/anomali-detect>

**Comment by nikita-raina** [comment]
thank you very much:)
