### ISSUE TITLE
Unable to see private RFC 1918 data

### ISSUE THREAD

**Issue by atgithub11** [threatstream/mhn#296]
Hi,

I am testing MHN on a private network and have deployed a kippo sensor on the same server which also hosts MHN. I can see kippo logging data from nmap and VA scans but I cannot see any of this in the UI. 

In the troubleshooting guide, it does mention that by default, mnemosyne  will filter out RFC1918 addresses. But even after following the workaround, i.e. adding following to mnemosyne.cfg and restarting service, it's still unable to record any of the attacks.

[normalizer]
ignore_rfc1918 = False

Here are some results:

kippo]$ ./start.sh
/usr/lib64/python2.6/site-packages/twisted/conch/ssh/keys.py:13: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha, md5
/usr/lib64/python2.6/site-packages/twisted/conch/ssh/keys.py:13: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import sha, md5
Loading dblog engine: hpfeeds
hpfeeds DBLogger start
hpfeeds client init broker MHN_Server:10000, identifier xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
hpclient established

# tail -f /var/log/mhn/hpfeeds-broker.err

INFO:root:Database ready.
INFO:root:Auth success by <Identifier Key>.
INFO:root:Auth success by <Identifier Key>.

# supervisorctl status
geoloc                           RUNNING   pid 13126, uptime 0:18:55
honeymap                         RUNNING   pid 13115, uptime 0:18:55
hpfeeds-broker                   RUNNING   pid 13130, uptime 0:18:55
mhn-celery-beat                  RUNNING   pid 13114, uptime 0:18:55
mhn-celery-worker                RUNNING   pid 13128, uptime 0:18:55
mhn-collector                    RUNNING   pid 13129, uptime 0:18:55
mhn-uwsgi                        RUNNING   pid 13127, uptime 0:18:55
mnemosyne                        RUNNING   pid 13116, uptime 0:18:55

# netstat -luntp | grep 10000
tcp        0      0 0.0.0.0:10000               0.0.0.0:*                   LISTEN      13130/python

# netstat -luntp | grep 8181
tcp        0      0 0.0.0.0:8181                0.0.0.0:*                   LISTEN      13116/python

From kippo.log
2016-07-22 15:19:12-0400 [kippo.core.honeypot.HoneyPotSSHFactory] New connection: VA_SCANNER:42463 (127.0.0.1:64222) [session: 74]
2016-07-22 15:19:12-0400 [HoneyPotTransport,74,VA_SCANNER] connection lost
2016-07-22 15:19:12-0400 [HoneyPotTransport,74,VA_SCANNER] publishing metadata to hpfeeds

Noticed the following. Not sure if any of this relates to the issue:

# cat  /var/log/mhn/mnemosyne.log

2016-07-22 15:27:51,664 (pyhpfeeds) connecting to localhost:10000
2016-07-22 15:27:51,666 (pyhpfeeds) FeedException while connecting: Could not connect to broker [localhost].
2016-07-22 15:28:11,667 (pyhpfeeds) connecting to localhost:10000
2016-07-22 15:28:11,669 (pyhpfeeds) FeedException while connecting: Could not connect to broker [localhost].

# cat /var/log/mhn/mnemosyne.err

2016-07-22 15:29:31,682 (pyhpfeeds) connecting to localhost:10000
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/socket.py", line 342 in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused
2016-07-22 15:29:31,683 (pyhpfeeds) FeedException while connecting: Could not connct to broker [localhost].

# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Kindly Assist.

Thanks,

**Comment by jt6211** [comment]
What is the output for this command?

```
grep localhost /etc/hosts
```

**Comment by atgithub11** [comment]
Hi jt6211,

Here is the output:

grep localhost /etc/hosts
::1  Hostname Hostname localhost
#::1            localhost6.localdomain6 localhost6

**Comment by atgithub11** [comment]
Oversight on my side. 

Added "localhost" for 127.0.0.1 and now hpfeeds is getting data correctly.
