### ISSUE TITLE
Splunk

### ISSUE THREAD

**Issue by smarthive-skp** [threatstream/mhn#303]
I have installed splunk_universalforwarder and it shows that splunkd is running but I cant open up the webpage. What port is the page on? I have tried 8000, 8001,8002. 

SKP

**Comment by rishii2129** [comment]
Universal Fowarder is a light weight splunk instance which is only used to collect logs and send to splunk indexer. So you can not see web pages for universal forwarder.

Thanks
Rishabh 
< Splunk Support Engineer.

**Comment by nx4dm1n** [comment]
@smarthive-skp this file is install splunk forwarder，the default web port is 8089 .

`ps aux |grep splunk `

you use this command find the port number。

use https ！
