### ISSUE TITLE
Which ports do I need to open?

### ISSUE THREAD

**Issue by thatguy031415** [threatstream/mhn#304]
I have an MHN server 'in the cloud' and honeypots deployed both in the cloud, and on corporate networks.  Those on corporate networks are unable to send alerts/events/attacks back to the server.  What values do I need to change in order to use ports that are already allowed through the firewall?  I'd rather avoid submitting change requests if possible.  Barring that, what ports need to be open in order for the honeypot to communicate with the server?

**Comment by jt6211** [comment]
The MHN Server listens on port 80 (main webapp), 3000 (honeymap -- needed only for your web browser) and 10000 (hpfeeds) by default.  If you have setup HTTPS then replace port 80 with 443.

Moving hpfeeds to another port would require many config changes, mostly on the honeypot side.  See https://github.com/threatstream/mhn/search?utf8=%E2%9C%93&q=10000&type=Code.  

Here are all the services that read/wite to the hpfeeds broker:

* mnemosyne
* honeymap
* hpfeeds-logger - only used if you are integrating MHN with splunk, Arcsight or ELK.
* all honeypots

In order for this change to be applicable to honeypots you deploy after the change, you would need to modify your MHN deploy scripts in your MHN webapp as well as /opt/mhn/server/mhn/static/registration.txt (just look for "10000" and replace it as needed)
