### ISSUE TITLE
honeymap FATAL "can't find command '/opt/honeymap/server/server'

### ISSUE THREAD

**Issue by ybAmazing** [threatstream/mhn#305]
I installed mhn on my Ubuntu LTS14.04  followed by [https://github.com/threatstream/mhn](url).
At the end, supervisorctl status command shows:  
geoloc                           RUNNING    pid 28810, uptime 0:32:44
honeymap                         FATAL      can't find command '/opt/honeymap/server/server'
hpfeeds-broker                   RUNNING    pid 9219, uptime 0:48:06
mhn-celery-beat                  RUNNING    pid 30462, uptime 0:11:51
mhn-celery-worker                RUNNING    pid 30569, uptime 0:09:30
mhn-collector                    RUNNING    pid 30464, uptime 0:11:51
mhn-uwsgi                        RUNNING    pid 30465, uptime 0:11:51
mnemosyne                        RUNNING    pid 27097, uptime 0:41:20
root@iZ2547dvr8xZ:/opt/honeymap# supervisorctl status
geoloc                           RUNNING    pid 28810, uptime 0:36:10
honeymap                         FATAL      can't find command '/opt/honeymap/server/server'
hpfeeds-broker                   RUNNING    pid 9219, uptime 0:51:32
mhn-celery-beat                  RUNNING    pid 30462, uptime 0:15:17
mhn-celery-worker                RUNNING    pid 30569, uptime 0:12:56
mhn-collector                    RUNNING    pid 30464, uptime 0:15:17
mhn-uwsgi                        RUNNING    pid 30465, uptime 0:15:17
mnemosyne                        RUNNING    pid 27097, uptime 0:44:46

and there is no execuable server under /opt/honeymap/server.So I intented to make the honeymap by:
apt-get install coffeescript
make
and then,I received:
coffee -cj client/js/honeymap.js client/coffee/_.coffee client/coffee/feeds/hpfeeds.coffee
cd server; go build
honeymap.go:5:2: cannot find package "github.com/fw42/go-hpfeeds" in any of:
        /usr/local/go/src/github.com/fw42/go-hpfeeds (from $GOROOT)
        ($GOPATH not set)
honeymap.go:6:2: cannot find package "github.com/jt6211/sockjs-go/sockjs" in any of:
        /usr/local/go/src/github.com/jt6211/sockjs-go/sockjs (from $GOROOT)
        ($GOPATH not set)
make: *_\* [hpfeeds_server] Error 1

how can I solve the problem?

**Comment by Gotric** [comment]
I met the same problem, anybody can solve it?

**Comment by jt6211** [comment]
Please run these commands on these systems and provide the output.

```
cd /opt/honeymap/server
export GOPATH=/opt/honeymap/server
go get
go build
```

**Comment by amidkaraji** [comment]
thats not work 
root@ubuntu:/opt/honeymap/server# cd /opt/honeymap/server
root@ubuntu:/opt/honeymap/server# export GOPATH=/opt/honeymap/server
root@ubuntu:/opt/honeymap/server# go get
 go install: no install location for directory /opt/honeymap/server outside GOPATH

**Comment by d1str0** [comment]
Please try with the latest install script.
