### ISSUE TITLE
mnemosyne FATAL status

### ISSUE THREAD

**Issue by malovisky** [threatstream/mhn#309]
I installed the mhn and mnemosyne is with fatal status.
I'm using ubuntu 12.04.5
In log we can see this:

> File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/init.py", line 36, in 
from gevent.hub import get_hub, iwait, wait
File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in 
import greenlet # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: PyTrash$
Traceback (most recent call last):
File "runner.py", line 18, in 
import gevent
File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/__init_.py", line 36, in 
from gevent.hub import get_hub, iwait, wait
File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in 
import greenlet # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: PyTrash$
Traceback (most recent call last):
File "runner.py", line 18, in 
import gevent
File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/__init_.py", line 36, in 
from gevent.hub import get_hub, iwait, wait
File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/hub.py", line 8, in 
import greenlet # http://pypi.python.org/pypi/greenlet/
ImportError: /opt/mnemosyne/env/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash$

what can I do to fix it?
I tried to update python but  it did not worked.

**Comment by malovisky** [comment]
I fix it.
It was an python version error.

to fix you have to do this steps:

>#python -v (if version is 2.7.3 continue)
>#wget https://www.python.org/ftp/python/2.7.4/Python-2.7.4.tgz
>#tar -zxvf Python-2.7.4.tgz
># cd Python-2.7.4.tgz
> #./configure
>#make
>#make install
>shutdown -r now
>#cd /opt
>#rm -rv mnemosyne
># cd/opt/mhn/scripts
>#./install_mnemosyne
>#shutdown -r now

 and it works ;)

**Comment by f1r3walled** [comment]
Great!
It solved my issue with mnemosyne presenting FATAL status.
I looked on a lot of blog and pages by the solution!

Thanks to you malovisky!

**Comment by X4mp** [comment]
Woked for me too, thx @malovisky
