### ISSUE TITLE
[RFC] ansible role for mhn

### ISSUE THREAD

**Issue by juju4** [threatstream/mhn#316]
Hello,

Just to inform you that I have a role to deploy mhn and mhnclient available.
Continuous integration is available through kitchen/vagrant, kitchen/lxd (preferred) and travis (with glitches)
It also include a packer config for server
https://github.com/juju4/ansible-mhn
https://github.com/juju4/ansible-mhnclient

I did it initially a while ago and refreshed it more recently.
It's not perfect but usable.
Target systems are trusty, xenial and centos7 (partial coverage for last one)

Also, with the way mhnclient is build and essentially with registration at the beginning, there is little testing possible without a server.

might help for
https://github.com/threatstream/mhn/issues/7

**Comment by jt6211** [comment]
@juju4 This is awesome. Thanks for sharing.

**Comment by d1str0** [comment]
Added to wiki. https://github.com/threatstream/mhn/wiki/MHN-With-Ansible
