### ISSUE TITLE
MHN Issue's 

### ISSUE THREAD

**Issue by v0idif** [threatstream/mhn#339]
Hello Everyone,
Few days back i have set up my own MHN on Ubuntu 14 64 bit. Everything was running smoothly when MHN decided to stop working. The issues that came to my attention are the following:

1) hpfeeds-broker                   FATAL      Exited too quickly (process log may have details)

2) mhn-celery-worker                FATAL      Exited too quickly (process log may have details)

3) mnemosyne                        FATAL      Exited too quickly (process log may have details)

Logs:

mhn.log

`  File "./mhn/common/clio.py", line 27, in __init__
    self.client = pymongo.MongoClient()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 369, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: [Errno 111] Connection refused
`

 hpfeeds-broker.log

`oserror [Errno 11] Resource temporarily unavailable: '<pyev.Io object at 0x7f9221c2c838> has been stopped' (11, 'Resource temporarily unavailable')
`
 mnemosyne.err
```
Traceback (most recent call last):
  File "runner.py", line 116, in <module>
    db = mnemodb.MnemoDB(c['mongo_db'])
  File "/opt/mnemosyne/persistance/mnemodb.py", line 37, in __init__
    conn = MongoClient(auto_start_request=False)
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 369, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
```
That had as a result the MHN to stop working and whenever i was trying to connect to the panel i was getting i was getting " Internal Server Error 500"

Any help will be really appreciated of how to fix these issues.

Thanks

**Comment by jt6211** [comment]
This error indicates that mongo is not running, OR it is listening on a different interface than localhost.  I have seen this error before if "localhost" is not setup properly.

I recommend doing this:

Check to see what interface mongo is listening on.

```
sudo netstat -luntp | grep mongo
```

It should be something like this:

```
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      831/mongod      
```

Make sure this in your `/etc/hosts`

```
127.0.0.1 localhost
```

**Comment by v0idif** [comment]
The only listening ports running at the moment are following. It appear mongodb its not running at all.

`PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                                                                                                   1527/sshd
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN                                                                                                                                                                   32297/redis-server
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN                                                                                                                                                                   816/nginx
tcp6       0      0 :::21                   :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                                                                                                   1527/sshd
tcp6       0      0 :::3000                 :::*                    LISTEN                                                                                                                                                                   10028/server
tcp6       0      0 :::1433                 :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::445                  :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::5060                 :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::5061                 :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::135                  :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::3306                 :::*                    LISTEN                                                                                                                                                                   10021/dionaea
tcp6       0      0 :::42                   :::*                    LISTEN                                                                                                                                                                   10021/dionaea
udp6       0      0 :::5060                 :::*                                                                                                                                                                                             10021/dionaea
udp6       0      0 :::69                   :::*                                                                                                                                                                                             10021/dionaea
`

Host file seems to be ok 👍 

>127.0.1.1 MHN-2 MHN-2
127.0.0.1 localhost
 >

**Comment by jt6211** [comment]
we highly recommend that you not run honeypots on the same server as MHN as it causes unexpected issues like this and it makes the honeypots trivial to fingerprint.

**Comment by v0idif** [comment]
well am not running anything else on the server just MHN , with dionaea sensor enabled. thats all.

**Comment by Waseem-farooqui** [comment]
Hey @v0idif  I think you can solve tese issues by first testing and doing following steps.
**mhn-celery-worker** its because of permissions of *mhn.log* so change the ownership this file by using this `chown www-data /var/log/mhn/mhn.log`
**hpfeeds-broker, mnemosyne** It is mostly becz of **mongodb**, mongodb service might not be running you can sheck this by `service mongod status`, start it if it is not starting check the logs most of the times you have not enough space to create journal so delete the previous journal or create a space.
When mongo started than start the supervisor services.

**Comment by starnightcyber** [comment]
I met the similiar problem, that **hpfeeds-broker** and **mnemosyne** cannot start.
```
root@983f7c38775b:/etc/init.d# supervisorctl status
geoloc                           RUNNING   pid 425, uptime 0:20:38
honeymap                         RUNNING   pid 429, uptime 0:20:37
hpfeeds-broker                   FATAL     Exited too quickly (process log may have details)
mhn-celery-beat                  RUNNING   pid 422, uptime 0:20:38
mhn-celery-worker                RUNNING   pid 427, uptime 0:20:37
mhn-collector                    RUNNING   pid 1939, uptime 0:01:07
mhn-uwsgi                        RUNNING   pid 426, uptime 0:20:38
mnemosyne                        FATAL     Exited too quickly (process log may have details)
```
you have to start mongo service first by running `service mongodb start`

then just restart hpfeeds-broker and mnemosyne, it will work as following...
```
root@983f7c38775b:/etc/init.d# supervisorctl restart hpfeeds-broker
hpfeeds-broker: ERROR (not running)
hpfeeds-broker: started
root@983f7c38775b:/etc/init.d# supervisorctl restart mnemosyne
mnemosyne: ERROR (not running)
mnemosyne: started
root@983f7c38775b:/etc/init.d# supervisorctl status
geoloc                           RUNNING   pid 425, uptime 0:22:07
honeymap                         RUNNING   pid 429, uptime 0:22:06
hpfeeds-broker                   RUNNING   pid 2156, uptime 0:00:38
mhn-celery-beat                  RUNNING   pid 422, uptime 0:22:07
mhn-celery-worker                RUNNING   pid 427, uptime 0:22:06
mhn-collector                    RUNNING   pid 1939, uptime 0:02:36
mhn-uwsgi                        RUNNING   pid 426, uptime 0:22:07
mnemosyne                        RUNNING   pid 2185, uptime 0:00:13
```
