### ISSUE TITLE
Honeypot FATAL status

### ISSUE THREAD

**Issue by kainny** [threatstream/mhn#340]
Hello guys!
I have deployed some honeypots(dionaea, p0f, etc) on my VPS, _( Linux version 2.6.32-042stab116.2 (root@kbuild-rh6-x64.eng.sw.ru) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC)_ ) . At first it worked well, when I checked the status, everything was **RUNNING**. But after a few hours, some honeypots were in **FATAL** status, and `supervisorctl restart `just cannot work.
![image](https://cloud.githubusercontent.com/assets/12522550/20592209/351f982a-b267-11e6-9d48-fd4616968409.png)

 And when I try on another VPS_( Linux version 3.2.0-106-generic (buildd@lgw01-60) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) )_ , honeypots are **RUNNING** all the time, but I can only see dionaea events on my map, is there something wrong? 
![image](https://cloud.githubusercontent.com/assets/12522550/20592204/3059498a-b267-11e6-97af-ebcec7a4f2a6.png)

![image](https://cloud.githubusercontent.com/assets/12522550/20592310/b2fb9636-b267-11e6-9964-0e5027b6b0e3.png)
Thank you for your help!

**Comment by kainny** [comment]
I guess I have figured out the first problem .As my VPS is based on OpenVZ container, and has venet Interface, some honeypots like p0f cannot work on it.

**Comment by d1str0** [comment]
Are you still experiencing issues? Closing for now
