### ISSUE TITLE
Raspberry PI 3 

### ISSUE THREAD

**Issue by decker78** [threatstream/mhn#342]
Dear reader,

Sorry for posting this in an issue section on Github but I cannot find a good source to ask the quesiton. Will dionaea run with for example raspbian or archlinux on a Raspberry PI 3?

If not what other good options are there for the Raspberry Pi 3? 

Thanks
Bart

**Comment by lambis7** [comment]
Dionaea runs ok with Raspian. MHN has script for this, named Raspberry - Dionaea
