### ISSUE TITLE
mhn-celery-worker: ERROR (spawn error) - Centos

### ISSUE THREAD

**Issue by NitescuLucian** [threatstream/mhn#345]
So:

[root@localhost ~]# supervisorctl start mhn-celery-worker
mhn-celery-worker: ERROR (spawn error)

[root@localhost ~]# supervisorctl status
geoloc                           FATAL     Exited too quickly (process log may have details)
honeymap                         RUNNING   pid 2305, uptime 0:20:43
hpfeeds-broker                   RUNNING   pid 2299, uptime 0:20:43
mhn-celery-beat                  RUNNING   pid 2298, uptime 0:20:43
mhn-celery-worker                FATAL     Exited too quickly (process log may have details)
mhn-collector                    RUNNING   pid 2304, uptime 0:20:43
mhn-uwsgi                        RUNNING   pid 2302, uptime 0:20:43
mnemosyne                        RUNNING   pid 2300, uptime 0:20:43

[root@localhost ~]# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucp:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
gopher:x:13:30:gopher:/var/gopher:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
vcsa:x:69:69:virtual console memory owner:/dev:/sbin/nologin
rtkit:x:499:496:RealtimeKit:/proc:/sbin/nologin
avahi-autoipd:x:170:170:Avahi IPv4LL Stack:/var/lib/avahi-autoipd:/sbin/nologin
saslauth:x:498:76:Saslauthd user:/var/empty/saslauth:/sbin/nologin
postfix:x:89:89::/var/spool/postfix:/sbin/nologin
ntp:x:38:38::/etc/ntp:/sbin/nologin
haldaemon:x:68:68:HAL daemon:/:/sbin/nologin
gdm:x:42:42::/var/lib/gdm:/sbin/nologin
pulse:x:497:495:PulseAudio System Daemon:/var/run/pulse:/sbin/nologin
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
tcpdump:x:72:72::/:/sbin/nologin
nli:x:500:500:nli:/home/nli:/bin/bash
rabbitmq:x:496:492:RabbitMQ messaging server:/var/lib/rabbitmq:/bin/bash
mongod:x:495:491:mongod:/var/lib/mongo:/bin/false
nginx:x:494:490:Nginx web server:/var/lib/nginx:/sbin/nologin
redis:x:493:489:Redis Server:/var/lib/redis:/sbin/nologin

So? what should I do? .. I am new to Centos and i tried to chown over logs for nginx, nli, root...

**Comment by Philelis** [comment]
>  geoloc FATAL Exited too quickly (process log may have details)

`cat /var/log/mhn/mhn-celery-worker.err 
`
I hope that will help you

**Comment by sanjana-shetty16** [comment]
Hi ,
 I have the same error and when i try to execute the above command in my MHN server i get error saying invalid user 
![1](https://user-images.githubusercontent.com/55754107/70238525-5b584700-1761-11ea-8944-3c4ed9f148f3.PNG)

Please check the file for reference and help me with this
