### ISSUE TITLE
script configuration

### ISSUE THREAD

**Issue by lambis7** [threatstream/mhn#346]
Hi i want to make some changes to the default script which install kippo on Raspberry "Ubuntu/Raspberry Pi - Kippo"

I made my changes to the file /opt/mhn/scripts/deploy_kippo.sh which as i examined it has the script code for deploying kippo on raspberry. I saved my changes, i rebooted the server but then when i run the deploy command from deploy menu for "Ubuntu/Raspberry Pi - Kippo" the default script runs without my changes.

Do i need to change other script?

Or where i can find instructions in order to make my own script from scratch?

**Comment by Antelox** [comment]
In order to save those changes you have to do that through the MHN dashboard: Deploy -> Kippo Raspberry Pi

**Comment by lambis7** [comment]
@Antelox It doesn't read the script directly from the file "/opt/mhn/scripts/deploy_kippo.sh" on mhn server? I made my modofications on that file.

If i modify the script through the MHN dashboard Deploy -> "Ubuntu/Raspberry Pi - Kippo" that changes will take effect as i execute it on my raspberry?

**Comment by Antelox** [comment]
> @Antelox It doesn't read the script directly from the file "/opt/mhn/scripts/deploy_kippo.sh" on mhn server? I made my modofications on that file.

No MHN takes the script content from db, IIRC.

> If i modify the script through the MHN dashboard Deploy -> "Ubuntu/Raspberry Pi - Kippo" that changes will take effect as i execute it on my raspberry?

After that you have made the changes and saved it, take the deploy command and execute it on Raspberry Pi.

**Comment by lambis7** [comment]
@Antelox Can you be more specific on what exactly do i need to change in order to make my changes valid?

I know that after my changes i need to redeploy the command on my raspberry. The problem is that by changing the file mentioned on my first comment, and then redeploying the command on raspberry the script that is executed is again the original and not the one with my changes.

As you can see am a noob on MHN

**Comment by Antelox** [comment]
Go to Deploy -> "Ubuntu/Raspberry Pi - Kippo" and edit there the deploy script through the form which lets show you the code. Save it. Then get the command and execute it in Raspberry Pi. This doesn't work for you?

**Comment by lambis7** [comment]
Now i understand what you ment before. I think that this might be ok.

Thanks a lot!
