### ISSUE TITLE
honeymaps

### ISSUE THREAD

**Issue by 0x7fff9** [threatstream/mhn#358]
This is more a question, not an issue.

So I have a doubt.
On the MHN server, there is a tab called MAP.
There is also another map spawned with python on port 3000 (or any other we decide to configure)

my doubt is, for the MHN to work perfectly do I need the one from pyhton tcp:3000 to run or can I disable it?

What's the difference between the "built in map" that is reachable via https://1.2.3.4/ui/honeymap/ and the one that is reachable via https://1.2.3.4:3000?

What ports of MHN server do I need to expose? 10000 and 443 because my nginx only listens on https?

thanks!!
cheers.

**Comment by juju4** [comment]
/ui/honeymap is calling page on port 3000 so both need to be accessible to your console system unless using a reverse proxy I believe.

**Comment by 0x7fff9** [comment]
Thanks! and is there a need to that port to be forwarded/open so the pots connect to it or can I keep it only LAN reachable?

cheers.

**Comment by juju4** [comment]
10000 port should be reachable by pots (hpfeeds), 3000/443 (honeymap + web console) are only for administration console. both can be restricted by firewall, vpn...

**Comment by 0x7fff9** [comment]
I see!! thanks a lot!!
cheers.
