### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by choquettejm** [threatstream/mhn#360]
when I try to access the MHN main page I am getting an 504 Gateway Time-out nginx/1.4.6 (Ubuntu) error.  My sensors are getting data and are forwarding that data to our Splunk setup.  I just cannot access the main GUI.

**Comment by choquettejm** [comment]
It looks like everything is running:

geoloc                           RUNNING    pid 1137, uptime 1 day, 3:53:03
honeymap                         RUNNING    pid 1168, uptime 1 day, 3:53:03
hpfeeds-broker                   RUNNING    pid 1135, uptime 1 day, 3:53:03
hpfeeds-logger-json              RUNNING    pid 1139, uptime 1 day, 3:53:03
hpfeeds-logger-splunk            RUNNING    pid 1133, uptime 1 day, 3:53:03
mhn-celery-beat                  RUNNING    pid 1132, uptime 1 day, 3:53:03
mhn-celery-worker                RUNNING    pid 1136, uptime 1 day, 3:53:03
mhn-collector                    RUNNING    pid 1340, uptime 1 day, 3:50:38
mhn-uwsgi                        RUNNING    pid 1138, uptime 1 day, 3:53:03
mnemosyne                        RUNNING    pid 1131, uptime 1 day, 3:53:03

**Comment by jt6211** [comment]
I have seen this in the past with MHN systems that either:

1. don't have enough RAM/CPU so mongo queries are very slow.  If this is
the case, consider upgrading your MHN server.

2. Have tons of data (lots of honeypots or just tons of honeypot events
from a small number of systems).  If this is the case, consider aging off
some of the data from Mongo.  Here is a script I used in the past:

set -e

DAYS=30

echo "[`date`] Aging off mnemosyne data ..."
DATE=$(date -d "${DAYS} days ago" +%FT00:00:00.000Z)
echo "[`date`] Deleting session and hpfeeds data older than $DATE..."

for COLLECTION in session hpfeed;
do
    REMOVE_CMD="db.${COLLECTION}.remove( { timestamp: {\$lt:
ISODate(\"${DATE}\") }  } )"
    /usr/bin/mongo mnemosyne --eval "$REMOVE_CMD"
done

echo "[`date`] Deleting precomputed counts for sensors and channels"
DATE=$(date -d "${DAYS} days ago" +%Y%m%d)
REMOVE_CMD="db.counts.remove( { date: {\$lt: \"${DATE}\" }  } )"
/usr/bin/mongo mnemosyne --eval "$REMOVE_CMD"

echo "[`date`] done"

**Comment by f1r3walled** [comment]
That's worked like a charm to me! 
First of all I was facing issues with Mongo stop/waiting status. After solve it I was facing the same issue described by choquettejm.
Now it's fine! Thx Jason!

**Comment by caihuzaimi** [comment]
Jason, 

I am still confused. Where do I put those scripts at? can you share the path..I am still new with this server thing. Please do help.
