### ISSUE TITLE
p0f Fatal Error

### ISSUE THREAD

**Issue by Epicism** [threatstream/mhn#362]
Hello,

I have a number of P0f instances that are not running, with a FATAL status. When I check /var/log/p0f.out I'm seeing:
```
[+] Closed 1 file descriptor.
[+] Loaded 320 signatures from 'p0f.fp'.
[-] PROGRAM ABORT : [+] p0f.hpfeed: Fatal read()
         Location : hpfeed_read_msg(), hpfeed.c:55
```

hpfeeds.c shows:
```
  if (read(s, &msglen, 4) != 4)
    FATAL("[+] p0f.hpfeed: Fatal read()");
```

Thanks

**Comment by d1str0** [comment]
Is this still an issue with the latest versions of MHN's deploy script and p0f?
