### ISSUE TITLE
Log Files

### ISSUE THREAD

**Issue by devinmknights** [threatstream/mhn#363]
I am just wondering if anyone can point me towards the file that is displayed on the attacks report page.  I want to know how many attacks are coming from specific countries, certain ports, the type of honeypot, and the protocol

**Comment by devinmknights** [comment]
Or any commands that would allow me to pull those counts from the database

**Comment by jt6211** [comment]
Please see this page:
https://github.com/threatstream/mhn/wiki/Exporting-Honeypot-Data-from-MHN

**Comment by devinmknights** [comment]
I looked at that however it does not state where that file is saved so that i can copy it off the machine

**Comment by jt6211** [comment]
The data is not stored in a file.  It is stored in Mongo DB and can be
queried either by using Mongo's command line tool or through other
tools/APIs.

**Comment by devinmknights** [comment]
oh okay, any hints on query commands for some of that data? i dont find the mongodb information online to be too helpful

**Comment by jt6211** [comment]
The data on the attacks page comes from the "session" collection in mongo.
So you would either need to create a filter and dump all the session data
to CSV/JSON and analyze it in another tool.

mongoexport --db mnemosyne --collection session
--fields=protocol,source_ip,source_port,destination_port,destination_ip,source_port,honeypot,timestamp,identifier
--csv > data.csv

OR you could use the mongo command line (and a JS program) and try to get
mongo to output just the info you want.  Example:
https://docs.mongodb.com/manual/tutorial/aggregation-zip-code-data-set/

**Comment by ferdasonmez** [comment]
Hi,
In what formats can we generate the mhn.log files? Json, CSV, txt etc??? 
Regards,
Ferda
