### ISSUE TITLE
Celery Worker/ Internal Server Error

### ISSUE THREAD

**Issue by devinmknights** [threatstream/mhn#365]
I am receiving a fatal error for mhn-celery-worker process saying that it is exiting too quickly.  I tried a solution on another issue post and that worked however i was still receiving the "500 internal server error" message every time i tried to access the UI.  And then celery-worker stopped again.

**Comment by devinmknights** [comment]
When looking through the mhn log it says "line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ui/dashboard.html
"

**Comment by jt6211** [comment]
The celery worker should not cause 500 errors on the web app.

500 errors in web app are usually related to mongo not running or a more
recent error we encountered (see fix here
https://github.com/threatstream/mhn/issues/261#issuecomment-279040777)

**Comment by devinmknights** [comment]
Even after performing the fix outlined in the other comment, i am still receiving the same 500 error.  and celery worker is still fatal.  Are there any logs you would need?  The celery log is still saying it cannot find the dashboard.html file even though it does exist in templates

**Comment by jt6211** [comment]
Please share your /var/log/nginx and /var/log/mhn/mhn-uwsgi logs. There are
likely error messages that help to reveal what the problem is. Just the
last 50 lines of each should be needed (tail -n50 FILE)

**Comment by devinmknights** [comment]
Attached is the logs from when i try to access the site.  the nginx error log file was empty so i just put some of the lines from the access file. I also attached the mhn logs and celery logs in case that helps.
[UWSGI.txt](https://github.com/threatstream/mhn/files/774638/UWSGI.txt)
[nginx.txt](https://github.com/threatstream/mhn/files/774639/nginx.txt)
[Celery.txt](https://github.com/threatstream/mhn/files/774651/Celery.txt)
[HMN.txt](https://github.com/threatstream/mhn/files/774652/HMN.txt)

**Comment by devinmknights** [comment]
geoloc                           RUNNING    pid 3005, uptime 3 days, 7:30:45
honeymap                         RUNNING    pid 3009, uptime 3 days, 7:30:44
hpfeeds-broker                   RUNNING    pid 2992, uptime 3 days, 7:30:46
hpfeeds-logger-json              RUNNING    pid 3007, uptime 3 days, 7:30:45
mhn-celery-beat                  RUNNING    pid 2983, uptime 3 days, 7:30:47
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)
mhn-collector                    RUNNING    pid 3008, uptime 3 days, 7:30:45
mhn-uwsgi                        RUNNING    pid 3006, uptime 3 days, 7:30:45
mnemosyne                        RUNNING    pid 2982, uptime 3 days, 7:30:47

mongodb   1278     1  1 Feb09 ?        03:15:09 /usr/bin/mongod --config /etc/mongod.conf
root      3099  3060  0 23:37 pts/0    00:00:00 grep --color=auto mongo

tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1278/mongod

On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    server/mhn/templates/auth/reset-email.html
        deleted:    server/mhn/templates/base.html
        deleted:    server/mhn/templates/pagination.html
        deleted:    server/mhn/templates/security/login_user.html
        deleted:    server/mhn/templates/ui/add-sensor.html
        deleted:    server/mhn/templates/ui/attacks.html
        deleted:    server/mhn/templates/ui/chart.html
        deleted:    server/mhn/templates/ui/dashboard.html
        deleted:    server/mhn/templates/ui/feeds.html
        deleted:    server/mhn/templates/ui/honeymap.html
        deleted:    server/mhn/templates/ui/reset-password.html
        deleted:    server/mhn/templates/ui/reset-request.html
        deleted:    server/mhn/templates/ui/rule_sources_mgmt.html
        deleted:    server/mhn/templates/ui/rules.html
        deleted:    server/mhn/templates/ui/script.html
        deleted:    server/mhn/templates/ui/sensors.html
        deleted:    server/mhn/templates/ui/settings.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ProjectData.csv
        server/collector.json
        server/mhn/ui/templates/

no changes added to commit (use "git add" and/or "git commit -a")


commit 1e6cdf95496de3d0ac862528fc7c0db7d3bde2e4
Merge: 2f4837b ad6b998
Author: Matthew Wollenweber <mjw@insomniac.technology>
Date:   Wed Jan 18 17:31:13 2017 -0600

    Merge pull request #337 from threatstream/LABS-2811

**Comment by jt6211** [comment]
It looks like you deleted the template files. If you restore these it will
likely work.

I believe this command will do it:

git checkout server

**Comment by devinmknights** [comment]
That worked! thank you so much
