### ISSUE TITLE
Emerging Threats list

### ISSUE THREAD

**Issue by f1r3walled** [threatstream/mhn#369]
Hello,
I'm not sure if this is the right section to write about, but if not it can be deleted.
I'm really confused about the ET (Emerging Threats) presented on signatures sections. I "googled" a lot about, but I could not find a list with all meanings.
Can somebody indicate a list with all ET meanings/explanations? I'm confuse and it should help me in an article about honeypots.

Regards

**Comment by d1str0** [comment]
I'm not sure what you mean by this. You can find the newest rules here http://rules.emergingthreats.net/

Basically it's a threat intel feed that updates as new intel comes in and old intel expires.
