### ISSUE TITLE
Disk Space

### ISSUE THREAD

**Issue by sphereict** [threatstream/mhn#371]
Good day

Can you possibly assist with a script that can purge the logs as I have found that the Honeypots being deployed quickly fills up the HDD. 
I would like to free up HDD space lets say every 90 days.

Your assistance will be appreciated. 

Sincerely.
G

**Comment by sphereict** [comment]
Same goes for the management server.

**Comment by juju4** [comment]
for server db, you can use script here
https://github.com/threatstream/mhn/issues/360#issuecomment-274354274

for logs file, you can just customize your logrotate configuration
