### ISSUE TITLE
mhn-celery-worker is fatal

### ISSUE THREAD

**Issue by B00071456** [threatstream/mhn#373]
As follows：

supervisorctl status
geoloc RUNNING pid 30171, uptime 5:21:01
honeymap RUNNING pid 4180, uptime 1:38:23
hpfeeds-broker RUNNING pid 10591, uptime 5:31:13
hpfeeds-logger-splunk RUNNING pid 14010, uptime 0:38:14
mhn-celery-beat RUNNING pid 13707, uptime 0:53:42
mhn-celery-worker FATAL Exited too quickly (process log may have details)
mhn-collector RUNNING pid 13709, uptime 0:53:42
mhn-uwsgi RUNNING pid 13710, uptime 0:53:42
mnemosyne RUNNING pid 28472, uptime 5:22:52

mhn-celery-worker.err as follows:

supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned
supervisor: couldn't chdir to /root/mhn/server: EACCES
supervisor: child process was not spawned

I've already run the chown www-data /var/log/mhn/mhn.log command, then started mhn-celery-worker, but when I run the start command I get the response:

mhn-celery-worker: ERROR (abnormal termination)

Could anyone be able to help with this?

**Comment by jt6211** [comment]
this looks like you have a custom install or modified some configs by hand.  Did you do this?

By default MHN gets installed into /opt.  Any chance you modified some of your supervisor configs (/etc/supervisor/conf.d/*)?

**Comment by Waseem-farooqui** [comment]
Hey @jt6211,

Hope you will be good of your help.
I have a some of-topic questions I need your help.
Kindly share a way I can communicate.
Thanks.

**Comment by jt6211** [comment]
Email the mhn mailing list (modern-honey-network@googlegroups.com) and i
will respond directly to you.

**Comment by dieee** [comment]
I had the same problem why not put the public solution?

**Comment by Waseem-farooqui** [comment]
Share the logs.
`supervisorctl status`

**Comment by d1str0** [comment]
@dieee Are your logs identical? If not, please post them.

**Comment by bharper1976** [comment]
Was there a resolution??? I have rebuit MHN 3 times and everytime you click on attack beside the sensor the system crashes and then get this after restart

mhn-celery-worker                FATAL     Exited too quickly (process log may have details)

**Comment by bbkarabulut** [comment]
Should mhn-celery-worker process be showing as “FATAL”, fret not! Try this instead:
[mhn-server] cd /var/log/mhn/
[mhn-server] sudo chown www-data mhn.log
[mhn-server] sudo supervisorctl start mhn-celery-worker

https://medium.com/@0xson/part-1-modern-honey-network-mhn-installing-server-on-ec2-instance-9144242acbb8
