### ISSUE TITLE
update sensor!

### ISSUE THREAD

**Issue by dpicollege** [threatstream/mhn#374]
Hello,
what is the road map for update deploy sensor script? for example snort 2.9 have lot's of bug when deploy script for snort 3 is available?

**Comment by jjjan** [comment]
it's true most sensor are old and useless. add new ids like bro, and change to new interface and also add more honeypot

**Comment by Philelis** [comment]
I updated suricata and made an Pull Request: [#1](https://github.com/threatstream/suricata/pull/1) @ threatstream:hpfeeds-support

**Comment by d1str0** [comment]
If there are specific deploy scripts you want to see updated, please create an issue listing the specific honeypot and the desired changes.

**Comment by dpicollege** [comment]
hi @d1str0,
great to see you hear. cloud you add such deploy script for below ids and honeypot?
1-glastopf v3 .
2-honeytrap
3-bro ids
4-snort(new deploy script to support last version of snort in new os)
5-passivedns project
6-mailoney (smtp honeypot)

and there is lot's of other project that i can mentioned in future.

thanks indeed
