### ISSUE TITLE
Protocol Identified as PCAP

### ISSUE THREAD

**Issue by robsmallridge** [threatstream/mhn#38]
Protocols are identified as pcap, But perhaps should be identified as TCP/UDP/ICMP etc.

**Comment by aabed** [comment]
I have that issue as well

**Comment by nullprobe** [comment]
Isn't the pcap tagged like that by design?

From http://dionaea.carnivore.it/ : 

>The pcap module uses the libpcap library to detect rejected connection attempts, so even if we do not >accept a connection, we can use the information somebody wanted to connect there.

**Comment by aabed** [comment]
Now I see , thank you very much
