### ISSUE TITLE
Latest update breaks some of the deployment scripts

### ISSUE THREAD

**Issue by islebranch** [threatstream/mhn#382]
According to the installation guide, "Ubuntu 16 is not supported at this time." Since the update 3 months ago, this is not true anymore. The installation even fails on Ubuntu 14 due to this line: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse".

However, after successful deployment on Ubuntu 16, there is no branch for Xenial at http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/ , which make some of the deployment scripts fail, e.g. Dionaea.

**Comment by islebranch** [comment]
That is, unless MHN is supposed to run Xenial and the honeypots Trusty.

**Comment by d1str0** [comment]
Dionaea should work now with Ubuntu 14 with the current install script. Ubuntu 16 is not supported for this honeypot.
