### ISSUE TITLE
encrypt hpfeeds traffic

### ISSUE THREAD

**Issue by 0x7fff9** [threatstream/mhn#389]
Hi, did anyone tried to ecrypt hpfeeds traffic of remote hosts?

What I did:

installed stunnel4, made the appropriate configs at server and client level.
(made the `feedbroker.py` to listen on 127.0.0.1:9999, made stunnel listen on intip:10000, created certs and all ok...)
Made the conf. for clients and everything checks out.

The issue is: the encrypted traffic is not received by the server.

```
tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN      10800/python    
tcp        0      0 172.16.20.10:10000      0.0.0.0:*               LISTEN      11465/stunnel4 
```

```
03:26:32.432947 IP (tos 0x0, ttl 64, id 51524, offset 0, flags [DF], proto TCP (6), length 675)
    172.16.20.11.52168 > 172.16.20.10.webmin: Flags [P.], cksum 0x97b0 (correct), seq 1:624, ack 1, win 229, options [nop,nop,TS val 12523881 ecr 29998567], length 623
<------DATA------>
```

All seems to be working fine, no errors on packet dumps but the MHN server gets no data on MAP not ELK.

<img width="489" alt="image" src="https://cloud.githubusercontent.com/assets/24276463/24833935/026c7c1e-1cd8-11e7-9968-49f4d0b017b1.png">
No data during SSL and data coming back after the config rollback. 

If anyone tried to encrypt this traffic and maybe I am looking at the wrong solution please let me know.

thanks.

Guido.

**Comment by jt6211** [comment]
Honeymap, mnemosyne, and the hpfeeds-logger (used with ELK integration) all
connect to the hpfeeds broker on port 10000 on localhost.  You will need to
either confgure them with stunnel (doesn't seem needed on localhost) or
change their configured hpfeeds port.

**Comment by juju4** [comment]
On my homelab setup, I use openvpn between the different sensors and servers and working well.

stunnel should be fine too but you have to change remote server address (syslog+stunnel example http://www.rsyslog.com/doc/v8-stable/historical/stunnel.html)

**Comment by 0x7fff9** [comment]
Thanks both!
Indeed over OVPN all goes well. I was just looking for as simple/practical way to encrypt traffic leaving for 10000 only with little config on the new sensors deployment.

Ok, I understand now what was wrong as at the test time I had no listener on lo:10000.

I'm gonna test properly today and report back.

thanks!!!

**Comment by 0x7fff9** [comment]
Hi!
even if I change the port to for Honeymap, mnemosyne, and the hpfeeds-logger I still get no data.
I think I will just keep on digging and check what can I do. I am sure I am doing something wrong.

cheers.
Guido.

**Comment by 0x7fff9** [comment]
it really seems hpfeeds is not compatible with stunnel.

On MHN - server:

```
Apr 11 00:38:00 mhn-fe stunnel: LOG7[ui]: Found 1 ready file descriptor(s)
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[ui]: Found 1 ready file descriptor(s)
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[ui]: FD=4 events=0x2001 revents=0x0
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[ui]: FD=7 events=0x2001 revents=0x1
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[ui]: Service [hpfeeds] accepted (FD=3) from 172.16.20.11:47034
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[0]: Service [hpfeeds] started
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG5[0]: Service [hpfeeds] accepted connection from 172.16.20.11:47034
Apr 11 00:38:00 mhn-fe stunnel4[13122]: 2017.04.11 00:38:00 LOG7[0]: SSL state (accept): before/accept initialization
Apr 11 00:38:00 mhn-fe stunnel: LOG7[ui]: FD=4 events=0x2001 revents=0x0
Apr 11 00:38:00 mhn-fe stunnel: LOG7[ui]: FD=7 events=0x2001 revents=0x1
Apr 11 00:38:00 mhn-fe stunnel: LOG7[ui]: Service [hpfeeds] accepted (FD=3) from 172.16.20.11:47034
Apr 11 00:38:00 mhn-fe stunnel: LOG7[0]: Service [hpfeeds] started
```
`tcp        0      0 0.0.0.0:60514           0.0.0.0:*               LISTEN      13137/stunnel4`

```
gg@mhn-fe:/etc/stunnel$ cat /etc/stunnel/hp-feeds.conf 
pid = /var/run/stunnel.pid
cert = /home/gg/stunnel.pem
debug = 7
foreground=yes
[hpfeeds] 
accept = 60514 
connect = 10000
```

On MHN - cowrieHoneyPot:
```
2017-04-11T00:31:03+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2017-04-11T00:39:42+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.1.0 (/opt/cowrie/env/bin/python2 2.7.12) starting up.
2017-04-11T00:39:42+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
```
```
gg@mhn-ssh-pot:/etc/stunnel$ cat /etc/stunnel/hp-feeds.conf 
pid = /var/run/stunnel.pid
debug = 7
foreground=yes
client=yes
[hpfeeds]
accept  = 127.0.0.1:61514
connect = 172.16.20.10:60514
```
basically the conn gets established but for the hpfeeds on cowrie is like it can't connect.

When I restart cowrie via `supervisorctl` it's not coming with the message "ready to accept....".
I will start look at the VPN option.

thanks!

**Comment by d1str0** [comment]
Related to #158
