### ISSUE TITLE
Fight with Dionaea for several months - no results

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#395]
I do not know what to say...

For several months I have been trying to collect malware using Dionaea, but without any results. I do not know what to do anymore. I've been through a lot of guides, many times asking for help, but without success.

The problem is that any malware is not collected. 

I recently set up an MHN server and implemented 2 probes that are in Digital Ocean. Dionaes seems listening on many ports:

```
sudo netstat -luntp | grep dionaea
tcp6       0      0 :::21                   :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::1433                 :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::443                  :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::445                  :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::5060                 :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::5061                 :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::135                  :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::3306                 :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::42                   :::*                    LISTEN      1295/dionaea    
tcp6       0      0 :::80                   :::*                    LISTEN      1295/dionaea    
udp6       0      0 :::69                   :::*                                1295/dionaea    
udp6       0      0 :::5060                 :::*                                1295/dionaea  
```
Many of attacks are collecting and sending to MHN server:

![bbb](https://cloud.githubusercontent.com/assets/25173433/25479945/09f70dfa-2b47-11e7-8c73-72bcdc495e2d.png)

Can someone lead me step by step to locate the source of the problems?

**Comment by Waseem-farooqui** [comment]
contact me at `waseem.farooqui19@gmail.com`

**Comment by br1877** [comment]
The problem was solved. Many thanks for Waseem. This script is out-dated and seems that is not supported for nowadays.

**Comment by haha5566** [comment]
I have same question .Can you tell me how to solve this problem?

**Comment by br1877** [comment]
Waseem has prepared a solution for me. Problem has been solved. But I had to pay for support. So I can not help you.

**Comment by Tigzy** [comment]
Hello same problem here. The project is open source, so please contribute !

**Comment by Waseem-farooqui** [comment]
There are list of things you have to check,

1. Your ports are open specially 445.
2. Your firewall is not blocking the following any port.
3. nmap you IP and check whether your port is filtered or open. (Resolve the issue if filtered.) 

There could be following bugs.
https://curl.haxx.se/mail/tracker-2014-02/0025.html
https://curl.haxx.se/mail/tracker-2010-12/0008.html

**Comment by br1877** [comment]
Possible problem is IPv6. Edit /etc/dionaea/dionaea.conf and change:
listen = .... it should like to:

`addrs = { eth0 = ["0.0.0.0"]}`

Should works now.
