### ISSUE TITLE
No Binaries from Dionaea Sensor

### ISSUE THREAD

**Issue by MNFaust** [threatstream/mhn#397]
I have been running a Dionaea sensor for 24 hours now, with a significant amount of events. It's a digital Ocean box which I have been using for other sensors (cowrie and p0f) and they work just fine but, I can never get Dionaea to capture crap with MHN.

**NMAP scan of the vulnerable Box:**
```
Host is up (0.00047s latency).
Not shown: 990 closed ports
PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
42/tcp   open  nameserver
135/tcp  open  msrpc
445/tcp  open  microsoft-ds
1433/tcp open  ms-sql-s
2222/tcp open  EtherNet/IP-1
3306/tcp open  mysql
5060/tcp open  sip
5061/tcp open  sip-tls

Nmap done: 1 IP address (1 host up) scanned in 0.14 seconds
```

**UFW status:** 
`Status: inactive`

**Comment by dpicollege** [comment]
Dionaea is old now and mhn is being old too

**Comment by MNFaust** [comment]
@dpicollege any recommendations on a better honeypot to catch malware in the wild?

**Comment by dpicollege** [comment]
what kind of opsec are you. kinda new in infosec, student or what every?

**Comment by MNFaust** [comment]
@dpicollege Graduate Student.

**Comment by br1877** [comment]
This Dionaea's version is crap for IPv6. Just delete it - edit /etc/dionaea/dionaea.conf, change:
listen = .... it should like to:
`addrs = { eth0 = ["0.0.0.0"]}`

And that is all. Should works now :)

**Comment by d1str0** [comment]
@MNFaust what do you mean it doesn't "capture crap". Nmap doesn't give it a payload to capture.
