### ISSUE TITLE
Downloading malware captured by Dionaea honeypots

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#399]
I would like to automatically download my captured malware from each honeypots (Dionaea) to another VPS. Is there any way to do that?

**Comment by Tigzy** [comment]
+1, I would like to add my python script for uploading payloads, where can I add it?

**Comment by phlipevil** [comment]
Oa

**Comment by DZKeeper** [comment]
+1

**Comment by bflew** [comment]
I agree, if it logged to a database like it does on honeydrive thatd be cool

**Comment by d1str0** [comment]
@Tigzy if you make a gist we can perhaps add it to the wiki.
