### ISSUE TITLE
Honeymap url

### ISSUE THREAD

**Issue by cdiaz1971** [threatstream/mhn#402]
I am able to access the map by going to http://xxx.xxx.xxx.xxx:3000, but when I click on the map tab on the main URL, which takes me to http://xxx.xxxx.xxx.xxx/ui/honeymap/  I just get a blank page.  Is there a way to access the map from that main page?

Thanks

**Comment by SmUrF3R5** [comment]
It appears that the config.py.template needs to be updated 
From `HONEYMAP_URL = '{{HONEYMAP_URL}}'`
To `HONEYMAP_URL = SERVER_BASE_URL + '{{HONEYMAP_URL}}'`


for now you can correct this issue by editing 
/opt/mhn/server/config.pyc

then find the line
`HONEYMAP_URL = ':3000'`

and change to 
`HONEYMAP_URL = SERVER_BASE_URL + ':3000'`

**Comment by cdiaz1971** [comment]
made the change in /opt/mhn/server/config.py and restarted with:

`sudo supervisorctl restart all` 

That resolved the issue.  Thanks!
