### ISSUE TITLE
Incorrect time on mhn "Attacks" page

### ISSUE THREAD

**Issue by royikle** [threatstream/mhn#405]
Hello,
This is my first time open issues on Github.
If something I say is not good or no manner , just tell me ,thanks. 
I installed MHN and deployed Kippo in Ubuntu 14.04.
And use System Settings to set Time&Date in GMT+8.

`date`
Fri May 26 15:23:37 CST 2017
`sudo hwclock`
Fri 26 May 2017 03:24:07 PM CST  -0.070632 seconds

But the Attacks page is
2017-05-26 07:21:03

I had seem the same issue before. #148 
So I try to modify rules.html & attacks.html like that.
But it's not work.
I have no ideal on it. 
Can somebody help me?

**Comment by Philelis** [comment]
Your time is correct. It is UTC time ;)

**Comment by royikle** [comment]
So my time setting is correct,
Just in MHN show the different time .
Maybe somewhere have configuration file can plus 8 hours on UTC ?
I ask my friend but he didn't have the same problem.
It really make me confuse.

**Comment by royikle** [comment]
I tried other method from google group.
https://groups.google.com/forum/#!searchin/modern-honey-network/time|sort:relevance/modern-honey-network/QRN5dNqMGOU/W0YxhFfgCAAJ
https://groups.google.com/forum/#!searchin/modern-honey-network/time|sort:relevance/modern-honey-network/fLOMBit7KEM/Rhn31TYPBqEJ
It's not work,either.
Maybe I should try to open a new mhn Machine.

**Comment by royikle** [comment]
I solved this problem by studying #148 

In "/opt/mhn/server/mhn/__ init __.py" add:

from mhn.common.templatetags import format_local_date
mhn.jinja_env.filters['fldate'] = format_local_date

In "/opt/mhn/server/mhn/common/templatetags.py" add :

from dateutil import tz

def format_local_date(dt):
    from_zone = tz.tzutc()
    to_zone = tz.gettz('Asia/Taipei')
    utc = dt
    utc = utc.replace(tzinfo=from_zone)
    dt2 = utc.astimezone(to_zone)
    return dt2.strftime('%Y-%m-%d %H:%M:%S')

Modify templates in "/opt/mhn/server/mhn/templates/ui", (rules.html & attacks.html) to use "fldate" instead of "fdate".

Then restart the mhn.
sudo supervisorctl restart all
------------------------------------------------------------------------
But Glastopf timestamp is wrong , I can't fix it by script.
So I change Glastopf's time zone to fit the time I need.
