### ISSUE TITLE
Cowrie Install Script Broken

### ISSUE THREAD

**Issue by jgamblin** [threatstream/mhn#406]
It looks like a recent update to cowrie has caused the automatic installation script to break as start.sh is no longer found: 

```
+ sed -i s/AUTHBIND_ENABLED=no/AUTHBIND_ENABLED=yes/ start.sh
sed: can't read start.sh: No such file or directory
```

**Comment by jgamblin** [comment]
For More Info.... This was a new Ubuntu 16.04 droplet on DO. 
 Here are all the commands that were run: 

```
sudo apt update
sudo apt upgrade -y
sudo apt install python -y
wget "http://honeypot.jgamblin.com/api/script/?text=true&script_id=14" -O deploy.sh && sudo bash deploy.sh http://honeypot.jgamblin.com removed
```

**Comment by RassilonMonk** [comment]
https://github.com/threatstream/mhn/pull/403

**Comment by jgamblin** [comment]
As an FYI I took all the fixes and put them in this shell script: 
https://gist.githubusercontent.com/jgamblin/e2c5432fa4518876c0536b625f90f8da/raw/c96fa946dacbb73b70f30b7fab28fb8d1e86ee3d/cowrie.sh

**Comment by racompton** [comment]
I'd like to know when these changes make it into the main branch.  I have some Dockerfile scripts that are failing because of this issue.  Thanks!

**Comment by d1str0** [comment]
Changes are merged and should now work fine.
