### ISSUE TITLE
Ubuntu Kippo Script Fails

### ISSUE THREAD

**Issue by jgamblin** [threatstream/mhn#408]
The Ubuntu Kippo install script appears to complete correctly but doesn't start completely.  It move the default SSH port to 2222 but doesnt spawn kippo on 22.

**Comment by suwitcham** [comment]
I found kippo.cfg was not copy/create. Only original kippo.cfg.dist found. Not sure if the same case.

**Comment by hackdefendr** [comment]
Kippo uses port 2222 by default.  That is by design.

**Comment by d1str0** [comment]
Cowrie is the latest version of Kippo and we highly recommend you use it instead.
