### ISSUE TITLE
WARNING:root:Disconnecting bad client: ('10.42.16.240', 39742)

### ISSUE THREAD

**Issue by droik123** [threatstream/mhn#410]
Hi, 

Recently I have been observing this error on hpfeeds-broker.err which i was using as an heartbeat.   All the Raspberry Pi Dionaea boxes cannot communicate with the MHN Server for some reason.   On the client I get the error  "hpfeeds dionaea/hpfeeds.py:212-warning: hpclient error 1"

Would request some help to have this issue fixed.   Please note I have reinstalled MHN on the server.

**Comment by droik123** [comment]
New Error that I now see

Traceback (most recent call last):
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 569, in _readable
    self._event('read', data)
  File "/opt/hpfeeds/env/src/evnet/evnet/util.py", line 16, in _event
    cb(*args)
  File "/opt/hpfeeds/env/src/evnet/evnet/mongodb.py", line 118, in read
    p._resolve(buf)
  File "/opt/hpfeeds/env/src/evnet/evnet/promise.py", line 73, in _resolve
    self._call_callbacks()
  File "/opt/hpfeeds/env/src/evnet/evnet/promise.py", line 33, in _call_callbacks
    fn(self._result, *args, **kwargs)
  File "/opt/hpfeeds/broker/feedbroker.py", line 117, in checkauth
    self.io_in(b'')
  File "/opt/hpfeeds/broker/feedbroker.py", line 154, in io_in
    self.error('identfail.')
  File "/opt/hpfeeds/broker/feedbroker.py", line 193, in error
    self.conn.write(self.msgerror(emsg))
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 505, in write
    raise EVException('Already closed.')
EVException: Already closed.
INFO:root:Auth success by hpfeeds-logger-arcsight.
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 290, in <module>
    sys.exit(main())
  File "/opt/hpfeeds/broker/feedbroker.py", line 286, in main
    loop()
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 47, in loop
    l.start()
pyev.Error: unspecified libev error: <pyev.Io object at 0x7f660197fdb8> has been stopped

**Comment by d1str0** [comment]
Can you show the output of 'sudo supervisorctl status' from your MHN box?

Also, please provide the output from the commands here: https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide#troubleshooting-the-honeypot-side

**Comment by closedstack** [comment]
root@localhost:/var/log/mhn# sudo supervisorctl status
geoloc                           RUNNING   pid 703, uptime 0:04:01
honeymap                         RUNNING   pid 712, uptime 0:04:01
hpfeeds-broker                   RUNNING   pid 701, uptime 0:04:01
mhn-celery-beat                  RUNNING   pid 700, uptime 0:04:01
mhn-celery-worker                FATAL     Exited too quickly (process log may have details)
mhn-collector                    RUNNING   pid 706, uptime 0:04:01
mhn-uwsgi                        RUNNING   pid 704, uptime 0:04:01
mnemosyne                        RUNNING   pid 702, uptime 0:04:01
root@localhost:/var/log/mhn# service mhn-celery-worker start
Failed to start mhn-celery-worker.service: Unit mhn-celery-worker.service not found.
root@localhost:/var/log/mhn# sudo supervisorctl status
geoloc                           RUNNING   pid 703, uptime 0:04:31
honeymap                         RUNNING   pid 712, uptime 0:04:31
hpfeeds-broker                   RUNNING   pid 701, uptime 0:04:31
mhn-celery-beat                  RUNNING   pid 700, uptime 0:04:31
mhn-celery-worker                FATAL     Exited too quickly (process log may have details)
mhn-collector                    RUNNING   pid 706, uptime 0:04:31
mhn-uwsgi                        RUNNING   pid 704, uptime 0:04:31
mnemosyne                        RUNNING   pid 702, uptime 0:04:31

**Comment by closedstack** [comment]
had to change ownership and permissions on path to /root/mhn/server. Probably not wise given the install location, but I suppose next time install in non-root user directory
