### ISSUE TITLE
Issue with MHN server install

### ISSUE THREAD

**Issue by Sparks2017** [threatstream/mhn#413]
I followed the installation instructions on the github website, and when I ran the commands:

user@precise64:/opt/mhn/scripts$ sudo /etc/init.d/supervisor status
user@precise64:/opt/mhn/scripts$ sudo supervisorctl status

it reported "/etc/init.d/supervisor: command not found"
I went to the /etc/init.d directory and listed the contents and the supervisor file was not there...

Anyone know what this file is for? Or how I could fix this issue? And what caused it?

**Comment by SmUrF3R5** [comment]
You should be using

sudo supervisorctl status

MHN Troubleshooting
https://github.com/threatstream/mhn/wiki/MHN-Troubleshooting-Guide

**Comment by d1str0** [comment]
Please use the latest install script. If you come across issues, please also say the OS and version you are trying to install on and what steps you have taken.
