### ISSUE TITLE
Dionaea attacks logged into MHN server but payloads are not

### ISSUE THREAD

**Issue by n4x0r** [threatstream/mhn#414]
Hi, Hope you can help me fix this issue I have,
I have been trying to hunt malware with MHN for a while. However, I just can't make it work completely.
On my current setup, dionaea attacks are logged and shown but no payloads are actually submitted into the dionaea.capture panel in MHN server.

I have checked my client and there are no binaries under /var/dionaea/binaries. However, there is stuff logged in /var/dionaea/bistreams.

Is there any way I can fix this and start receiving payloads?

Cheers

**Comment by br1877** [comment]
Or try this solution:
Delete IPv6 from /etc/dionaea/dionaea.conf, change:
listen = .... it should be:
addrs = { eth0 = ["0.0.0.0"]}

And that is all. Should works.

**Comment by JBAnderson** [comment]
Try the steps [Here](http://www.attacusatlas.com/how-to-set-up-dionaea-honeypot-with-modern-honey-network-and-slack-alerts/). Should get you going
