### ISSUE TITLE
Dionaea auth successfull however no attacks in mhn

### ISSUE THREAD

**Issue by DZKeeper** [threatstream/mhn#416]
Good day,

I installed mhn and added an existing dionaea instance to it. I have a few questions:

1- In the view sensors page, I see my sensor, but with a different ip then the sensor ip. It is the ip used to create the sensor entry from the gui. How can it reflect the right ip of the sensor ?

2- My sensor seems to be authentocating correctly as show in : hpfeeds-broker.err with a line similar to this: INFO:root:Auth success by XXXXX-XXXX-XXXX etc...

However, I still get no attacks logged into my mhn instance.

Just not certain if the problem resides with the dionaea instance or mhn ? or a config ?

thanks in advance

**Comment by DZKeeper** [comment]
The problem seems from the dionaea instance, as I commented out the line for dynamic resolution of ips in the hpfeeds config and now event are logging. However, my MHN sensor page still shows the wwrong ip address for the sensor. How to remediate that ?

**Comment by wesleyraptor** [comment]
The MHN app gets the IP address from the client who hits the /api/sensor/ endpoint with a POST request (api/views.py on line 38: sensor.ip = request.remote_addr).

I added an IP address field to the 'Add sensor' form, which required a couple changes to the view, model, and front-end Javascript. I'm not sure it's worth making a pull request for my changes but let me know your thoughts. Alternatively, you could find a way to edit the mhn.db SQLite3 file, where that IP address lives.

Also a sidenote: notice that the IP address of the honeypot you're trying to change is probably the IP address of the workstation you're using :) when you generated the UUID using the MHN server, it populated the IP with the IP address of the client making the request.

**Comment by DZKeeper** [comment]
I finally opted to use the deploy script and thus got the correct ip in the sensors page. Thanks for the response.
