### ISSUE TITLE
Issue incorporating an already deployed Honeypot into MHN

### ISSUE THREAD

**Issue by f1r3walled** [threatstream/mhn#418]
Hello,
I manually deployed cowrie in a VPS, but now I want to see it into MHN sensors.
I tried to follow the steps: https://github.com/threatstream/mhn/wiki/Incorporate-an-already-deployed-Honeypot-into-MHN. The only information that is missing and I`m leaving blank is PUBLISH_CHANNELS and SUBSCRIBE_CHANNELS.
After do it and restart the honeypot, I have the following message:
cowrie@ubuntu:~/cowrie$ bin/cowrie start
Activating virtualenv "cowrie-env"
Starting cowrie: [twistd   -l log/cowrie.log --umask 0077 --pidfile var/run/cowrie.pid cowrie ]...
hpfeeds client init broker cowrie_ipaddress:10000, identifier 89279520.................................................................
hpclient established
'errormessage from server: 617574.....................c2e'

The sensors appears on MHN dashboard, but it is not increasing attacks.
On both sides, MHN and Cowrie, port 10000 is open and connected between these servers.

Does anyone have any idea to help me?

**Comment by wesleyraptor** [comment]
mhn/server/config.py lists the honeypot channels in the HONEYPOT_CHANNELS variable. For cowrie, it looks like you want to specify 1 channel named cowrie.sessions:

HONEYPOT_CHANNELS = {
    'dionaea': [
        'mwbinary.dionaea.sensorunique',
        'dionaea.capture',
        'dionaea.capture.anon',
        'dionaea.caputres',
        'dionaea.connections'
    ],
    'conpot': ['conpot.events'],
    'snort': ['snort.alerts'],
    'kippo': ['kippo.sessions'],
    'cowrie': ['cowrie.sessions'],
    'thug': ['thug.files', 'thug.events'],
    'glastopf': ['glastopf.files', 'glastopf.events'],
    'amun': ['amun.events'],
    'wordpot': ['wordpot.events'],
    'shockpot': ['shockpot.events'],
    'p0f': ['p0f.events'],
    'suricata': ['suricata.events'],
    'elastichoney': ['elastichoney.events'],
}

Hope that helps.

Sidenote: Looks like one of the dionaea channels is misspelled (caputres), however it's not used by the Flask application it seems.

**Comment by mikefozeu** [comment]
Hello,
Please @f1r3walled how did you solve your problem?
Have been blocked with that for days....

**Comment by d1str0** [comment]
For support, please send a detailed email to the mailing list: https://groups.google.com/forum/#!forum/modern-honey-network
