### ISSUE TITLE
Centos 6.5 support for MHN Server

### ISSUE THREAD

**Issue by jt6211** [threatstream/mhn#42]
If you want/need this support.  Comment with a +1 or similar.  It will help us prioritize this with the other items.

**Comment by sgzeng** [comment]
+1

**Comment by shelinlove** [comment]
+1

**Comment by Aliaric** [comment]
+1

**Comment by mofei-123** [comment]
+1

**Comment by d1str0** [comment]
Centos 6.9 should be supported currently.
