### ISSUE TITLE
Manual password reset script does not work.

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#420]
I forgot my login password. I tried to reset it but could not. I followed this steps:

`$ cd $MHN_HOME
$ source env/bin/activate
$ cd server
$ python manual_password_reset.py `

Error:

`Traceback (most recent call last):
  File "manual_password_reset.py", line 1, in <module>
    from flask_security.utils import encrypt_password
ImportError: No module named flask_security.utils
`

**Comment by d1str0** [comment]
Works for me on ubuntu 16.04, make sure you run all commands as root.

https://github.com/threatstream/mhn/wiki/Password-Reset-Without-Web-UI
