### ISSUE TITLE
TOP Attackers API

### ISSUE THREAD

**Issue by br1877** [threatstream/mhn#421]
How to display the number of attacks (from all honeypots) in the last 24 hours using API?

**Comment by masifpak** [comment]
Which API? You want to query dionaea database and kippo database?

**Comment by br1877** [comment]
No, no. I mean API's key which is in "settings" on webpage MHN. This instruction: https://github.com/threatstream/mhn/wiki/MHN-REST-APIs

**Comment by suwitcham** [comment]
API key is in your profile under MHN web console.
