### ISSUE TITLE
Integrate new Dionaea from PPA with MHN

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#425]
Is there any way to integrate a new version Dionaea honeypot (https://github.com/DinoTools/dionaea) with MHN website?

Propably, the Dionaea from MHN's script is no longer support, well I want to integrate the new version with MHN. It is possible?

**Comment by DZKeeper** [comment]
This is the deploy script I use, you would want to change the server_url and deploy_key variable:
`#!/bin/bash

set -e
set -x

server_url="https://changeme.com"
deploy_key="CHANGEME"

wget $server_url/static/registration.txt -O registration.sh
chmod 755 registration.sh
# Note: this will export the HPF_* variables
. ./registration.sh $server_url $deploy_key "dionaea"

if [ -f /etc/debian_version ]; then
    # Add ppa to apt sources (Needed for Dionaea).
    apt-get update
    apt-get install -y python-software-properties software-properties-common python3-requests
    add-apt-repository -y ppa:honeynet/nightly
    apt-get update
    apt-get install -y dionaea
    sed -i "s/hpfriends.honeycloud.net/$HPF_HOST/g" /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml
    sed -i "s/ident: \"\"/ident: \"$HPF_IDENT\"/g" /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml
    sed -i "s/secret: \"\"/secret: \"$HPF_SECRET\"/g" /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml
    sed -i "s/dynip_resolve:/# dynip_resolve:/g" /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml
    ln -s /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml /opt/dionaea/etc/dionaea/ihandlers-enabled/hpfeeds.yaml
    service dionaea restart
    
    sed -i "s/default.levels=all/default.levels=all,-debug/g" /opt/dionaea/etc/dionaea/dionaea.cfg
    sed -i "s/errors.levels=warning,error/errors.levels=error/g" /opt/dionaea/etc/dionaea/dionaea.cfg
   
fi`

**Comment by br1877** [comment]
Should I execute this bash on honeypot VPS? From MHN is necessary UUID and domain only?

**Comment by DZKeeper** [comment]
What you need from MHN is the server url and the server deploy key. Then you run this from your ubuntu 14.04 vps

**Comment by br1877** [comment]
@DZKeeper I do not know what is going on:

`	"name": "Test....", 
	"hostname": "Test....", 
	"deploy_key": "2b5925f25....",
	"honeypot": "dionaea"
}' http://my_IP/api/sensor/
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'uuid'
++ uuid=
`
The UUID is correct, so....

**Comment by DZKeeper** [comment]
@br1877 Dont know either. not much detail in your post.

How did you generate this ?

**Comment by br1877** [comment]
I take you script and saved into empty file named "script". Then I changed UUID and my_MHN_IP server and I run using command "bash script". Tested on Ubuntu 14.04. x64

**Comment by DZKeeper** [comment]
Is is possible that you used a uuid instead of the deploy key ?

**Comment by br1877** [comment]
@DZKeeper It is possible quiet sure. Where I can found deploy key?

**Comment by DZKeeper** [comment]
Hi,

to find the deploy key, you have 2 options:

on your mhn instance, in the file /opt/mhn/server/config.py

OR

in the MHN webgui under the deploy tab, if you choose a script, you will be presented with a deply command. Take the last string of the deploy command, it should be an 8 chars string. Thats your deploy key.

**Comment by br1877** [comment]
Confirm! It is working very well :+1: Thank you very much for script sharing.

**Comment by jjjan** [comment]
great job please add supervisor to deploy script

**Comment by br1877** [comment]
@DZKeeper There is a possibility to change domain / IP for MHN server without reinstall Dionaea? I need to change server for MHN, so honeypots will not be able to send attack information.
