### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ghost** [threatstream/mhn#429]
Everything looks good, but the web-page doesn't works. 

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

```
root@vps:/home/mhn# sudo /etc/init.d/nginx status
 * nginx is running
root@vps:/home/mhn# sudo /etc/init.d/supervisor status
 is running
root@:/home/mhn# sudo supervisorctl status
geoloc                           RUNNING    pid 1548, uptime 0:00:58
honeymap                         RUNNING    pid 1567, uptime 0:00:56
hpfeeds-broker                   RUNNING    pid 1533, uptime 0:00:58
mhn-celery-beat                  RUNNING    pid 1532, uptime 0:00:58
mhn-celery-worker                RUNNING    pid 1558, uptime 0:00:57
mhn-collector                    RUNNING    pid 1563, uptime 0:00:56
mhn-uwsgi                        RUNNING    pid 1553, uptime 0:00:57
mnemosyne                        RUNNING    pid 1541, uptime 0:00:58
```
What should I do next?

**Comment by Ge3kySaint29** [comment]
Check your server url configuration. I know if you are using a VM on a NAT network you need to use the local machine IP to access the web page since you are running MHN on your local machine.

**Comment by br1877** [comment]
No, I'm using VPS with public IP. But the issue has been solved. Indirectly. I had to re-install the entire VPS server. This is not a solution to this problem.

**Comment by bflew** [comment]
I had same issues to resolve I destroyed my VPS and recreated, working fine first install, if you reboot your server it messes up so once its up and running don't reboot

**Comment by M4rvil** [comment]
Same issue, same symptoms while running into Virtualbox. After having a look into mhn.log I realize the problem was...  low space in virtual HD. Increasing space solved the issue. HTH.
