### ISSUE TITLE
install MHN server eeror

### ISSUE THREAD

**Issue by mofei-123** [threatstream/mhn#433]
install MHN server, this is hpfeeds-broker service is not running

root@mofei:/opt/mhn/scripts# supervisorctl status
geoloc                           RUNNING    pid 17621, uptime 0:11:53
honeymap                         RUNNING    pid 17604, uptime 0:11:54
hpfeeds-broker                   FATAL      Exited too quickly (process log may have details)
mhn-celery-beat                  RUNNING    pid 17603, uptime 0:11:54
mhn-celery-worker                RUNNING    pid 17625, uptime 0:11:53
mhn-collector                    RUNNING    pid 17641, uptime 0:11:52
mhn-uwsgi                        RUNNING    pid 17622, uptime 0:11:53
mnemosyne                        RUNNING    pid 17614, uptime 0:11:53

hpfeeds-broker err.log display:

Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Tried the solution：
rm -rf /usr/local/lib/python2.7/dist-packages/OpenSSL/
 apt-get install --reinstall python-openssl

help me ! thks!

**Comment by dimasdanang** [comment]
sudo /opt/hpfeeds/env/bin/python -m pip install --upgrade pyopenssl 
Try this

**Comment by mofei-123** [comment]
thank you very mach! @dimasdanang ！ my question is OK！

**Comment by bflew** [comment]
mofei you should close your ticket if its resolved

**Comment by alicancakil** [comment]
Thanks to dimasdanang, upgrading pyopenssl solved my problem.

**Comment by CoredusK** [comment]
Thanks a lot dimasdanang
