### ISSUE TITLE
deploying honeypots with MHN  faild

### ISSUE THREAD

**Issue by mofei-123** [threatstream/mhn#435]
OS :ubuntu 14.04
InterNet Network:proxy
install:wget "http://x.x.x.x/api/script/?text=true&script_id=12" -O deploy.sh && sudo bash deploy.sh http://x.x.x.x i434QsqI

help me!

error info：
W: GPG error: http://extras.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192
W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-i386/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

`
error:
Connecting to 10.64.113.181:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 16522 (16K) [text/html]
Saving to: ‘deploy.sh’

deploy.sh                       100%[========================================================>]  16.13K  --.-KB/s   in 0.001s 

2017-07-24 16:39:32 (12.0 MB/s) - ‘deploy.sh’ saved [16522/16522]

+ '[' 2 -ne 2 ']'
+ server_url=http://10.64.113.181
+ deploy_key=i4hKQsqI
+ wget http://10.64.113.181/static/registration.txt -O registration.sh
--2017-07-24 16:39:32--  http://10.64.113.181/static/registration.txt
Connecting to 10.64.113.181:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1423 (1.4K) [text/plain]
Saving to: ‘registration.sh’

registration.sh                 100%[========================================================>]   1.39K  --.-KB/s   in 0s     

2017-07-24 16:39:32 (11.2 MB/s) - ‘registration.sh’ saved [1423/1423]

+ chmod 755 registration.sh
+ . ./registration.sh http://10.64.113.181 i4hKQsqI dionaea
++ '[' 3 -ne 3 ']'
++ server_url=http://10.64.113.181
++ deploy_key=i4hKQsqI
++ honeypot=dionaea
+++ hostname
++ hostname=vm172-31-0-19.ksc.com
++ '[' -f /etc/debian_version ']'
++ OS=Debian
++ sudo apt-get install -y curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version.
The following package was automatically installed and is no longer required:
  librtmp0
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
++ curl -s -X POST -H 'Content-Type: application/json' -d '{
        "name": "vm172-31-0-19.ksc.com-dionaea", 
        "hostname": "vm172-31-0-19.ksc.com", 
        "deploy_key": "i4hKQsqI",
        "honeypot": "dionaea"
}' http://10.64.113.181/api/sensor/
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
++ uuid=a01d2ac8-704b-11e7-9b3f-0800274c8ecb
++ '[' -z a01d2ac8-704b-11e7-9b3f-0800274c8ecb ']'
++ set -e
++ echo 'Created sensor: ' a01d2ac8-704b-11e7-9b3f-0800274c8ecb
Created sensor:  a01d2ac8-704b-11e7-9b3f-0800274c8ecb
+++ echo http://10.64.113.181
+++ sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'
++ export HPF_HOST=10.64.113.181
++ HPF_HOST=10.64.113.181
++ export HPF_PORT=10000
++ HPF_PORT=10000
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["identifier"]'
++ export HPF_IDENT=a01d2ac8-704b-11e7-9b3f-0800274c8ecb
++ HPF_IDENT=a01d2ac8-704b-11e7-9b3f-0800274c8ecb
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["secret"]'
++ export HPF_SECRET=GQI6xmxPBvvzs2tS
++ HPF_SECRET=GQI6xmxPBvvzs2tS
+ echo 'deb http://packages.s7t.de/raspbian wheezy main'
+ apt-get update
Ign http://packages.s7t.de wheezy InRelease                                                                     
Ign http://extras.ubuntu.com trusty InRelease                                                                   
Ign http://archive.ubuntu.com trusty InRelease                                            
Ign http://packages.s7t.de wheezy Release.gpg                                              
Ign http://archive.canonical.com trusty InRelease                                          
Get:1 http://extras.ubuntu.com trusty Release.gpg [72 B]                                   
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]                                                   
Hit http://packages.s7t.de wheezy Release                                                                              
Hit http://archive.canonical.com trusty Release.gpg                                                                    
Hit http://extras.ubuntu.com trusty Release                                                            
Ign http://extras.ubuntu.com trusty Release                                                                                   
Hit http://archive.canonical.com trusty Release                                                                               
Ign http://extras.ubuntu.com trusty/main amd64 Packages/DiffIndex                                                             
Ign http://ppa.launchpad.net vivid InRelease                                                           
Ign http://ppa.launchpad.net vivid Release.gpg                                                                                
Ign http://extras.ubuntu.com trusty/main i386 Packages/DiffIndex                                                  
Hit http://archive.ubuntu.com trusty-updates InRelease                                                            
Ign http://ppa.launchpad.net vivid Release                                                                                    
Get:3 http://archive.ubuntu.com trusty-proposed InRelease [65.9 kB]                                               
Hit http://extras.ubuntu.com trusty/main amd64 Packages                                                                       
Hit http://archive.canonical.com trusty/partner amd64 Packages                                                                
Hit http://extras.ubuntu.com trusty/main i386 Packages                                                                        
Hit http://archive.canonical.com trusty/partner i386 Packages                                                                 
Hit http://archive.ubuntu.com trusty-backports InRelease                                                          
Hit http://archive.canonical.com trusty/partner Translation-en                                                                
Hit http://archive.ubuntu.com trusty Release.gpg                                                                  
Get:4 http://archive.ubuntu.com trusty-security/main Sources [134 kB]                       
Ign http://extras.ubuntu.com trusty/main Translation-en_US                                          
Ign http://extras.ubuntu.com trusty/main Translation-en                                             
Err http://ppa.launchpad.net vivid/main amd64 Packages                                                                        
  404  Not Found
Err http://ppa.launchpad.net vivid/main i386 Packages                                                                         
  404  Not Found
Ign http://ppa.launchpad.net vivid/main Translation-en_US                                                                     
Ign http://ppa.launchpad.net vivid/main Translation-en                                                                        
Err http://packages.s7t.de wheezy/main amd64 Packages                                                                         
  404  Not Found
Err http://packages.s7t.de wheezy/main i386 Packages                                                                          
  404  Not Found
Ign http://packages.s7t.de wheezy/main Translation-en_US                                                                      
Ign http://packages.s7t.de wheezy/main Translation-en                                                                         
Get:5 http://archive.ubuntu.com trusty-security/restricted Sources [4,955 B]                                                  
Get:6 http://archive.ubuntu.com trusty-security/universe Sources [59.7 kB]                                                    
Get:7 http://archive.ubuntu.com trusty-security/multiverse Sources [3,189 B]                                                  
Get:8 http://archive.ubuntu.com trusty-security/main amd64 Packages [634 kB]                                                  
Get:9 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.0 kB]                                           
Get:10 http://archive.ubuntu.com trusty-security/universe amd64 Packages [174 kB]                                             
Get:11 http://archive.ubuntu.com trusty-security/multiverse amd64 Packages [4,132 B]                                          
Get:12 http://archive.ubuntu.com trusty-security/main i386 Packages [589 kB]                                                  
Get:13 http://archive.ubuntu.com trusty-security/restricted i386 Packages [13.7 kB]                                           
Get:14 http://archive.ubuntu.com trusty-security/universe i386 Packages [175 kB]                                              
Get:15 http://archive.ubuntu.com trusty-security/multiverse i386 Packages [4,288 B]                                           
Get:16 http://archive.ubuntu.com trusty-security/main Translation-en [342 kB]                                                 
Get:17 http://archive.ubuntu.com trusty-security/multiverse Translation-en [2,201 B]                                          
Get:18 http://archive.ubuntu.com trusty-security/restricted Translation-en [3,491 B]                                          
Get:19 http://archive.ubuntu.com trusty-security/universe Translation-en [101 kB]                                             
Get:20 http://archive.ubuntu.com trusty-proposed/main Sources [115 kB]                                                        
Get:21 http://archive.ubuntu.com trusty-proposed/restricted Sources [782 B]                                                   
Get:22 http://archive.ubuntu.com trusty-proposed/universe Sources [17.3 kB]                                                   
Get:23 http://archive.ubuntu.com trusty-proposed/multiverse Sources [28 B]                                                    
Get:24 http://archive.ubuntu.com trusty-proposed/main amd64 Packages [92.7 kB]                                                
Get:25 http://archive.ubuntu.com trusty-proposed/restricted amd64 Packages [769 B]                                            
Get:26 http://archive.ubuntu.com trusty-proposed/universe amd64 Packages [14.4 kB]                                            
Get:27 http://archive.ubuntu.com trusty-proposed/multiverse amd64 Packages [28 B]                                             
Get:28 http://archive.ubuntu.com trusty-proposed/main i386 Packages [89.8 kB]                                                 
Get:29 http://archive.ubuntu.com trusty-proposed/restricted i386 Packages [772 B]                                             
Get:30 http://archive.ubuntu.com trusty-proposed/universe i386 Packages [14.4 kB]                                             
Get:31 http://archive.ubuntu.com trusty-proposed/multiverse i386 Packages [28 B]                                              
Hit http://archive.ubuntu.com trusty Release                                                                                  
Hit http://archive.ubuntu.com trusty-updates/main Sources                                                                     
Hit http://archive.ubuntu.com trusty-updates/restricted Sources                                                               
Hit http://archive.ubuntu.com trusty-updates/universe Sources                                                                 
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources                                                               
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages                                                              
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages                                                        
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages                                                          
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages                                                        
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages                                                               
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages                                                         
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages                                                           
Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages                                                         
Hit http://archive.ubuntu.com trusty-updates/main Translation-en                                                              
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en                                                        
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en                                                        
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en                                                          
Hit http://archive.ubuntu.com trusty-proposed/main Translation-en                                                             
Hit http://archive.ubuntu.com trusty-proposed/multiverse Translation-en                                                       
Hit http://archive.ubuntu.com trusty-proposed/restricted Translation-en                                                       
Hit http://archive.ubuntu.com trusty-proposed/universe Translation-en                                                         
Hit http://archive.ubuntu.com trusty-backports/main Sources                                                                   
Hit http://archive.ubuntu.com trusty-backports/restricted Sources                                                             
Hit http://archive.ubuntu.com trusty-backports/universe Sources                                                               
Hit http://archive.ubuntu.com trusty-backports/multiverse Sources                                                             
Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages                                                            
Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages                                                      
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages                                                        
Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages                                                      
Hit http://archive.ubuntu.com trusty-backports/main i386 Packages                                                             
Hit http://archive.ubuntu.com trusty-backports/restricted i386 Packages                                                       
Hit http://archive.ubuntu.com trusty-backports/universe i386 Packages                                                         
Hit http://archive.ubuntu.com trusty-backports/multiverse i386 Packages                                                       
Hit http://archive.ubuntu.com trusty-backports/main Translation-en                                                            
Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en                                                      
Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en                                                      
Hit http://archive.ubuntu.com trusty-backports/universe Translation-en                                                        
Hit http://archive.ubuntu.com trusty/main Sources                                                                             
Hit http://archive.ubuntu.com trusty/restricted Sources                                                                       
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/multiverse Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty/main i386 Packages
Hit http://archive.ubuntu.com trusty/restricted i386 Packages
Hit http://archive.ubuntu.com trusty/universe i386 Packages
Hit http://archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/multiverse Translation-en
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Ign http://archive.ubuntu.com trusty/main Translation-en_US                                                                   
Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US                                                             
Ign http://archive.ubuntu.com trusty/restricted Translation-en_US                                                             
Ign http://archive.ubuntu.com trusty/universe Translation-en_US                                                               
Fetched 2,736 kB in 4min 4s (11.2 kB/s)                                                                                       
W: GPG error: http://extras.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192
W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://packages.s7t.de/raspbian/dists/wheezy/main/binary-i386/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by d1str0** [comment]
https://ubuntuforums.org/showthread.php?t=1869890

Does this help?
