### ISSUE TITLE
no install location for directory /opt/honeymap/server outside GOPATH

### ISSUE THREAD

**Issue by amidkaraji** [threatstream/mhn#438]
root@ubuntu:/opt/honeymap/server# cd /opt/honeymap/server
root@ubuntu:/opt/honeymap/server# export GOPATH=/opt/honeymap/server
root@ubuntu:/opt/honeymap/server# go get
go install: no install location for directory /opt/honeymap/server outside GOPATH

**Comment by jjjan** [comment]
learn Linux before post comment!!!

**Comment by d1str0** [comment]
It is unclear what you are asking here.
