### ISSUE TITLE
Error with ./install_mhnserver.sh command

### ISSUE THREAD

**Issue by Kh4ster** [threatstream/mhn#446]
Hi,
When trying to install MHN server using this command  
` ./install_mhnserver.sh` (following this [guide](https://github.com/threatstream/mhn/wiki/Getting-up-and-running-using-Vagrant))
I get python error, namely : 
```
Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 24, in <module>
    mhn.config.from_object('config')
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/opt/mhn/server/config.py", line 18
SyntaxError: Non-ASCII character '\xc3' in file /opt/mhn/server/config.py on line 18, but no encoding declared; see htt
p://www.python.org/peps/pep-0263.html for details
```
Does anyone have any idea how to fix this ? 
It might be useful to note that I already tried before to run this command and failed and did everything once again so it might have created some issues that would explain this.

Thank you

**Comment by d1str0** [comment]
It looks like you might have a unicode character in your config file.  Can you double check that config.py doesn't have any unicode? 

A brief google search and I see that '\xc3' might be the first byte in the "é" character. Is there any chance this character is in your config file?

**Comment by d1str0** [comment]
Closed until further information is provided.
