### ISSUE TITLE
What is different between two honey pot in MHN deploy

### ISSUE THREAD

**Issue by royikle** [threatstream/mhn#447]
Hello everyone ,
When I try to deploy dionaea , I notice there are two dionaea in "Select Script".
One is Ubuntu - Dionaea , another is Ubuntu - Dionaea with http.
What is different between this two script ?
Is version ? or function ? or something else?

And I have same problem in kippo.
What is different between Ubuntu - Kippo as vulnerable Juniper Netscreen and Ubuntu/Raspberry Pi - Kippo

**Comment by suwitcham** [comment]
Kippo: prompt will show differently one try to simulate netscreen router.
Dionaea with HTTP will include web emulate and your can put page under wwwroot.

**Comment by royikle** [comment]
If I want to get more information , I need to choose Kippo as vulnerable Juniper Netscreen.
It seems more function more better.
So if I'm good at Dionaea with HTTP , I can use dionaea replace glastopf ?

**Comment by d1str0** [comment]
Closing as this is not an issue
