### ISSUE TITLE
Cannot get Dionaea to deploy

### ISSUE THREAD

**Issue by dgj918** [threatstream/mhn#448]
I have been wrestling with MHN and Dionaea for a week now and still cannot seem to get it right. I have got MHN up and running with the following results:

```
geoloc                               RUNNING   pid 4168, uptime 0:53:56
honeymap                         RUNNING   pid 4172, uptime 0:53:55
hpfeeds-broker                 RUNNING   pid 4166, uptime 0:53:56
mhn-celery-beat               RUNNING   pid 4165, uptime 0:53:56
mhn-celery-worker           RUNNING   pid 4170, uptime 0:53:55
mhn-collector                   RUNNING   pid 4171, uptime 0:53:55
mhn-uwsgi                        RUNNING   pid 4169, uptime 0:53:56
mnemosyne                      RUNNING   pid 4167, uptime 0:53:56

netstat -luntp | grep 10000
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN 

tail -f hpfeeds-broker.err
INFO:root:Database ready.
INFO:root:Auth success by mnemosyne.
INFO:root:Auth success by honeymap.
INFO:root:Auth success by geoloc.
INFO:root:Auth success by collector.
INFO:root:Database ready.
INFO:root:Auth success by honeymap.
INFO:root:Auth success by mnemosyne.
INFO:root:Auth success by geoloc.
INFO:root:Auth success by collector.

```

I cannot however get Dionaea up and running on the sensor sever. I am using Ubunto 16.04.3 x64 for the sensor server. When I run the deploy script I cannot seem to get Dionaea actually running. Any advice or somewhere with clearer instructions to get Dionaea running and connected to MHN?

**Comment by suwitcham** [comment]
Any error when deploy sensor? I got error message about verified source with my new deployment.

**Comment by dgj918** [comment]
This was the only error messages I saw during deployment:


W: The repository 'http://ppa.launchpad.net/honeynet/nightly/ubuntu zesty Releas                                             e' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potential                                             ly dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                             ils.
E: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/zesty/                                             main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used                                              instead.

**Comment by suwitcham** [comment]
same error, still find solution.

**Comment by izotope115** [comment]
I'd highly recommend looking at this article: 
https://www.attacusatlas.com/how-to-set-up-dionaea-honeypot-with-modern-honey-network-and-slack-alerts/

I was able to get MHN and Dionaea running and capturing malware. 

Hope it helps,

Gabe

**Comment by suwitcham** [comment]
I use the same for one of my honeypot and start from last week I found it failed on apt-get.

sudo add-apt-repository ppa:honeynet/nightly

have't troubleshoot yet. Any issue on repository? 

Suwitcha

**Comment by dgj918** [comment]
Thanks for the article Gabe! Got it to work with a few modifications and going through the steps slowly.

**Comment by suwitcham** [comment]
How you fix with manual install? I still got an error about "release files" Have you bypass it?

**Comment by d1str0** [comment]
@suwitcham Dionaea does not have a binary ready for 16.04. 14.04 should work using the current install script or by following the previously linked article. For 16.04, you can probably get it working by compiling from source.
