### ISSUE TITLE
mnemosyne connection refused to localhost

### ISSUE THREAD

**Issue by hackdefendr** [threatstream/mhn#449]
OK

mnemosyne is attempting to connect to hpfeeds via localhost port 10000. However hpfeeds is listening on 0.0.0.0 port 10000 which is causing the connection refused.

/var/log/mhn/mnemosyne.err
`2017-08-31 15:08:43,654 (pyhpfeeds) connecting to localhost:10000
Traceback (most recent call last):
  File "/opt/mnemosyne/env/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/gevent/socket.py", line 344, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused`

How can I force hpfeeds to listen on localhost or tell mnemosyne to not request via localhost?

Thanks

**Comment by d1str0** [comment]
I could be wrong, but I don't think that is the issue. Can you confirm that hpfeeds is running on your MHN box?

    sudo supervisorctl status

This should show all services as RUNNING
