### ISSUE TITLE
CRC check failed  after sudo ./install_mhnserver.sh

### ISSUE THREAD

**Issue by MonkeyButler** [threatstream/mhn#45]
Exact error:
IOError: CRC ceck failed 0x808f37b != 0x9423e077L

I get the above error while running the install_mhnserver.sh, after filling in the MHN configuration info.  This happens on both the Vagrant Install, and a fresh Ubuntu 14.04.1 Server VBox Install.

**Comment by d1str0** [comment]
Please try with the latest code
