### ISSUE TITLE
Honeymap give a blank page.

### ISSUE THREAD

**Issue by battletux** [threatstream/mhn#450]
I've a new mhn install on a site using HTTPS. Everything is going well, except that the map just shows an empty page. No map loads or shows attacks.

My sensors are feeding data and they are not on public IPs. Really not sure why this is not working, does anyone have any advice?

**Comment by suwitcham** [comment]
Have you try to access to map with preconfig tcp port? in my case is 3000

**Comment by battletux** [comment]
Figured it out.

As I am running over HTTPS I followed the instructions on the wiki and the honeymap is running on port 8443. I need to update the config and restart the script to fix it (I hope).

**Comment by battletux** [comment]
Ok I take that back. After updating the config to use https:<domain>:8443 instead of https://<domain>:3000 it still wont display the page after restarting mhn-uwgsi.

I can see the map via https://<domain>:8443 directly now. Any idea how I can have it display within the dashboard?

**Comment by ocramuias** [comment]
Have edit configuration file: /opt/mhn/server/config.py  ?

You need put new url in this var HONEYMAP_URL = "https://:8443"

Next you need restart mhn gui services.

**Comment by d1str0** [comment]
Honeymap config needs improvement for sure

**Comment by archerming** [comment]
i have the same problem.have any ways to solve it？

**Comment by archerming** [comment]
( ⊙ o ⊙ )！，i know the my problem, my SERVER_BASE_URL and HONEYMAP_URL did not add http://
