### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by vr6syncro** [threatstream/mhn#457]
Have this Error

`Command "/opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8aNLmT/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bf66La-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python2.7/uWSGI" failed with error code 1 in /tmp/pip-build-8aNLmT/uWSGI/
`

**Comment by d1str0** [comment]
Please provide the OS version you are attempting to install on.

**Comment by d1str0** [comment]
Closed until further information is provided.

**Comment by Ben-Winn** [comment]
Test Comment
