### ISSUE TITLE
Add new honeypot and ids

### ISSUE THREAD

**Issue by dpicollege** [threatstream/mhn#462]
Hello, 
According to your response about update new script of MHN project " If there are specific deploy scripts you want to see updated, please create an issue listing the specific honeypot and the desired changes."
i have some suggestion that may you update and improve MHN project

1- change the map and make it more interactive and show threat in log not just connection
PLEASE make map like 
https://threatmap.checkpoint.com/ThreatPortal/livemap.html
http://threatmap.fortiguard.com/

2- add new honeypot and ids for example

2-1-glastopf v3 .
2-2:honeytrap
2-3:bro ids
2-4: snort 3(new deploy script to support last version of snort in new os)
2-5:passivedns project
2-6:mailoney (smtp honeypot)

3- also add new technology like http://docs.opencanary.org/en/latest/ and honeytocken.

4- please update splunk app for new honeypot

and the project need lot's of improvment that you know about it. update the managment interface and rest api.

Thanks indeed

**Comment by d1str0** [comment]
This is too broad a request. Will be closing this and creating separate requests for the honeypot upgrades.
