### ISSUE TITLE
MHN Install fails on Ubuntu 14/16

### ISSUE THREAD

**Issue by d1str0** [threatstream/mhn#479]
Install currently fails on hpfeeds + evnet installation:

urllib2.HTTPError: HTTP Error 403: SSL is required

**Comment by d1str0** [comment]
As to why it has only *just* came up as an issue:

https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html

**Comment by RedolentSun** [comment]
I was able to fix it you need to edit ez_setup in hpfeeds-logger repo and make the default_url = https....
same on the evnet repo which I cloned and edited distributed_setup.py the same way. lastly on mhn server requirements.txt edit hpfeeds-logger to git+"repo of edited hpfeeds-logger"

**Comment by d1str0** [comment]
Fixed.
