### ISSUE TITLE
mnemosyne Fatal Error

### ISSUE THREAD

**Issue by tommytee89** [threatstream/mhn#486]
Running Ubuntu 14.04 x64. 

Clean install, immediately after install completes running the supervisor status: 

geoloc                           RUNNING    pid 32247, uptime 0:11:02
honeymap                         RUNNING    pid 32229, uptime 0:11:03
hpfeeds-broker                   RUNNING    pid 32278, uptime 0:11:00
mhn-celery-beat                  RUNNING    pid 32228, uptime 0:11:03
mhn-celery-worker                RUNNING    pid 32262, uptime 0:11:01
mhn-collector                    RUNNING    pid 32267, uptime 0:11:00
mhn-uwsgi                        RUNNING    pid 32249, uptime 0:11:01
mnemosyne                        FATAL      Exited too quickly (process log may have details)

Log file references the magic library: 

  GNU nano 2.2.6             File: mnemosyne.err

    raise ImportError('Unable to find magic library')
ImportError: Unable to find magic library
Traceback (most recent call last):
  File "runner.py", line 29, in <module>
    from normalizer.normalizer import Normalizer
  File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
    from modules import glastopf_files
  File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <modu$
    import magic
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic/__init__.py"$
    from magic.identify import Magic, MagicError
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic/identify.py"$
    from magic import api
  File "/opt/mnemosyne/env/local/lib/python2.7/site-packages/magic/api.py", lin$
    raise ImportError('Unable to find magic library')
ImportError: Unable to find magic library

**Comment by d1str0** [comment]
What's the full version number of the system? Is it fully up to date when you first try and install?

**Comment by tommytee89** [comment]
Ubuntu 14.04.5 LTS (GNU/Linux 2.6.32-042stab120.19 x86_64)

Fresh install with update, and upgrade.

**Comment by d1str0** [comment]
Very strange. Can't reproduce on DigitalOcean droplets. @tommytee89 are you using AWS?

**Comment by tommytee89** [comment]
No another cloud provider. Will a 10$ instance run MHN ? Happy to spin one up to test.

**Comment by tommytee89** [comment]
All working now, not sure what the issue was. Think it was hardware in the end. Thanks
