### ISSUE TITLE
dionaea fails to install on Ubuntu 16 and Centos 6.9

### ISSUE THREAD

**Issue by d1str0** [threatstream/mhn#488]
## Ubuntu 16
add-apt-repository -y ppa:honeynet/nightly most likely causing failure as it's not showing binaries for 16.04

## Centos 6.9
`+ easy_install supervisor                          
Searching for supervisor                           
Reading http://pypi.python.org/simple/supervisor/  
Couldn't find index page for 'supervisor' (maybe misspelled?)                                         
Scanning index of all packages (this may take a while)                                                
Reading http://pypi.python.org/simple/             
No local packages or download links found for supervisor                                              
error: Could not find suitable distribution for Requirement.parse('supervisor') `

**Comment by NitescuLucian** [comment]
any hints on this one?

**Comment by Luckygecko** [comment]
see:  https://github.com/threatstream/mhn/issues/522

**Comment by orhiee** [comment]
had the same issue, try ubuntu 14

**Comment by superATM** [comment]
> 
> 
> had the same issue, try ubuntu 14

I have the same issue by using ubuntu14 , Is there any solution？
