### ISSUE TITLE
Fails to install  on Raspbian GNU/Linux 9

### ISSUE THREAD

**Issue by xyzeugene** [threatstream/mhn#505]
N: Skipping acquire of configured file '10gen/binary-armhf/Packages' as repository 'http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist InRelease' doesn't support architecture 'armhf'
+ apt-get install -y mongodb-org
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mongodb-org

**Comment by d1str0** [comment]
Pull requests are welcome. Currently we only plan to support Ubuntu 14.04, 16.04 and Centos 6.9

**Comment by Seechay** [comment]
I'm in the process of installing it myself on Stretch. I've added backports for Jessie and changed the install scripts to use mongodb instead of mongodb-org and that allowed me to jump that hurdle. I've also had to update the uwsgi version to 2.0.15 in the requirements.txt.

**Comment by KyleSponz** [comment]
Im having this issue as well Ive modfied the install_mongodb.sh script and it does install mongodb but Im not seeing where it is installing the rest of the components.

**Comment by KyleSponz** [comment]
I fixed this in pull request 514, if you guys have any critiques let me know!
