### ISSUE TITLE
install_hpfeeds.sh failed with urllib2.HTTPError:HTTP Error 403:SSL is required

### ISSUE THREAD

**Issue by gzygwx** [threatstream/mhn#507]
When i install hpreef ， it failed with Command "python setup.py egg_info" failed with error code 1 in /opt/hpfeeds/env/src/evnet

**Comment by d1str0** [comment]
What operating system and specs? I was not able to reproduce on latest commit using a $10 droplet on Digital Ocean, Ubuntu 16.04.
