### ISSUE TITLE
How to create custom HPfeed channels?

### ISSUE THREAD

**Issue by JBAnderson** [threatstream/mhn#511]
I am able to publish to hpfeeds using the “dionaea.*” channels, however I would like to create custom channels for my own honeypot project. Any guidance on how to achieve this? Thanks!

**Comment by d1str0** [comment]
This page helped me.
https://github.com/threatstream/mhn/wiki/Add-Support-for-New-Sensors-to-the-MHN
 Let me know if you have further questions.
