### ISSUE TITLE
ConPot is not working?

### ISSUE THREAD

**Issue by helience** [threatstream/mhn#517]
Hello, 

I'm sorry before if my English is very bad,

I want to ask, I just installed MHN on Ubuntu 14.04 64bit on DigitalOcean with $5 for 1GB RAM and 25GB SSD.  I updated and upgrade Ubuntu, then install git then clone MHN, then I installed hpfeeds, mnemosyne and honeymap, after that I installed MHN, and deploy Dionaea, Snort and ConPot. I checked supervisorctl and restarted conpot to work. then I tested using nmap scan from port 1-1000, but no Siemens S7 or modbus is open, all closed. I set ignore_rfc1918 to false in mnemosyne.cfg, also change http port listen to 8080 in /etc/nginx/sites-enabled/default , scanned and the port is still close. How to open port 102 and 502? using listen with netcat but not working.

Sorry for my bad English.

**Comment by d1str0** [comment]
Are you running Dionaea Snort and Conpot all on the same server as MHN? It is *highly* recommended to use a separate machine for each honeypot, but especially a separate machine for honeypots vs. MHN.
