### ISSUE TITLE
Cannot deploy client - could not create sensor error

### ISSUE THREAD

**Issue by coonsmatthew** [threatstream/mhn#520]
Hello all, 

I'm trying to deploy a Kippo sensor on a raspberry pi 3. I've got rasbian installed on the honeypot, but for some reason when I call the oneliner, the install script stops. 

Here's what my output looks like (last bit of the output): 

```
+ chmod 755 registration.sh
+ . ./registration.sh https://servername.domain.com key kippo
++ '[' 3 -ne 3 ']'
++ server_url=https://servername.domain.com
++ deploy_key=key
++ honeypot=kippo
+++ hostname
++ hostname=sensor1
++ '[' -f /etc/debian_version ']'
++ OS=Debian
++ sudo apt-get install -y curl python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u2).
python is already the newest version (2.7.13-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
++ curl -s -X POST -H 'Content-Type: application/json' -d '{
	"name": "sensor1-kippo", 
	"hostname": "sensor1", 
	"deploy_key": "key",
	"honeypot": "kippo"
}' https://servername.domain.com/api/sensor/
```

If I try to run the registration.sh command directly, I get this output: 

```
sudo bash registration.sh https://server.domain.com/api/sensor/ key kippo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u2).
python is already the newest version (2.7.13-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Could not create sensor using name "sensor1".
```

The ONLY thing I changed in the deploy script was adding "--no-check-certificate" on the first wget command that pulls the registration.sh file. Would that have broken anything?

**Comment by coonsmatthew** [comment]
It seems that my issue was related to the curl command in the registration.sh script. I had to add a flag to not check the SSL certificate as the scripts seem to want to use my server's IP address, but it actually has a registered domain name with SSL. 

Is there a way to update the deploy scripts to use my MHN management server's URL and not its IP address?

**Comment by d1str0** [comment]
You should be able to call the one-liner script using your domain name. Something like this:

`wget "https://mhn.threatstream.com/api/script/?text=true&script_id=13" -O deploy.sh && sudo bash deploy.sh https://mhn.threatstream.com secret-gibberish`

**Comment by coonsmatthew** [comment]
Hello, 

Thank you for the response. I'm more interested in how I can modify the default "deploy" URL's that are displayed when when you go to the deploy page in the MHN web UI. I'm guessing that's something that is configured when MHN is installed, but I'm not sure if that is maintained in a config file somewhere? 

Thank you.

**Comment by coonsmatthew** [comment]
@d1str0 Any ideas on this one? I'm guessing the "deploy" URL is stored in a database table somewhere?

**Comment by coonsmatthew** [comment]
Got it. 

The URL can be changed in this file: `/opt/mhn/server/config.py`
