### ISSUE TITLE
pyev upstream not available?

### ISSUE THREAD

**Issue by juju4** [threatstream/mhn#521]
My travis scheduled run tests failed today on pyev

```
stdout: Processing /opt/evnet\nCollecting pyev>=0.5.3-3.8 (from evnet==1.0.post5)\n\n:stderr:   Could not find a version that satisfies the requirement pyev>=0.5.3-3.8 (from evnet==1.0.post5) (from versions: )\nNo matching distribution found for pyev>=0.5.3-3.8 (from evnet==1.0.post5)\n"
```

and it seems not available anymore. standard pages returning 404
https://pypi.python.org/pypi/pyev/
https://pythonhosted.org/pyev/
https://www.versioneye.com/python/pyev/0.9.0

some github forks found
https://github.com/gabrielfalcao/pyev
https://github.com/kbandla/pyev/tree/master/pyev-0.9.0

any ideas what's going on?

**Comment by JohnSmith94** [comment]
I'm having this same issue when trying to install MHN unable to get paste the pyev dependancy.

**Comment by JeanFrancoisMaes** [comment]
same problem here..

**Comment by JeanFrancoisMaes** [comment]
@d1str0  maybe you know what to do? 👍

**Comment by mstoetz1** [comment]
I think this issue just started.. I had success on the weekend.
Error running sudo ./install.sh

Obtaining evnet from git+https://github.com/threatstream/evnet.git#egg=evnet-dev
  Cloning https://github.com/threatstream/evnet.git to ./env/src/evnet
Collecting pyev>=0.5.3-3.8 (from evnet)
  Could not find a version that satisfies the requirement pyev>=0.5.3-3.8 (from evnet) (from versions: )
No matching distribution found for pyev>=0.5.3-3.8 (from evnet)

**Comment by norn93** [comment]
Same problem here.

**Comment by JohnSmith94** [comment]
got this work around from someone at the google group ant it worked for me

"Hello

I had the same error. I was able to fix it by manualy installing the needed dependency.

After cloning the MHN git repository go to <path_to_folder>/mhn/scripts, here you need to edit the install_hpfeeds.sh file.

pip install cffi
pip install pyopenssl==17.3.0
pip install pymongo
           **pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev** 
pip install -e git+https://github.com/threatstream/evnet.git#egg=evnet-dev
pip install .
deactivate

The Bold line is the line you need to add to this file. Now you should be able to install.
"

**Comment by JeanFrancoisMaes** [comment]
@JohnSmith94 this worked for me, thanks! :)

**Comment by mstoetz1** [comment]
Thank you from me too.. worked great!

**Comment by mstoetz1** [comment]
Actually, the MHN installed worked, but now some of the honeypots (have issues with getting their sources (http://ppa.launchpad.net/honeynet/nightly/ubuntu)

**Comment by Schillers** [comment]
@JohnSmith94 Gret fix, thanks!

**Comment by xxmoC** [comment]
Same error

**Comment by d1str0** [comment]
PR merged. Should work fine now.

**Comment by Agatsu42** [comment]
I just cloned the MHN repo this morning and ran the install. When it hits the clone of pyev.git, it prompts me for a username and pw, then fails with:
+ pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev
Obtaining pyev from git+https://github.com/HurricaneLabs/pyev.git#egg=pyev
  Cloning https://github.com/HurricaneLabs/pyev.git to ./env/src/pyev
Username for 'https://github.com': xxxxxxxxx
Password for 'https://xxxxxxxx@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/HurricaneLabs/pyev.git/' not found
Command "git clone -q https://github.com/HurricaneLabs/pyev.git /opt/hpfeeds/env/src/pyev" failed with error code 128 in None
Sorry if this is a newb issue, but the pyev dependency looked like it was spotted and fixed, but I didi't see any mention of username and PW coming up. Thanks for any help

**Comment by adenvoice** [comment]
**pyey.get new repo address**
pip install -e git+https://github.com/couozu/pyev.git#egg=pyev

**Comment by antonio12PR** [comment]
pip install cffi
pip install pyopenssl==17.3.0
pip install pymongo
pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev
pip install -e git+https://github.com/threatstream/evnet.git#egg=evnet-dev
pip install .
deactivate 
I got the same issue even though my file looked like this, what I did was replace https://github.com/HurricaneLabs/pyev.git#egg=pyev with https://github.com/couozu/pyev.git#egg=pyev
worked
