### ISSUE TITLE
No config options during install

### ISSUE THREAD

**Issue by rshalayda** [threatstream/mhn#523]
I am trying to install MHN  on digital ocean-im using putty- everything is fine except when i run the install script i never get any config options. I get a lot of script running that ends with this-

 mongodb.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongodb.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-02-11 01:17:20 UTC; 61ms ago
 Main PID: 11121 (mongod)
    Tasks: 3
   Memory: 9.7M
      CPU: 24ms
   CGroup: /system.slice/mongodb.service
           └─11121 /usr/bin/mongod --quiet --config /etc/mongod.conf

oh yeah im using ubuntu 16.04. Really need help on this

**Comment by irinicd** [comment]
I didn't get the config options during installation either.
Go to: <path_to_mhn>/mhn/server
Try running: sudo python generateconfig.py

**Comment by rshalayda** [comment]
I found the issue- user error, i wasnt waiting long enough for everything to finish running
