### ISSUE TITLE
Error during install:  Could not find a version that satisfies the requirement pyev>=0.5.3-3.8

### ISSUE THREAD

**Issue by alikat500** [threatstream/mhn#525]
Hi,

I received the following message after running the install script:

...
+ pip install -e git+https://github.com/threatstream/evnet.git#egg=evnet-dev
Obtaining evnet from git+https://github.com/threatstream/evnet.git#egg=evnet-dev
  Cloning https://github.com/threatstream/evnet.git to ./env/src/evnet
Collecting pyev>=0.5.3-3.8 (from evnet)
  Could not find a version that satisfies the requirement pyev>=0.5.3-3.8 (from evnet) (from versions: )
No matching distribution found for pyev>=0.5.3-3.8 (from evnet)

I searched for solution and found a reference on following link:

https://github.com/threatstream/mhn/issues/521

Adding the follwoing line to install_hpfeeds.sh:

pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev

I did so and ran the install script again. I did not receive the error.

However, I did not receive a message indicating that install was "successful" or "completed".

I was able to browse to http://myMHNserverIP:3000 and see the map.

However, when I browsed to http://myMHNseverIP, I only saw the nginx default install page.

when I ran 'sudo supervisorctl status', only four out of eight services  were running:

geoloc
honeymap
hpfeeds-broker
memosye

I wiped off the vm and ran the install again without adding the following line:

pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev

I received the same error message:

 Could not find a version that satisfies the requirement pyev>=0.5.3-3.8 (from evnet) (from versions: )
No matching distribution found for pyev>=0.5.3-3.8 (from evnet)

My virtual server is running:

lsb_release -a:
..
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

uname -a:
.. 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Regards,

**Comment by d1str0** [comment]
Have you tried wiping the VM and doing a fresh install of MHN *with* adding in that line?

**Comment by alikat500** [comment]
Yes. Actually I tested it a fresh Ubuntu server 14.04 install as well, the same error.

**Comment by alikat500** [comment]
A couple of points and a question (about high CPU usage)

I had the following message when the install script stopped:

./install_mhnserver.sh: line 70: 10838 Killed                  python initdatabase.py  

Per comment in following post pointing to more memory needed I created a new vm with 1 GB of memory and did not receive the message above.

https://github.com/threatstream/mhn/issues/502

[And thanks for adding the egg=pyev line to install_hpfeeds.sh file!]

During the install the script stopped at:

...
+ systemctl status mongodb
● mongodb.service - High-performance, schema-free document-oriented database
...
... systemd[1]: Started High-performance, schema-free document-oriented databas
lines 1-11/11 (END)

I hit the q key and the script continued.

Question:

celery is using over 98% of memory constantly. Any thoughts?

**Comment by d1str0** [comment]
Regarding celery, I've heard of this issue before but I do not have a solution for you atm.
