### ISSUE TITLE
error during installation of mhn sever: No matching distribution found for pyev>=0.5.3-3.8 (from evnet)

### ISSUE THREAD

**Issue by prahlad574** [threatstream/mhn#526]
The below line is the message that i got during the install of mhn (by running ./install.sh) and the installation aborted. I tried in ubuntu 16.04 and 14.04, CentOS 6.9, the same error repeated.

"_Could not find a version that satisfies the requirement pyev>=0.5.3-3.8 (from evnet) (from versions: )
No matching distribution found for pyev>=0.5.3-3.8 (from evnet)."_

Regards.

**Comment by joeneldeasis** [comment]
Add this `pip install -e git+https://github.com/HurricaneLabs/pyev.git#egg=pyev` 
before this line `pip install -e git+https://github.com/threatstream/evnet.git#egg=evnet-dev` on file `/opt/mhn/scripts/install_hpfeeds.sh`

**Comment by d1str0** [comment]
Please see #521 and #525

**Comment by prahlad574** [comment]
Thank you.
