### ISSUE TITLE
IPC connect call failed

### ISSUE THREAD

**Issue by remix30303** [threatstream/mhn#537]
Hi,
I'm installing mhn and i type sudo ./install.sh and i get error:
``Executing: /tmp/apt-key-gpghome.lrc0tnIiLz/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.lrc0tnIiLz/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr``
I'm on kali linux. What should i do?

**Comment by d1str0** [comment]
Kali is not a supported OS for MHN installation. If you can get it to work, that's great, but we have no resources to support it.
