### ISSUE TITLE
Populating Attacks

### ISSUE THREAD

**Issue by rachelcohen2** [threatstream/mhn#541]
Hi everyone, 

I followed the set-up instructions  in this tutorial and I have MHN up and running:

[https://medium.com/@himynamesdave/deploy-a-network-of-honeypots-in-minutes-for-only-5-77c5ca7f49d1](url)

I'm running Ubuntu 14.04. When I went to deploy a sensor, I copied the deployment script for the Ubuntu 14.04 Dionaea and it ran without error (after refreshing the sensor page I am able to see my new sensor added). How do I begin to populate events generated with this sensor? 

I was following the demo in this video:
[https://www.youtube.com/watch?v=9W0-hKBXU2E&t=333s](url)

When I issue the wget command, I am getting a redirect which appears to be the login panel of MHN.

Thanks in advance.

**Comment by d1str0** [comment]
Discussion taking place in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/modern-honey-network/Yf-CufqvdXQ/H1cjhoL0AgAJ

**Comment by d1str0** [comment]
Please reopen if issues persist
