### ISSUE TITLE
How to delete specific sensor alert (Snort)

### ISSUE THREAD

**Issue by Michealpool** [threatstream/mhn#543]
Hello,

i have deployed MHN first time with snort and wordport sensor(all services deployed on same server ). i can see my own server IP in the alert on port 80 by snort(wordport is deployed on port 80 while i have changed Dashboard access port to 8085). Also i want to enable password protection on honeymap on port 3000. Kindly guide for that as well.

**Comment by Michealpool** [comment]
Can you please guide how to remove snort alert?
I have tried to enable password protection but its not working. any idea how to enable password protection?

**Comment by d1str0** [comment]
MHN wasn't really designed to be used with sensors installed on the MHN server. As for honeymap, it doesn't support password protection at this point. You might be able to add it using an nginx config, or you could restrict access to only your IP using a firewall.
