### ISSUE TITLE
How can I automate MHN

### ISSUE THREAD

**Issue by NitescuLucian** [threatstream/mhn#547]
I am interested in posting in real time all IP's which have connected to cowrie to https://abuseipdb.com/
How can I do this? Is there a place from where I can read the IP's?

**Comment by xmppadmin** [comment]
You can do it by using the MHN API

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NitescuLucian** [comment]
@xmppadmin, thanks, I know but how can ensure that I report every single attack as an individual request (in branches or not) in order to ensure that I would not duplicate data.

**Comment by d1str0** [comment]
You can listen to hpfeeds and handle all events coming in through that.
