### ISSUE TITLE
package mongodb-org is not available on ubuntu 32 bit

### ISSUE THREAD

**Issue by Sangvin** [threatstream/mhn#553]
In consequence, the ./install.sh fail
I think it may be added in the readme.
But i don't know what can be done to fix it

**Comment by deanhinson** [comment]
I am having the same problem. please someone help!

**Comment by Sangvin** [comment]
I switched my host to a 64bit to fix the problem, but i know this is just a workaround

**Comment by d1str0** [comment]
You can always manually install mongodb and then restart the mhn installation.
