### ISSUE TITLE
Add support for Project Nova 

### ISSUE THREAD

**Issue by sirmodok** [threatstream/mhn#56]
https://github.com/DataSoft/Nova

I have the deploy script all set up and everything installs/runs properly, I just have no idea how to integrate hpfeeds into the whole thing. The actual honeypots in use for project nova is honeyd, however the information compiled together from Nova is more useful than the actual honeyd logs. 

Anyways, this is just an idea if anyone wants to help out I can give you the deploy code I have already written.

**Comment by nullprobe** [comment]
Project Nova seems to be pretty much dead. Also, I don't know what the added value of the Nova logs would be in MHN.

**Comment by d1str0** [comment]
Nova seems pretty old. Until we have more people asking for this to be supported this will be closed.
