### ISSUE TITLE
Hurricane Labs pyev.git no longer available

### ISSUE THREAD

**Issue by synmacs** [threatstream/mhn#560]
So the git repo that Hurricane Labs had up for pyev has either been deleted or made private.  This was the repo used to fix issue #521.  I tried the kablanda repo with zero success.

**Comment by synmacs** [comment]
pip install -e git+https://github.com/couozu/pyev.git#egg=pyev

**Comment by royisanew** [comment]
I also meet the issue ！Anyone can resolve it？

**Comment by synmacs** [comment]
Pull the code in synmacs github repo - fixed there.

Mac

Please excuse any typos.  Autocorrect is evil!
