### ISSUE TITLE
Installation issue in Debian 9.5 - Failed building wheel for uWSGI

### ISSUE THREAD

**Issue by hackunagi** [threatstream/mhn#573]
I'm installing MHN on Debian 9.5 from Digital Ocean.
The issue occur while building uWSGI.
Logs below.

Building wheels for collected packages: uWSGI
  Running setup.py bdist_wheel for uWSGI ... |                                                                                                                                                                                              error
  Complete output from command /opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3skk5p/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-TH0ZoF --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying uwsgidecorators.py -> build/lib.linux-x86_64-2.7
  installing to build/bdist.linux-x86_64/wheel
  running install
  using profile: buildconf/default.ini
  detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/6/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
  Patching "bin_name" to properly install_scripts dir
  detected CPU cores: 1
  configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY -DUWSGI_VERSION="\"2.0.14\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="14" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -DUWSGI_XML -DUWSGI_XML_EXPAT -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
  *** uWSGI compiling server core ***
  [x86_64-linux-gnu-gcc -pthread] core/utils.o
  [x86_64-linux-gnu-gcc -pthread] core/protocol.o
  [x86_64-linux-gnu-gcc -pthread] core/socket.o
  [x86_64-linux-gnu-gcc -pthread] core/logging.o
  [x86_64-linux-gnu-gcc -pthread] core/master.o
  [x86_64-linux-gnu-gcc -pthread] core/master_utils.o
  [x86_64-linux-gnu-gcc -pthread] core/emperor.o
  [x86_64-linux-gnu-gcc -pthread] core/notify.o
  [x86_64-linux-gnu-gcc -pthread] core/mule.o
  [x86_64-linux-gnu-gcc -pthread] core/subscription.o
  [x86_64-linux-gnu-gcc -pthread] core/stats.o
  [x86_64-linux-gnu-gcc -pthread] core/sendfile.o
  [x86_64-linux-gnu-gcc -pthread] core/async.o
  [x86_64-linux-gnu-gcc -pthread] core/master_checks.o
  [x86_64-linux-gnu-gcc -pthread] core/fifo.o
  [x86_64-linux-gnu-gcc -pthread] core/offload.o
  [x86_64-linux-gnu-gcc -pthread] core/io.o
  [x86_64-linux-gnu-gcc -pthread] core/static.o
  [x86_64-linux-gnu-gcc -pthread] core/websockets.o
  [x86_64-linux-gnu-gcc -pthread] core/spooler.o
  [x86_64-linux-gnu-gcc -pthread] core/snmp.o
  [x86_64-linux-gnu-gcc -pthread] core/exceptions.o
  [x86_64-linux-gnu-gcc -pthread] core/config.o
  [x86_64-linux-gnu-gcc -pthread] core/setup_utils.o
  [x86_64-linux-gnu-gcc -pthread] core/clock.o
  [x86_64-linux-gnu-gcc -pthread] core/init.o
  [x86_64-linux-gnu-gcc -pthread] core/buffer.o
  [x86_64-linux-gnu-gcc -pthread] core/reader.o
  [x86_64-linux-gnu-gcc -pthread] core/writer.o
  [x86_64-linux-gnu-gcc -pthread] core/alarm.o
  [x86_64-linux-gnu-gcc -pthread] core/cron.o
  [x86_64-linux-gnu-gcc -pthread] core/hooks.o
  [x86_64-linux-gnu-gcc -pthread] core/plugins.o
  [x86_64-linux-gnu-gcc -pthread] core/lock.o
  [x86_64-linux-gnu-gcc -pthread] core/cache.o
  [x86_64-linux-gnu-gcc -pthread] core/daemons.o
  [x86_64-linux-gnu-gcc -pthread] core/errors.o
  [x86_64-linux-gnu-gcc -pthread] core/hash.o
  [x86_64-linux-gnu-gcc -pthread] core/master_events.o
  [x86_64-linux-gnu-gcc -pthread] core/chunked.o
  [x86_64-linux-gnu-gcc -pthread] core/queue.o
  [x86_64-linux-gnu-gcc -pthread] core/event.o
  [x86_64-linux-gnu-gcc -pthread] core/signal.o
  [x86_64-linux-gnu-gcc -pthread] core/strings.o
  [x86_64-linux-gnu-gcc -pthread] core/progress.o
  [x86_64-linux-gnu-gcc -pthread] core/timebomb.o
  [x86_64-linux-gnu-gcc -pthread] core/ini.o
  [x86_64-linux-gnu-gcc -pthread] core/fsmon.o
  [x86_64-linux-gnu-gcc -pthread] core/mount.o
  [x86_64-linux-gnu-gcc -pthread] core/metrics.o
  [x86_64-linux-gnu-gcc -pthread] core/plugins_builder.o
  [x86_64-linux-gnu-gcc -pthread] core/sharedarea.o
  [x86_64-linux-gnu-gcc -pthread] core/rpc.o
  [x86_64-linux-gnu-gcc -pthread] core/gateway.o
  [x86_64-linux-gnu-gcc -pthread] core/loop.o
  [x86_64-linux-gnu-gcc -pthread] core/cookie.o
  [x86_64-linux-gnu-gcc -pthread] core/querystring.o
  [x86_64-linux-gnu-gcc -pthread] core/rb_timers.o
  [x86_64-linux-gnu-gcc -pthread] core/transformations.o
  [x86_64-linux-gnu-gcc -pthread] core/uwsgi.o
  [x86_64-linux-gnu-gcc -pthread] proto/base.o
  [x86_64-linux-gnu-gcc -pthread] proto/uwsgi.o
  [x86_64-linux-gnu-gcc -pthread] proto/http.o
  [x86_64-linux-gnu-gcc -pthread] proto/fastcgi.o
  [x86_64-linux-gnu-gcc -pthread] proto/scgi.o
  [x86_64-linux-gnu-gcc -pthread] proto/puwsgi.o
  [x86_64-linux-gnu-gcc -pthread] lib/linux_ns.o
  [x86_64-linux-gnu-gcc -pthread] core/yaml.o
  [x86_64-linux-gnu-gcc -pthread] core/ssl.o
  core/ssl.c: In function 'uwsgi_ssl_init':
  core/ssl.c:17:9: warning: 'OPENSSL_config' is deprecated [-Wdeprecated-declarations]
           OPENSSL_config(NULL);
           ^~~~~~~~~~~~~~
  In file included from /usr/include/openssl/crypto.h:32:0,
                   from /usr/include/openssl/bio.h:20,
                   from /usr/include/openssl/conf.h:13,
                   from ./uwsgi.h:356,
                   from core/ssl.c:1:
  /usr/include/openssl/conf.h:92:1: note: declared here
   DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
   ^
  core/ssl.c: In function 'uwsgi_ssl_info_cb':
  core/ssl.c:26:24: error: dereferencing pointer to incomplete type 'SSL {aka const struct ssl_st}'
                   if (ssl->s3) {
                          ^~
  core/ssl.c: In function 'uwsgi_ssl_session_new_cb':
  core/ssl.c:62:69: error: dereferencing pointer to incomplete type 'SSL_SESSION {aka struct ssl_session_st}'
           if (uwsgi_cache_set2(uwsgi.ssl_sessions_cache, (char *) sess->session_id, sess->session_id_length, session_blob, len, uwsgi.ssl_sessions_timeout, 0)) {
                                                                       ^~
  core/ssl.c: In function 'uwsgi_ssl_new_server_context':
  core/ssl.c:408:46: warning: passing argument 2 of 'SSL_CTX_sess_set_get_cb' from incompatible pointer type [-Wincompatible-pointer-types]
                   SSL_CTX_sess_set_get_cb(ctx, uwsgi_ssl_session_get_cb);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~
  In file included from ./uwsgi.h:357:0,
                   from core/ssl.c:1:
  /usr/include/openssl/ssl.h:637:6: note: expected 'SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, const unsigned char *, int,  int *)}' but argument is of type 'SSL_SESSION * (*)(SSL *, unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, unsigned char *, int,  int *)}'
   void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
        ^~~~~~~~~~~~~~~~~~~~~~~

  ----------------------------------------
  Failed building wheel for uWSGI
  Running setup.py clean for uWSGI
Failed to build uWSGI
hpfeeds-logger 0.0.7.3 has requirement hpfeeds-threatstream==1.1, but you'll have hpfeeds-threatstream 1.0 which is incompatible.
Installing collected packages: uWSGI, pymongo, hpfeeds-threatstream, pygal, GeoIP, hpfeeds-logger, pysqlite
  Running setup.py install for uWSGI ... error
    Complete output from command /opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3skk5p/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-RJUJiq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python2.7/uWSGI:
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/6/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    detected CPU cores: 1
    configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY -DUWSGI_VERSION="\"2.0.14\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="14" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -DUWSGI_XML -DUWSGI_XML_EXPAT -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
    *** uWSGI compiling server core ***
    core/utils.o is up to date
    core/protocol.o is up to date
    core/socket.o is up to date
    core/logging.o is up to date
    core/master.o is up to date
    core/master_utils.o is up to date
    core/emperor.o is up to date
    core/notify.o is up to date
    core/mule.o is up to date
    core/subscription.o is up to date
    core/stats.o is up to date
    core/sendfile.o is up to date
    core/async.o is up to date
    core/master_checks.o is up to date
    core/fifo.o is up to date
    core/offload.o is up to date
    core/io.o is up to date
    core/static.o is up to date
    core/websockets.o is up to date
    core/spooler.o is up to date
    core/snmp.o is up to date
    core/exceptions.o is up to date
    core/config.o is up to date
    core/setup_utils.o is up to date
    core/clock.o is up to date
    core/init.o is up to date
    core/buffer.o is up to date
    core/reader.o is up to date
    core/writer.o is up to date
    core/alarm.o is up to date
    core/cron.o is up to date
    core/hooks.o is up to date
    core/plugins.o is up to date
    core/lock.o is up to date
    core/cache.o is up to date
    core/daemons.o is up to date
    core/errors.o is up to date
    core/hash.o is up to date
    core/master_events.o is up to date
    core/chunked.o is up to date
    core/queue.o is up to date
    core/event.o is up to date
    core/signal.o is up to date
    core/strings.o is up to date
    core/progress.o is up to date
    core/timebomb.o is up to date
    core/ini.o is up to date
    core/fsmon.o is up to date
    core/mount.o is up to date
    core/metrics.o is up to date
    core/plugins_builder.o is up to date
    core/sharedarea.o is up to date
    core/rpc.o is up to date
    core/gateway.o is up to date
    core/loop.o is up to date
    core/cookie.o is up to date
    core/querystring.o is up to date
    core/rb_timers.o is up to date
    core/transformations.o is up to date
    core/uwsgi.o is up to date
    proto/base.o is up to date
    proto/uwsgi.o is up to date
    proto/http.o is up to date
    proto/fastcgi.o is up to date
    proto/scgi.o is up to date
    proto/puwsgi.o is up to date
    lib/linux_ns.o is up to date
    core/yaml.o is up to date
    [x86_64-linux-gnu-gcc -pthread] core/ssl.o
    core/ssl.c: In function 'uwsgi_ssl_init':
    core/ssl.c:17:9: warning: 'OPENSSL_config' is deprecated [-Wdeprecated-declarations]
             OPENSSL_config(NULL);
             ^~~~~~~~~~~~~~
    In file included from /usr/include/openssl/crypto.h:32:0,
                     from /usr/include/openssl/bio.h:20,
                     from /usr/include/openssl/conf.h:13,
                     from ./uwsgi.h:356,
                     from core/ssl.c:1:
    /usr/include/openssl/conf.h:92:1: note: declared here
     DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
     ^
    core/ssl.c: In function 'uwsgi_ssl_info_cb':
    core/ssl.c:26:24: error: dereferencing pointer to incomplete type 'SSL {aka const struct ssl_st}'
                     if (ssl->s3) {
                            ^~
    core/ssl.c: In function 'uwsgi_ssl_session_new_cb':
    core/ssl.c:62:69: error: dereferencing pointer to incomplete type 'SSL_SESSION {aka struct ssl_session_st}'
             if (uwsgi_cache_set2(uwsgi.ssl_sessions_cache, (char *) sess->session_id, sess->session_id_length, session_blob, len, uwsgi.ssl_sessions_timeout, 0)) {
                                                                         ^~
    core/ssl.c: In function 'uwsgi_ssl_new_server_context':
    core/ssl.c:408:46: warning: passing argument 2 of 'SSL_CTX_sess_set_get_cb' from incompatible pointer type [-Wincompatible-pointer-types]
                     SSL_CTX_sess_set_get_cb(ctx, uwsgi_ssl_session_get_cb);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ./uwsgi.h:357:0,
                     from core/ssl.c:1:
    /usr/include/openssl/ssl.h:637:6: note: expected 'SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, const unsigned char *, int,  int *)}' but argument is of type 'SSL_SESSION * (*)(SSL *, unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, unsigned char *, int,  int *)}'
     void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
          ^~~~~~~~~~~~~~~~~~~~~~~

    ----------------------------------------
Command "/opt/mhn/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3skk5p/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-RJUJiq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/mhn/env/include/site/python2.7/uWSGI" failed with error code 1 in /tmp/pip-install-3skk5p/uWSGI/

![image](https://user-images.githubusercontent.com/19274126/42911472-6f41f546-8ac1-11e8-91be-b0f700b9e438.png)

**Comment by hackunagi** [comment]
This can be the reason.

uwsgi is not yet OpenSSL 1.1 compatible.

https://github.com/unbit/uwsgi/issues/1395

**Comment by K0zero** [comment]
hello, i also meet the same problem but i use ubuntu
how can i fix it?
i'm not really understand what you said
