### ISSUE TITLE
Installing MHN to Ubuntu 18 almost IMPOSSIBLE 

### ISSUE THREAD

**Issue by Jdelgado89** [threatstream/mhn#582]
I have been trying to install MHN to ubuntu 18. I kept getting the mongodb php key error. I bypassed that but now I keep getting HPfeeders-broker fatal. Has someone successfully installed MHN on Ubuntu 18. If so please advise.

**Comment by d1str0** [comment]
Please refrain from using explicit language.

**Comment by d1str0** [comment]
Mongodb install should work just fine now with the latest commit: dab84db

**Comment by d1str0** [comment]
If the latest code doesn't work, please comment here or open a new issue with updated information.
