### ISSUE TITLE
Send logs to Wazuh agent

### ISSUE THREAD

**Issue by camaro23** [threatstream/mhn#589]
Is it possible to send logs to a Wauzh agent? If so, what is the best way to implement this?

Thanks!

**Comment by d1str0** [comment]
I'm not familiar with Wazuh but if it can import json it can easily import it.

**Comment by d1str0** [comment]
Under /opt/hpfeeds/examples you can use either to_stdout.py or to_stdout_json.py to accomplish this. 

An example: `/opt/hpfeeds/examples/to_stdout_json.py localhost 10000 *hpfeeds-user* *hpfeeds-secret* mhn-community-v2.events /data/mhn-community-v2.events.log`

**Comment by d1str0** [comment]
Since this isn't really an issue, I'm closing this, although feel free to post your results here and we can add this to the wiki in the future.
