### ISSUE TITLE
/opt/cowrie/log/cowrie.out does not exist

### ISSUE THREAD

**Issue by f1r3walled** [threatstream/mhn#596]
Hello, everyone,
I'm getting the following error everytime I try to execute Cowrie automated installation script: and it happens in the final steps:

+ supervisorctl update
error: <class 'xmlrpclib.Fault'>, <Fault 92: 'CANT_REREAD: The directory named as part of the path /opt/cowrie/log/cowrie.out does not exist.'>: file: /usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 947

I have MHN panel running in a separated environment with Ubuntu 16.04 and I'm trying to install Cowrie in a different environment. I got this error while testing in both Ubuntu version (14 and 16).
Manually create the informed directory isn't an option because I tried and it did not work.

Any ideas on what can be happening?

Thank you!

**Comment by d1str0** [comment]
Fixed in #600
