### ISSUE TITLE
Can I make use of mhn generated honeypots behind Reverse Proxy?

### ISSUE THREAD

**Issue by 74cmonty** [threatstream/mhn#598]
I'm running web services in network zone DMZ controlled by router firewall.
Having only one public IP I'm using a reverse proxy to forward incoming requests to a dedicated web server.
Question:
Can I use mhn generated honeypots in this scenario behind Reverse Proxy?

THX

**Comment by d1str0** [comment]
You can run MHN behind the proxy. What I would suggest is finding which honeypot software you want to use as different ones use different ports. Cowrie, for example, listens for SSH on port 22. ElasticHoney uses the default elastic search port. 

Decide which honeypots you want to run and then forward those ports to the honeypots.
