### ISSUE TITLE
Errors in Ubuntu 18: snort, p0f and cowrie

### ISSUE THREAD

**Issue by netoeuler** [threatstream/mhn#601]
Hi! I did a 'git pull' in MHN after the alert in the Google Groups but the I'm getting the same errors that I had before the git pull.

One of them is when I try to deploy cowrie:
`Command "/opt/cowrie/cowrie-env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7F8bL5/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iPfMlw/install-record.txt --single-version-externally-managed --compile --install-headers /opt/cowrie/cowrie-env/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-install-7F8bL5/cryptography/`

The other is when I try to deploy snort. The installation seems to be ok but when I see the supervisor, it shows:
`snort                            FATAL     Exited too quickly (process log may have details)`

p0f seems to be ok too, bu the supervisor shows:
`p0f                              STARTING`

EDIT: Snort problem was solved. 
I saw the message 'ERROR: /opt/snort/etc/snort.conf(45) Missing argument to HOME_NET', so I manually have setted the IP in this variable.

EDIT2: p0f problem was solved.
I have already setted the IP. It was in /opt/p0f/p0f_wrapper.sh.

Just the cowrie problem persists.

**Comment by d1str0** [comment]
Thanks for the updates!

When I announced support for Ubuntu18 I not only jumped the gun (there's still an error on MHN install) but I was also referring to the MHN server *exclusively* although I did not make this clear, which is my fault.

If you could test #600 for me, I'd feel better about it before I merge it into "master". You will need to copy the new cowrie script and paste it under your Deploy panel and save it, before trying to deploy cowrie again.

**Comment by d1str0** [comment]
Should be fixed by #600

**Comment by netoeuler** [comment]
Hi! I tested just to be sure but unfortunatelly the issue which I had mentioned here is about installation. This error occur during the installation, so when it occur, it's aborted.

**Comment by d1str0** [comment]
I guess I should have read your cowrie error better. 

This is an error on cowrie installation? What OS are you running this on? If you could provide OS, version, and cloud provider (if applicable).

**Comment by netoeuler** [comment]
It's an AWS Instance with Ubuntu Server 18.04 LTS (HVM), SSD Volume Type. The kernel version is 4.5.

**Comment by AgoraSecurity** [comment]
I'm also getting an error when deploying (installing) a sensor with cowrie.
I think the issues are python dependencies related...
Errors I've found:
```
...
Building wheels for collected packages: twisted, cryptography, tftpy, pycparser
  Building wheel for twisted (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/57/2e/89/11ba83bc08ac30a5e3a6005f0310c78d231b96a270def88ca0
  Building wheel for cryptography (setup.py) ... error
  Complete output from command /opt/cowrie/cowrie-env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hLMAUj/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-IX6Kaq --python-tag cp27:
  warning: no previously-included files found matching 'setup.pyc'
  warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
  warning: no previously-included files matching 'lextab.*' found under directory 'tests'
...
```

And
```
...
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
pyopenssl 19.0.0 has requirement cryptography>=2.3, but you'll have cryptography 1.8 which is incompatible.
Installing collected packages: cryptography, configparser, pyopenssl, appdirs, pyasn1, pyasn1-modules, service-identity, tftpy
  Found existing installation: cryptography 2.5
...
```

**Comment by Jymit** [comment]
I have just faced the same.
> snort FATAL Exited too quickly (process log may have details)

I didn't want to create a new bug without chiming in here on the above - I can do so if that helps triage this, as I note #600 is for Cowrie. 

Note in Ub14 we have a `inet addr:` whereas in Ub18 we just have the 'inet'.
`DISTRIB_DESCRIPTION="Ubuntu 14.04.6 LTS"`
```
inet addr:x.x.x.x  Bcast:x.x.x.x  Mask:x.x.x.x
```

`DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"`
```
inet x.x.x.x  Bcast x.x.x.x  Mask x.x.x.x
```

From the Snort deploy.sh
  3 INTERFACE=eth0
 74 IP=$(ifconfig $INTERFACE | grep 'inet addr' | cut -f2 -d: | awk '{print $1}')
 75 sed -i "s/ipvar HOME_NET any/ipvar HOME_NET $IP/" snort.conf

I wonder if we could replace the `ifconfig` for `ip addr show dev eth0`. We would then need a _cut_ on the forward slash after the IP addr.

**Comment by DuckY1987** [comment]
Simplicity is the solution:

IP=$(hostname -I | awk '{print $1}')

Verified on Ubuntu 16.04, 18.04 and Centos 6.1 and 7.6

Of course assuming we have just one interface configured.

**Comment by DuckY1987** [comment]
So antother solution is: 

ip=$(ip -f inet -o addr show $INTERFACE|cut -d\  -f 7 | cut -d/ -f 1)

**Comment by DuckY1987** [comment]
So i solved all issues with above mentioned sensors on Ubuntu 18.04

PR #675
PR #680
PR #681

**Comment by d1str0** [comment]
@DuckY1987 super appreciative. Thanks. Unfortunately I’m out of town for the rest of the week and weekend for July 4th. Will merge when I return!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d1str0** [comment]
Please let me know if the current scripts on master branch aren't working for them! If something is still broken we can reopen this issue.
