### ISSUE TITLE
Can I run honeypot on port 22 in parallel to SSH jumphost?

### ISSUE THREAD

**Issue by 74cmonty** [threatstream/mhn#606]
Hi,
my question is:
Can I run honeypot on port 22 at the same time with a SSH jumphost?

Due to limitations in my network architecture (I have only 1 public IP) I need to use reverse proxy + port forwarding on router.
Certainly I can setup a honeypot on port 22 and run this in DMZ with port forwarding (on router).
However I want to run a SSH jumphost (with 2 factor authentication) for secure SSH access to any other server in DMZ.

THX

**Comment by 74cmonty** [comment]
OK, that makes sense.

There's another question though:
Would you agree that it makes sense to keep port 22 closed in case it is not needed instead of providing a honeypot to the outside world?

This would mean that I access my SSH jump host via VPN connection and use port 22 on the jump host.

**Comment by d1str0** [comment]
Running any service exposed to the internet is risky. Whether or not it's on port 22 doesn't matter.
