### ISSUE TITLE
deploy Dionaea error

### ISSUE THREAD

**Issue by weng6698175** [threatstream/mhn#610]
When installing the deploy Dionaea hints
“Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/honeynet/nightly/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/honeynet/nightly/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found”

**Comment by d1str0** [comment]
What script are you using and what kind of system are you attempting to deploy on?
