### ISSUE TITLE
Install fails at intializing database

### ISSUE THREAD

**Issue by Clickbaitcake** [threatstream/mhn#612]
Hello,

I am using Ubuntu 18.04 and getting this error right near the end of the install.
Can anyone help understand why this is happening?

> Initializing database, please be patient. This can take several minutes
> + python initdatabase.py
> Traceback (most recent call last):
>   File "initdatabase.py", line 5, in <module>
>     create_clean_db()
>   File "/opt/mhn/server/mhn/__init__.py", line 123, in create_clean_db
>     db.session.flush()
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
>     self._flush(objects)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
>     flush_context.execute()
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
>     rec.execute(self)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
>     uow
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
>     mapper, table, insert)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
>     execute(statement, params)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
>     return meth(self, multiparams, params)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
>     context)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
>     exc_info
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
>     context)
>   File "/opt/mhn/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.IntegrityError: (pysqlite2.dbapi2.IntegrityError) UNIQUE constraint failed: role.name [SQL: u'INSERT INTO role (name, description) VALUES (?, ?)'] [parameters: ('admin', '')] (Background on this error at: http://sqlalche.me/e/gkpj)
> root@LHRVM-HONEYCCC:/opt/mhn/server#

**Comment by d1str0** [comment]
Is it possible you've already tried an installation? UNIQUE constraint will fail if a database already exists (/opt/mhn/server/mhn.db) and you try to run the install script a second time.

Does this happen on a clean install? Is there a chance mhn.db already existed?

I would recommend deleting mhn.db and then running the install again, or if this is a cloud server, use a fresh image.
