### ISSUE TITLE
conpot is not working! [Error 98] Address already in use

### ISSUE THREAD

**Issue by kuan13** [threatstream/mhn#616]
![image](https://user-images.githubusercontent.com/44361630/50586703-aadd2580-0eb5-11e9-8610-3011f2cf66c3.png)

Any suggestions?

**Comment by d1str0** [comment]
Is there a chance you are running modbus or any other service on port 502?

**Comment by kuan13** [comment]
@d1str0 Thank you for the reply!
I solve it ! Because the supervisor has already run a conpot
