### ISSUE TITLE
GeoLite Legacy databases discontinued

### ISSUE THREAD

**Issue by juju4** [threatstream/mhn#617]
+ GeoLite Legacy databases are now discontinued (since Jan 2)
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

I believe honeymap is still using it.
https://github.com/threatstream/mhn/blob/dd5c57bade8711c0c8bd699060232425ad2a8082/scripts/install_honeymap.sh#L99

**Comment by d1str0** [comment]
Thank you for bringing this to our attention. :)

**Comment by f1r3walled** [comment]
Guys,
I had an urgent need to run and install the project in the last days and it was not possible due this problem (Geolite databases discontinuation). I tried to replace it with the newer version of Geolite databases, but I had no success (Maybe, I did something wrong or simply it is not possible).
So, to defeat the issue, I just poked around the Internet to find the required files (GeoIPASNum.dat.gz, GeoLiteCity.dat.gz and GeoLiteCityv6.dat.gz) and I added them to a private cloud server that I built for this reason, only.
So, TEMPORARILY, I'm sharing the address where I placed those files. Feel free if you want to use, too.
The address is: http://45.62.212.159/packages/ and the respective lines of my "install_honeymap.sh" file now looks like the following:

wget http://45.62.245.67/packages/GeoLiteCity.dat.gz && gzip -d GeoLiteCity.dat.gz
wget http://45.62.245.67/packages/GeoLiteCityv6.dat.gz && gzip -d GeoLiteCityv6.dat.gz
wget http://45.62.245.67/packages/GeoIPASNum.dat.gz && gzip -d GeoIPASNum.dat.gz

The MD5 hash of those files are:
24f082fa05a2bac804b664f6a0893aba  GeoIPASNum.dat.gz
ee40cec85682b456726b009c36afe845  GeoLiteCity.dat.gz
ca64d35383892b3e7f52888d9e73ee50  GeoLiteCityv6.dat.gz

You can use my Apache server address or simply download the files and point the installation to your own server.
The use and risk is not my responsibility. I just can say that I download all of them from sources such as Fedora Project.
This change should help to achieve a successful installation of MHN project while it is not repaired in consequence of Geolite database.

Hope it helps! :)

**Comment by f1r3walled** [comment]
> Guys,
> I had an urgent need to run and install the project in the last days and it was not possible due this problem (Geolite databases discontinuation). I tried to replace it with the newer version of Geolite databases, but I had no success (Maybe, I did something wrong or simply it is not possible).
> So, to defeat the issue, I just poked around the Internet to find the required files (GeoIPASNum.dat.gz, GeoLiteCity.dat.gz and GeoLiteCityv6.dat.gz) and I added them to a private cloud server that I built for this reason, only.
> So, TEMPORARILY, I'm sharing the address where I placed those files. Feel free if you want to use, too.
> The address is: http://45.62.212.159/packages/ and the respective lines of my "install_honeymap.sh" file now looks like the following (I'll keep eyes on server availability but it is stored in a bad cloud provider :-( ):
> 
> wget http://45.62.245.67/packages/GeoLiteCity.dat.gz && gzip -d GeoLiteCity.dat.gz
> wget http://45.62.245.67/packages/GeoLiteCityv6.dat.gz && gzip -d GeoLiteCityv6.dat.gz
> wget http://45.62.245.67/packages/GeoIPASNum.dat.gz && gzip -d GeoIPASNum.dat.gz
> 
> The MD5 hash of those files are:
> 24f082fa05a2bac804b664f6a0893aba GeoIPASNum.dat.gz
> ee40cec85682b456726b009c36afe845 GeoLiteCity.dat.gz
> ca64d35383892b3e7f52888d9e73ee50 GeoLiteCityv6.dat.gz
> 
> You can use my Apache server address or simply download the files and point the installation to your own server.
> The use and risk is not my responsibility. I just can say that I download all of them from sources such as Fedora Project.
> This change should help to achieve a successful installation of MHN project while it is not repaired in consequence of Geolite database.
> 
> Hope it helps! :)

Just saw now that there is a better solution wrote on #619.

**Comment by d1str0** [comment]
Should be temporarily fixed by the latest merge.

**Comment by unixfreaxjp** [comment]
would you please share again the recent ones of :

> ee40cec85682b456726b009c36afe845 GeoLiteCity.dat.gz

thank you in advance.

**Comment by d1str0** [comment]
@juju4 @f1r3walled @unixfreaxjp 

This should be fixed in the latest code with GeoLite2 being supported officially.
