### ISSUE TITLE
Error 404 Not Found when deploying Dionaea on Raspberry pi

### ISSUE THREAD

**Issue by iwanthoneypot** [threatstream/mhn#618]
Hello, I'm trying to deploy my Raspberry Pi as a Dionaea Honeypot. Unfortunately, while I am trying to deploy it by the command, I received an error 404.

> Processing triggers for libc-bin (2.24-11+deb9u3) ...
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
'+' wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
> --2019-01-15 18:31:36--  http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
> Resolving security.debian.org (security.debian.org)... 133.242.99.74, 2401:2500:103:11a::74
> Connecting to security.debian.org (security.debian.org)|133.242.99.74|:80... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: http://security-cdn.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb [following]
> --2019-01-15 18:31:37--  http://security-cdn.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
> Resolving security-cdn.debian.org (security-cdn.debian.org)... 151.101.8.204, 2a04:4e42:2::204
> Connecting to security-cdn.debian.org (security-cdn.debian.org)|151.101.8.204|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2019-01-15 18:31:38 ERROR 404: Not Found.

Note: on the fourth line, I put two ' between + to avoid the plus logo being a dot instead. I only add this right here.

Otherwise, everything else has been installed and MHN even detect my Raspberry Pi as a sensor.

Please help. Thank you so much.

**Comment by AizazAZ** [comment]
if you are being successful in what you are trying to achieve. would you please write a readme file. I also want to do something similar. 
Thanks.

**Comment by SigmazGFX** [comment]
Same here.. It fails on insttalling the old libssl 1.0.0_1.

**Comment by SigmazGFX** [comment]
I changed the repo in the script ad well as the version becasue 8u6 is nowhere to be found...
wget https://mirrors.ocf.berkeley.edu/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb

**Comment by HallefHerbeth** [comment]
After you download deploy.sh

Open the file with sudo nano
Edit the following line:

wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1 + deb8u6_armhf.deb


For this:

wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1 + deb8u8_armhf.deb

After that, run the installation.

**Comment by iwanthoneypot** [comment]
> I changed the repo in the script ad well as the version becasue 8u6 is nowhere to be found...
> wget https://mirrors.ocf.berkeley.edu/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb

and...

> After you download deploy.sh
> 
> Open the file with sudo nano
> Edit the following line:
> 
> wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
> sudo dpkg -i libssl1.0.0_1.0.1t-1 + deb8u6_armhf.deb
> 
> For this:
> 
> wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb
> sudo dpkg -i libssl1.0.0_1.0.1t-1 + deb8u8_armhf.deb
> 
> After that, run the installation.

Both of these worked. Sorry for the late reply, but yes, I can confirm this is the solution, at least when tested on local network.

**Comment by SigmazGFX** [comment]
Glad you've got it working! 
I'm sorry that I forgot to add the script change in my reply.. 
I just realized that would have been useful for anyone that didn't know that it needed to be done.

**Comment by SigmazGFX** [comment]
Glad you've got it working!

**Comment by HallefHerbeth** [comment]
Glad to have helped!
