### ISSUE TITLE
Migrating MHN to Ubuntu 16

### ISSUE THREAD

**Issue by coonsmatthew** [threatstream/mhn#620]
Are there any documented paths to upgrade MHN from Ubuntu 14 to Ubuntu 16? 
I'm not really worried about the Mongo database, but I'm more worried about having to re-deploy all of my honeypots. 

Is there a way to import secret keys/authentication tokens for a new build on Ubuntu 16 so my existing honeypots start sending data to my new server (provided it's on the same IP/hostname)? 

Thank you.

**Comment by d1str0** [comment]
You should be fine doing an upgrade through apt, but I can try and verify that for you. 

Cheers

Brady Sullivan

**Comment by coonsmatthew** [comment]
Thanks @d1str0! I will try it and see how it goes

**Comment by d1str0** [comment]
@coonsmatthew please reply with your results!

**Comment by coonsmatthew** [comment]
@d1str0 My systems support team is saying that a clean Ubuntu 16 install is preferred. Do you know/have documentation describing how to restore MHN on a clean install? 

I'm not so much worried about the attack information (I don't mind losing that), I just don't want to re-deploy/reconfigure honeypot pre-shared keys. If there's a way to install MHN on the new system and import key information so I don't have to re-deploy honeypots (they will just start talking to my new server)?

**Comment by d1str0** [comment]
If your IP doesn't change, you can straight copy the mongodb files over to the new machine, otherwise you will have to import the mongodb data related to the honeypots manually somehow.

If your IP doesn't change, the honeypots will be fine but they will be using the same hpfeeds username/password so that's the part you have to move over.

**Comment by coonsmatthew** [comment]
Cool, so if i'm not worried about the historical data, and my IP doesn't change, I just need to move the HPFeeds username/password info over to the new system, right? 

This may be a silly question, but where is that config file? I just want to be sure I'm backing up the right thing before doing the rebuild with Ubuntu 16.

**Comment by d1str0** [comment]
Well it's going to be the hpfeeds table/collection in Mongo you'll have to export/import. Does that make sense?

**Comment by coonsmatthew** [comment]
@d1str0 This is good to know. I was assuming it was saved somewhere in a config file, but since it's in the Mongo database, I will just be sure that we backup and restore the DB. 

An aside, is it possible to prune the DB? My database is getting somewhat large and I couldn't find documentation describing how to prune/delete data from the DB. I logged into and was poking around, but wasn't sure what tables I could drop/empty without running into issues. 

Thanks.

**Comment by d1str0** [comment]
Any tables dropped will repopulate with new data. So as long as you aren't worried about losing certain data, you should feel free pruning the DB. 

Review this page: https://github.com/threatstream/mhn/wiki/Deleting-Data-from-MHN
