### ISSUE TITLE
ERROR: Unknown OS

### ISSUE THREAD

**Issue by Clickbaitcake** [threatstream/mhn#621]
I am trying to install MHN on UBuntu 18.04 but get an error. I am not sure how to troubleshoot. Is anyone able to help?

I used image; _ubuntu-18.04.1.0-live-server-amd64_ Is that the issue?

`````
build-essential is already the newest version (12.3).
git is already the newest version (1:2.11.0-3+deb9u4).
libffi-dev is already the newest version (3.2.1-6).
python-dev is already the newest version (2.7.13-2).
python-pip is already the newest version (9.0.1-2).
supervisor is already the newest version (3.3.1-1+deb9u1).
libssl-dev is already the newest version (1.1.0j-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
++ which python
+ PYTHON=/usr/bin/python
++ which pip
+ PIP=/usr/local/bin/pip
+ /usr/local/bin/pip install virtualenv
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages (16.3.0)
Requirement already satisfied: setuptools>=18.0.0 in /usr/lib/python2.7/dist-packages (from virtualenv) (33.1.1)
++ which virtualenv
+ VIRTUALENV=/usr/local/bin/virtualenv
+ ldconfig /usr/local/lib/
+ bash install_mongo.sh
+ '[' -f /etc/debian_version ']'
++ lsb_release -r -s
+ '[' 9.7 == 14.04 ']'
++ lsb_release -r -s
+ '[' 9.7 == 16.04 ']'
**++ lsb_release -r -s
+ '[' 9.7 == 18.04 ']'
+ echo -e 'ERROR: Unknown OS\nExiting!'
ERROR: Unknown OS
Exiting!**
+ exit -1
````

**Comment by d1str0** [comment]
This is strange. It is thinking you are running Debian 9.7, not Ubuntu 18.04. 

Did you install Ubuntu on your system or are you trying to run MHN on a live instance?

**Comment by d1str0** [comment]
Please reopen if you have further info to provide.

**Comment by adamtimmins** [comment]
Just got this error, running the latest version of Ubuntu server. No idea to debug :/

**Comment by d1str0** [comment]
Which specific error? What was the output? @adamtimmins

**Comment by secprentice** [comment]
I still have this same issue.

`equirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages (16.7.7)
++ which virtualenv
+ VIRTUALENV=/usr/local/bin/virtualenv
+ ldconfig /usr/local/lib/
+ bash install_mongo.sh
+ '[' -f /etc/debian_version ']'
++ lsb_release -r -s
install_mongo.sh: line 11: lsb_release: command not found
+ '[' '' == 14.04 ']'
++ lsb_release -r -s
install_mongo.sh: line 13: lsb_release: command not found
+ '[' '' == 16.04 ']'
++ lsb_release -r -s
install_mongo.sh: line 15: lsb_release: command not found
+ '[' '' == 18.04 ']'
+ echo -e 'ERROR: Unknown OS\nExiting!'
ERROR: Unknown OS
Exiting!
+ exit -1
`

**Comment by d1str0** [comment]
@secprentice what version of ubuntu are you using? Where are you hosting it?
