### ISSUE TITLE
nginx problem

### ISSUE THREAD

**Issue by abay123** [threatstream/mhn#622]
Dear：
 I can install it, but it will show "/ etc/init.d/nginx: No such file or directory" when testing. Accessing ip: 3000 shows honeymap, but accessing ip: 80 means that the default page of nginx has nothing else. I tried centos7 and Kali have this problem, what should I do?
![default](https://user-images.githubusercontent.com/42140379/52761000-a0818000-304c-11e9-86cf-06527b71df5f.png)
![default](https://user-images.githubusercontent.com/42140379/52761750-a62c9500-304f-11e9-82d5-6c0f1e95129c.png)

**Comment by d1str0** [comment]
Ubuntu is the supported OS. 

Cheers

Brady Sullivan
