### ISSUE TITLE
504 Gateway timeout on Payloads and Dashboard

### ISSUE THREAD

**Issue by Jquinn147** [threatstream/mhn#627]
So I've been receiving a 504 error on my MHN server.  
Disk space - 300GB
RAM - 8GB

Today I tried reinstalling MHN to see if a fresh install would fix it.  It didnt.  I've also tried adding proxy_read_timeout 300; to /etc/nginx/sites-enabled/default but that didn't fix it either.  I can load all of the pages except for the Payloads and Dashboard.  Not too big of an issue, because I can just open up the Payloads directory on my honeypots, but its still frustrating none the less.

Also, all of my services are running.

**Comment by d1str0** [comment]
Please provide a gist of you /var/log/mhn-uwsgi.err file

**Comment by d1str0** [comment]
Can reopen when we have more information.
