### ISSUE TITLE
Fresh install on 18.04.2 results in geoloc FATAL exited too quickly

### ISSUE THREAD

**Issue by stevebeer** [threatstream/mhn#628]
**supervisorctl status:**
geoloc       FATAL     Exited too quickly (process log may have details)
(rest of proccesses are running fine)

**geoloc.err:**
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 64, in <module>
    'drupot.events': [drupot_events,],
NameError: name 'drupot_events' is not defined

Any idea's? 
Couldn't find any solution regarding the drupot_events error...

**Comment by stevebeer** [comment]
Same result in Ubuntu 16.04.

**Comment by d1str0** [comment]
Interesting. Thought I fixed this. Will release an update this weekend. 

Cheers

Brady Sullivan

**Comment by d1str0** [comment]
This error is fixed although geoloc is still having issues. Will continue to tweak.

**Comment by d1str0** [comment]
Should be fully fixed with latest code.

**Comment by stevebeer** [comment]
Can confirm that problem is fixed. 
Everything works perfect.
