### ISSUE TITLE
Install fails on git clone of hpfeeds-logger

### ISSUE THREAD

**Issue by soufaam** [threatstream/mhn#632]
hello everyone i'm trying to install mhn on ubuntu 18.04 and when I execute ./install.sh
i get this error: Command "git clone -q git://github.com/threatstream/hpfeeds-logger /opt/mhn/env/src/hpfeeds-logger" failed with error code 128 in None

**Comment by d1str0** [comment]
Are you using a cloud host or your own hardware?

**Comment by d1str0** [comment]
Are you running this as root or sudo?

**Comment by soufaam** [comment]
I'm using my own hardware 
I have tried ubuntu 16 it worked just fine

**Comment by sytek** [comment]
I am having this exact same issue. 

I am on a cloud environment. Have tester with Ubuntu 18 and 16. 
Fails when running using 'sudo' as well as 'root'.
