### ISSUE TITLE
MHN Server Website interface only map

### ISSUE THREAD

**Issue by CarlosLannister** [threatstream/mhn#64]
Hi,
I was trying to install mhn in a Xubuntu 14.04 64 bits. I run all the scripts and everything was installed correctly. 

But when I access to website I only can see the map. The top banner with settings and login does not appear. Any idea about that?, I tried access from different browsers and it´s the same. 

All the services are running:
geoloc                           RUNNING    pid 35687, uptime 0:43:18
honeymap                         RUNNING    pid 35688, uptime 0:43:18
hpfeeds-broker                   RUNNING    pid 15643, uptime 0:51:13
mhn-celery-beat                  RUNNING    pid 38140, uptime 0:03:08
mhn-celery-worker                RUNNING    pid 38141, uptime 0:03:07
mhn-collector                    RUNNING    pid 38142, uptime 0:03:07
mhn-uwsgi                        RUNNING    pid 38147, uptime 0:03:07
mnemosyne                        RUNNING    pid 33769, uptime 0:46:49

Thanks for all and the incredible project

**Comment by jjjan** [comment]
hello honeymap not working under linux 14.4 any good solution without downgrades of os.
honeymap                         FATAL      can't find command '/opt/honeymap/server/server'

**Comment by jt6211** [comment]
That means your honeymap installation failed.  Can you do this:

```
rm -rf /opt/honeymap
cd /opt/mhn/scripts
sudo ./install_honeymap.sh
```

And provide a text log of the output.

**Comment by amidkaraji** [comment]
thats not work for me 

go install: no install location for directory /opt/honeymap/server outside GOPATH

**Comment by jjjan** [comment]
it's not work for you because your colleague installed it before. why you copy his work? try to find more new project. may be your colleague installed all github. such as tpot. you searching for new one baby.
