### ISSUE TITLE
Deploy command for Ubuntu - Dionaea with HTTP fails

### ISSUE THREAD

**Issue by ilangovishnu** [threatstream/mhn#650]
I've setup my mhn application in one VM ( Ubuntu 14.04 (Trusty) )& trying to deploy my honeypot in the other VM ( Ubuntu 14.04 (Trusty) ). However, I'm unable to deploy honeypot in VM. Both the VM are hosted in Google cloud platform.

Deploy script : wget "http://{External-IP}/api/script/?text=true&script_id=2" -O deploy.sh && sudo bash deploy.sh http://{External-IP} ANRyoCKR

Below is the error message while running the script:
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
++ curl -s -X POST -H 'Content-Type: application/json' -d '{
        "name": "mhn-honeypot-1-dionaea", 
        "hostname": "mhn-honeypot-1", 
        "deploy_key": "ANRyoCKR",
        "honeypot": "dionaea"
}' http://<<ip>>/api/sensor/
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
++ uuid=

```

MHN - Application server logs:

```
ilangovishnupriya@mhn-admin:/opt/mhn$ tail -f /var/log/mhn/mhn.log
    rv = self.handle_user_exception(e)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_use
r_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispa
tch_request
    rv = self.dispatch_request()
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_r
equest
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./mhn/api/decorators.py", line 18, in wrapped_view
    if current_user and current_user.is_authenticated():
TypeError: 'bool' object is not callable
```

Firewall Settings in Google cloud:
`$ gcloud beta compute firewall-rules create mhn-allow-admin --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:3000,tcp:10000 --source-ranges=0.0.0.0/0 --target-tags=mhn-admin
`

`$ gcloud beta compute firewall-rules create mhn-allow-honeypot --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=all --source-ranges=0.0.0.0/0 --target-tags=mhn-honeypot
![Mhn-Script](https://user-images.githubusercontent.com/25672013/56463818-7a4fc780-6390-11e9-8927-ae50aadd4c11.PNG)
`

Thanks,
Vishnu

**Comment by j0rh3rp4** [comment]
The same error too

+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
++ uuid=

Thanks

**Comment by f1r3walled** [comment]
Same here! I'm also running MHN over HTTPS.
I tried to change /opt/mhn/server/config.py parameter SERVER_BASE_URL to use my IP address and also to use my server name, which is an A Record created under my domain, but in both cases, the error remains.

**Comment by ilangovishnu** [comment]
This was due to Flask- Login's version.
It worked once Flask- Login was downgraded to version 2.X

sudo su -
cd /opt/mhn
source env/bin/activate
pip uninstall Flask-Login==0.3.0 
pin install Flask-Login==0.2.11
supervisorctl restart mhn-uwsgi

Thanks

**Comment by j0rh3rp4** [comment]
> 
> 
> This was due to Flask- Login module's version in mhn application.
> It worked once Flask-Login version was downgraded to version 2.X
> 
> sudo su -
> cd /opt/mhn
> source env/bin/activate
> pip uninstall Flask-Login==0.3.0
> pin install Flask-Login==0.2.11
> supervisorctl restart mhn-uwsgi
> 
> Thanks

If I downgrade Flash-Login, I can't access to MHN via web

**Comment by j0rh3rp4** [comment]
I found this:
https://stackoverflow.com/questions/32983133/is-authenticated-raises-typeerror-typeerror-bool-object-is-not-callable

**Comment by d1str0** [comment]
This should be fully resolved with the latest commit 44ced5

**Comment by d1str0** [comment]
Please do a git pull inside /opt/mhn
Then run `sudo supervisorctl restart all`

**Comment by d1str0** [comment]
Lastly, thanks to everyone for reporting and commenting here. And especially @j0rh3rp4 because it had the exact issue and solution to fix it.

**Comment by f1r3walled** [comment]
That's just to say thanks to @ilangovishnu because your suggestion about Flask-Login module downgrade solved my problem.
