### ISSUE TITLE
Install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by seifreed** [threatstream/mhn#656]
The initial deploy of MHN fails on Ubuntu:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

The error is from the mongodb

`mongodb: unrecognized service`

**Comment by d1str0** [comment]
Just reverted the commit that made this change. Should work fine now.
