### ISSUE TITLE
Port to open on subnet

### ISSUE THREAD

**Issue by Nymeria1** [threatstream/mhn#659]
Hello,
I installed MHN and sensor Dionaea successfully.
I have two scenario:
In the same subnet:
- Attack works correctly
 - I see log of attacks on mhn-splunk.log in real time.

Sensor in different subnet of management:
- Attack works correctly
- I do not see the attack on log file. The file does not update 

I opened ports 10000,80,443,3000 from sensor to MHN as outbound rule.

Could you indicate me what ports I have to open to register attack also when sensor is in different subnet of management?

Many thanks

**Comment by d1str0** [comment]
10000 must be open for incoming on the MHN server.
