### ISSUE TITLE
Dionaea support on Ubuntu 18.04

### ISSUE THREAD

**Issue by jorkanofaln** [threatstream/mhn#666]
I looked at the scripts, didn't see any option to install dionaea on Ubuntu 18.04 LTS. Since April 2019, Ubuntu 14.04 LTS is now unsupported for those without commercial ESM support. Would it be possible to include Ubuntu 18.04 support, in the installation script for Dionaea? Furthermore, many cloud providers only offer Ubuntu 18.04 as well as 16.04, when it comes to Ubuntu images.

**Comment by d1str0** [comment]
Will try and get to this soon. In the meantime, if you figure it out, pull requests will be accepted.

**Comment by d1str0** [comment]
Latest deploy_dionaea.sh script works on 18.04, 16.04, and Raspbian.
