### ISSUE TITLE
mhn-collector FATA on new install 20190620

### ISSUE THREAD

**Issue by loust** [threatstream/mhn#672]
Hello,

Installing on Ubuntu 14, 16 and 18 which resulted in the same error:

```bash
raceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,
         ^
SyntaxError: invalid syntax```

This is causing `mhn-collector` to FATAL-ly exit too quickly. The above is from `/var/log/mhn/mhn-collector.err`

Thank you.

**Comment by jtsamas** [comment]
I wish @d1str0 could look into this... I tried a fresh installation and honeymap is not not recording any attacks events but the dashboard shows that activity... a step by step solution would be most appreciated

**Comment by tiancu1980** [comment]
hi loust the issue is as i found in line 165 that is not ending with an comma 
just edit /opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py and add an comma at the end of line 165 that is why the script reports SyntaxError: invalid syntax```

**Comment by d1str0** [comment]
`/opt/mhn/env/bin/pip install -r /opt/mhn/server/requirements.txt`

`sudo supervisorctl restart all`

This should update and restart the problem service.

**Comment by d1str0** [comment]
Please reply if you're still seeing issues.

**Comment by jtsamas** [comment]
> Please reply if you're still seeing issues.

This issue still exist.... what has really changed since Max GeoIP database ? I mean the honeymap is one of the most attractive parts of using the honey as attacks events can be viewed.... Please help resolve this issue

**Comment by nitrogen17** [comment]
@jtsamas lucky you because you tried the honeymap working. In my part, I struggled a lot to make the honeymap work. It will fix this soon.

**Comment by d1str0** [comment]
@jtsamas so mhn-collector is still fatal for you? Can you please show the output of your /var/log/mhn/mhn-collector.err ? It’s possible hpfeeds-logger wasn’t updated. 

‘/opt/mhn/env/bin/pip uninstall hpfeeds-logger’
Then reinstall with 
‘ opt/mhn/env/bin/pip install hpfeeds-logger

**Comment by jtsamas** [comment]
Mhn-collector is runnning however the mhn-collector.err has the following ;


SyntaxError: invalid syntax
Traceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  **File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,
         ^**
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  **File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,**
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "collector_v2.py", line 5, in <module>
    from hpfeedslogger import processors
  **File "/opt/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 166
    src_ip=dec.src_ip,**
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):

**Comment by jtsamas** [comment]
Cannot see any events on the honeymap 

http://hornet.cirt.zm:3000/

However the attacks are present on the dashboard.

**Comment by loust** [comment]
I didn't get the map to work when using dionaea that comes with MHN. When I installed dionaea 0.8, it showed the attacks on the map. I'm not referring to the map error in this case though, but regardless, I'll try again soon when I get my honeynet up again since I took it down due to tight budgeting at the moment.
