### ISSUE TITLE
p0f sensor tries to use eth0 instead of ens160 on Ubuntu 16.04

### ISSUE THREAD

**Issue by DuckY1987** [threatstream/mhn#674]
I added following to my deployment script:

Interface=$(basename -a /sys/class/net/e*)
sed -i "s/INTERFACE=eth0/INTERFACE=$Interface/" /opt/p0f/p0f_wrapper.sh

**Comment by d1str0** [comment]
PR #676 
Have you tested this on any cloud providers or your own hardware?

Will give this a test today.

**Comment by DuckY1987** [comment]
PR #678 added.

Tested on ubuntu 16.04

Same interface selection i added for the other deployment scripts.
