### ISSUE TITLE
Fix AttributeError: 'Location' object has no attribute 'lattitude' 

### ISSUE THREAD

**Issue by nitrogen17** [threatstream/mhn#682]
# Description

https://github.com/threatstream/hpfeeds-logger/blob/master/hpfeedslogger/processors.py

The error is from the wrong spelling of latitude in **hpfeeds-logger**. In _hpfeedslogger/processors.py line: 62_ , it declares as latitude but using lattitude in line 77

`File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 77, in geo_intel
AttributeError: 'Location' object has no attribute 'lattitude'`
 

## Fix
- [x] https://github.com/threatstream/hpfeeds-logger/pull/16

**Comment by jtsamas** [comment]
I also noticed that and changed it then but still no events on my honeymap; my code now looks something like this....


  if maxmind_geo:
        geo = maxmind_geo.city(ip)
        if geo:
            result['city'] = geo.city.name
            result['region_name'] = geo.subdivisions.most_specific.name
            result['region'] = geo.subdivisions.most_specific.iso_code
            result['longitude'] = geo.location.longitude
            **result['latitude'] = geo.location.latitude**
            result['country_code3'] = geo.country.iso_code
            result['postal_code'] = geo.postal.code
            result['country_code'] = geo.country.iso_code
            result['country_name'] = geo.country.name

**Comment by nitrogen17** [comment]
it will only fix this error on mhn log

`File "/opt/mhn/env/src/hpfeeds-logger/hpfeedslogger/processors.py", line 77, in geo_intel AttributeError: 'Location' object has no attribute 'lattitude'`

for me, the master branch is working except if you have public IP from Singapore.
