### ISSUE TITLE
why my supervisorctl status mhn-uwsgi,mhn-collector,mhn-celery-worker,mhn-celery-beat not exist

### ISSUE THREAD

**Issue by Suhaila123** [threatstream/mhn#713]
geoloc                           RUNNING   pid 30013, uptime 1:32:42
honeymap                         RUNNING   pid 30015, uptime 1:32:42
hpfeeds-broker                   RUNNING   pid 30014, uptime 1:32:42
mnemosyne                        RUNNING   pid 30012, uptime 1:32:42

after i configure the mhn server and run supervisorctl status i got the result above and my mhn honeypot cant open it will display welcome nginx.. anyone please help me how to solve this problems thanks

**Comment by chetan-cv** [comment]
I am suffering exactly same problem 
Did you solve it?
