### ISSUE TITLE
only "Unknown" flags for country

### ISSUE THREAD

**Issue by Arnaud-Burn** [threatstream/mhn#93]
I've made some tries with a Raspberry Pi and  Dionaea.

> When I was testing this system, everything worked well

So I've decided to mount few Raspis (differents external ranges)

> All had been installed correctly; attacks noticed on MHN dash, ...

BUT I've got no country flags this time (and was having them when testing).

> I've only got "Unknown" flags

I've saw that there is the same "problem" in few screenshots in your tutorials...

Is it normal or a misconfiguration ?

thanks

**Comment by d1str0** [comment]
If this is still an issue we can reopen
